### PR TITLE
Change wording for BB cloud orgs

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

* Change wording for BB cloud orgs

See [JENKINS-45561](https://issues.jenkins-ci.org/browse/JENKINS-45561).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
screen shot 2017-08-08 at 4 57 04 pm

**Comment by sophistifunk** [comment]
Maybe dogfood is just slow today 😁

**Comment by i386** [comment]
Great stuff 👍 I suppose the terminology for Bitbucket Server is coming in a different PR?

**Comment by sophistifunk** [comment]
Seems to have been a.... 

image

Communication breakdown. 

[ YAAAAAAAAAAAAAAAAAAAAH ]

Also... found that code, will fix.

**Comment by i386** [comment]
Haha

**Comment by sophistifunk** [comment]
No screenshot for this latest update, I give up trying to run BB locally.

**Comment by i386** [comment]
@sophistifunk thats fine by me mate. when you merge this in ill do some testing anyway 🐝

**Pull request merged**
