### PR TITLE
[FIX JENKINS-47310] Handle various cases of credential errors when loading the editor

### PR DESCRIPTION
**Pull request by kzantow**
# Description

Fixes cases where the editor attempts to display a credential dialog but it is hidden.

See [JENKINS-47310](https://issues.jenkins-ci.org/browse/JENKINS-47310).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
:bee: LGTM - not sure how to test the scenarios though... how does one make a "no push access" token?

**Comment by i386** [comment]
@michaelneale create an access token without push permission then use that.

**Comment by michaelneale** [comment]
@i386 I can't see how to not give it push permission, it isn't an option to uncheck.

**Comment by kzantow** [comment]
@i386 @michaelneale one way is to add a public / private repo that you don't own

**Comment by michaelneale** [comment]
this can go in IMO

**Comment by kzantow** [comment]
@cliffmeyers mind having a quick review before I merge this?

**Pull request merged**
