### PR TITLE
JENKINS-41373# Permission error reporting in JSON

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-41373](https://issues.jenkins-ci.org/browse/JENKINS-41373).

How to test:

- Create github accessToken credential id in system store and global scope
- Create a user in Jenkins and using matrix authorization give him overall read, job read permission
- Create GitHub org pipeline

```
curl -v -XPOST -H 'content-type: application/json' -u 'vivek:vivek' http://localhost:8080/jenkins/blue/rest/organizations/jenkins/pipelines/ -d 
'{
   "scmConfig" : {
      "config" : {
         "repos" : [
            "PR-7"
         ],
         "orgName" : "cloudbeers"
      },
      "uri" : "https://api.github.com",
      "credentialId" : "vivek-github"
   },
   "$class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubPipelineCreateRequest",
   "name" : "cb1"
}'
```
You should receive 403 error:

```
{
  "message" : "Failed to create pipeline: failureproject2. User vivek doesn't have Job create permission",
  "code" : 403,
  "errors" : [ ]
}
```

- Call update API on previously created jenkins org folder

```
curl -v -XPUT -H 'content-type: application/json' -u 'vivek:vivek' http://localhost:8080/jenkins/blue/rest/organizations/jenkins/pipelines/failureproject2/ -d 
'{
   "scmConfig" : {
      "uri" : "https://api.github.com",
      "config" : {
         "repos" : [
            "failure-project"
         ]
      },
      "credentialId" : "vivek-github"
   },
   "$class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubPipelineUpdateRequest"
}'
```

You should get 403 with error message:

```
{
  "message" : "Failed to update Git pipeline: failureproject2. User vivek doesn't have Job configure permission",
  "code" : 403,
  "errors" : [ ]
}
```

@cliffmeyers PTAL

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
LGTM - but need to have @cliffmeyers ack that it is what he is looking for. Assume it passes ATH etc etc.

**Comment by cliffmeyers** [comment]
Tested this and it works as expected. Nice! @vivek  do you think there is any value in returning a structured error in the `errors` array for this? I liked how you had an explicit `INVALID` in #759 when the credentials were not valid. It would be nice if this had a more explicit error code so I can more easily distinguish between the different 403 errors. I can be flexible on this though if you disagree or it would be difficult to implement.

**Comment by vivek** [comment]
@cliffmeyers errors array is field specific, in this case its higher level and the code there is reflects HTTP error codes, its also not tied to any field so sorry, I think its fine this way:)

**Comment by cliffmeyers** [comment]
Works for me! 🐝

**Comment by vivek** [comment]
ATH passes https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/1153/.

**Pull request merged**
