### PR TITLE
Bug/jenkins 44760 search is missing the clear button

### PR DESCRIPTION
**Pull request by NicuPascu**
# Description

adds a clear button to the fast search

See [JENKINS-44760](https://issues.jenkins-ci.org/browse/JENKINS-44760).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
Giving this a whirl now

**Comment by i386** [comment]
@cliffmeyers would you mind handling the code review?

**Comment by i386** [comment]
This looks great from my PoV 👍

**Comment by i386** [comment]
@NicuPascu can you do the corejs publishing dance and merge to master?

**Comment by vivek** [comment]
@i386 I am cherry picking it to 1.1.1-release branch.

**Pull request merged**
