### PR TITLE
add tag filter

### PR DESCRIPTION
**Pull request by runzexia**
Signed-off-by: runzexia <runzexia@yunify.com>

# Description

In the git pipeline, tag is also a typical use case, this PR allows users to list the pipeline of the tag through the api

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by halkeye** [comment]
Looking good so far, since its a WIP I'm going to hold off doing a full review (plus don't know that section of code yet), but certainly looks good to me so far.

**Comment by runzexia** [comment]
Currently added backend API support for filtering tags.The front page will be added to support the tag.
The front end will be contributed by @baymac

**Comment by halkeye** [comment]
Are you still working on this? It doesn't even compile on CI from an eslint issue

```
/home/jenkins/workspace/Plugins_blueocean-plugin_PR-1937/blueocean-dashboard/src/main/js/components/TagRow.jsx
   38:10  error  Missing semicolon  semi
```

**Comment by halkeye** [comment]
Also is there a jira ticket at all?

**Comment by baymac** [comment]
@halkeye I am assigned the front end part of the work. But at this moment I am not able to give time due to my GSoC commitments. This PR is planned to be implemented at some later stage of my GSoC coding period. In the meantime if someone is interested and have React experience can take a look at it. I will so try to find some freetime to work on it.

**Comment by baymac** [comment]
Raised an issue: https://issues.jenkins-ci.org/browse/JENKINS-57177

**Pull request closed without merging**
