### PR TITLE
Downstream job links UI

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

See [JENKINS-38339](https://issues.jenkins-ci.org/browse/JENKINS-38339).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
Functionality is done, but not ATH test so this isn't ready for merge RN. I just want to run the ATH and full test suite on dogfood.

**Comment by sophistifunk** [comment]
screen shot 2018-02-28 at 1 48 33 pm

**Comment by sophistifunk** [comment]
@NicuPascu could you please take a look at `Pipeline.jsx` in particular? I had to hand merge your changes and mine, and I'd like another pair of eyes on the result to make sure I didn't accidentally undo some of your changes :)

**Comment by NicuPascu** [comment]
LGTM, I also ran this branch locally and in my test cases my fix still works as expected

**Comment by sophistifunk** [comment]
@NicuPascu thanks for that mate

**Pull request merged**
