### PR TITLE
Feature/jenkins 38598 create pipeline from GitHub

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- Not ready for review yet.
- See [JENKINS-38598](https://issues.jenkins-ci.org/browse/JENKINS-38598).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
I am going to start testing

**Comment by michaelneale** [comment]
Looking good - put feedback in the doc

**Comment by michaelneale** [comment]
Tried latest "mocked" version - LGTM. 

One small :nit: was that when it was busy creating, it didn't disable the git/github buttons right at the top is all but I think can proceed.

**Comment by cliffmeyers** [comment]
Closing in favor of #812

**Pull request closed without merging**
