### PR TITLE
Hotfix/loading worm preloader

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- When opening certain pages directly, the loading worm would display on the screen indefinitely. Normally the worm is hidden by the success/failure handler for XHR calls. There are some screens however that get data exclusively from the preloader, which doesn't actually fire XHR calls.
- The change is that we now call "show" for the indicator for any fetch that hasn't opt'd out, and if the data is pulled from the preloader then we immediately make a call to "hide".
- You should be able to repro this scenario by deep-linking to the "Branches" tab for a multi-branch project with no branches, or the "Branches" tab for a non-multibranch project. "PR's" tab should also illustrate it.

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
if with and ATH happy - sounds good. 

Are there specific pages to see this on?

**Comment by michaelneale** [comment]
:bee: if you are comfortable with it and @kzantow is

**Comment by cliffmeyers** [comment]
ATH passed: https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/master/2025/pipeline/17

**Comment by cliffmeyers** [comment]
@kzantow mostly showed up in empty state cases. When a screen had data - even if it was provided just by the preloader - there were using some an extra fetch or two afterwards (e.g. for capabilities)  that would trigger hiding of the status indicator.

**Comment by cliffmeyers** [comment]
ATH passed: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/2027/

**Pull request merged**
