### PR TITLE
[FIX JENKINS-42135] Updated creation last steps

### PR DESCRIPTION
**Pull request by kzantow**
# Description

See the ticket for the test cases:

See [JENKINS-42135](https://issues.jenkins-ci.org/browse/JENKINS-42135).

Youtube video here: https://youtu.be/HUUzAVCtmEk

Requires upstream fixes from: #916 

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
While you are in the neighbourhood can you replace "Connect to a Git repository!" with "Connect to a Git repository"?

**Comment by kzantow** [comment]
ATH passing: https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/master/1889/pipeline/17

**Comment by kzantow** [comment]
@i386 no more shouting :)

**Comment by i386** [comment]
Wonderbar :)

**Comment by michaelneale** [comment]
Wow what an awesome video - I don't know how you manage to crank things out like this. Coffee? lots of it? 

Also: https://github.com/one-synth-challenge/ - I think we should all join that gitter room. 
I did get excited for a brief moment to think that maybe it was time for "keytars" to come back (the only thing from the 80s that hasn't yet come back, sadly). But I don't think it is about that...


I also took a look at the code, and kicked the tyres, looks great. Get it in! 

:bee: :bee: :bee:
:bee: :bee: :bee:
:bee: :bee: :bee:

Also:

**Comment by cliffmeyers** [comment]
@kzantow nice job mate. Those backend changes were the magic sauce!

**Pull request merged**
