### PR TITLE
[JENKINS-43588] Paginate Artifact list

### PR DESCRIPTION
**Pull request by imeredith**
# Description

See [JENKINS-43588](https://issues.jenkins-ci.org/browse/JENKINS-43588).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
Nice 👍

**Comment by michaelneale** [comment]
@imeredith artifacts tests need to change for this to pass - but nice progress

**Comment by i386** [comment]
This will need tests too, please.

**Comment by imeredith** [comment]
Fixing tests today

**Pull request merged**
