### PR TITLE
[FIXED JENKINS-36302] - show test totals in blue ocean

### PR DESCRIPTION
**Pull request by kzantow**
Related to issue #JENKINS-36302. 

Summary of this pull request: 
. Add test total display to test results page

image

image

image

@reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
Screenshot LGTM

**Comment by michaelneale** [comment]
@kzantow do you have a test project that you use to verify this?

**Comment by michaelneale** [comment]
🐝  thanks for tests. Not sure how to manually test all the states, but happy this has some test coverage.

**Comment by kzantow** [comment]
@michaelneale I've been using https://github.com/kzantow/failure-project but you need to push changes to see, well, changes

**Comment by michaelneale** [comment]
:bee: this looks good to me. Tested it with a branch on that repo.

**Comment by cliffmeyers** [comment]
Very nice job with the tests. I know we hadn't discussed Enzyme yet when this PR was submitted - eventually would be great to get them ported over so we are consistent, but definitely don't want to block the PR with that. 🐝

**Pull request merged**
