### PR TITLE
JENKINS-47211 ResultItem headers overflowing in Dashboard

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

See [JENKINS-47211](https://issues.jenkins-ci.org/browse/JENKINS-47211).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
Old and busted:

screen shot 2017-10-03 at 12 26 39 pm

**Comment by sophistifunk** [comment]
New hotness:

screen shot 2017-10-03 at 12 59 09 pm

**Comment by michaelneale** [comment]
@vivek will need a hand getting this one ported over to release/1.3

**Comment by vivek** [comment]
@michaelneale ok will do once its merged to master.

**Comment by michaelneale** [comment]
updated with de-flaky test stuff

**Pull request merged**
