### PR TITLE
[JENKINS-49272] Use node.type==PARALLEL to determine if a node is par…

### PR DESCRIPTION
**Pull request by imeredith**
…allel

# Description

See [JENKINS-49272](https://issues.jenkins-ci.org/browse/JENKINS-49272).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
very nice @imeredith great catch. :bee:

(I am looking at the ATH to catch this in future)

**Comment by michaelneale** [comment]
@imeredith ok - well I looked at the ATH - it does exercise a test very much like this problem, specifically for this case. However, both on master as well as this branch it runs fine. However clicking as a human is not fine. 

the line: 

```
wait.click(By.xpath("//*[contains(@class, 'pipeline-node')][3]"));
``` 

seems to click it successfully - but somehow this is not the case in reality - so I am at a bit of a loss regarding the ATH here. 

I think this is worthwhile merging and cherry picking for a new release as this is obviously a bad problem and needs to be addressed ASAP. 

I will keep thinking about the ATH problem

**Comment by michaelneale** [comment]
ok - I found it. The test was silly - was just looking for "secondBranch" text() - which the node would satisfy. I fixed it to search for a unit step title. 

I checked this fails on the master branch, and passes here, so if this goes green - we can be good to go.

**Comment by michaelneale** [comment]
@vivek @imeredith if this is all green - can someone merge this, and @vivek do a 1.4.1 release? as this is a rather annoying one.

**Comment by vivek** [comment]
@michaelneale sounds good. Thanks.

**Comment by michaelneale** [comment]
@vivek small one to cherry-pick to `release/1.4` I think...

**Pull request merged**
