### PR TITLE
bug/JENKINS-39853-table-actions * Partial fix for Dashboard table issues

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

See [JENKINS-39853](https://issues.jenkins-ci.org/browse/JENKINS-39853).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by sophistifunk** [comment]
Fixes it in that it makes it look like it used to. There's some re-arranging I need to do in JDL that should make this fix unnecessary.

**Comment by sophistifunk** [comment]
screen shot 2016-11-21 at 2 51 31 pm

**Comment by sophistifunk** [comment]
God I miss Flex.

**Comment by michaelneale** [comment]
NICE. 
Thanks @sophistifunk 

http://pr.sandbox.blueocean.io/pr-611/blue/organizations/jenkins/multibranch/branches/ looks good to me. 

:bee:

**Pull request merged**
