### PR TITLE
FIX JENKINS-38056 Duration of running Pipeline is not live

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-38056](https://issues.jenkins-ci.org/browse/JENKINS-38056).

depends on https://github.com/jenkinsci/jenkins-design-language/pull/98

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by tfennelly** [comment]
@scherler thor you have a few lint errors, but the changes look fine to me.

**Comment by michaelneale** [comment]
nice @scherler - needs some updating and lint etc - but this could be good, is there a video of it in action?

**Comment by scherler** [comment]
https://youtu.be/wasmM7s6lb8 @michaelneale

**Comment by i386** [comment]
That looks awesome @scherler 🌟 💯 🎆

**Comment by i386** [comment]
🐝

**Comment by tfennelly** [comment]
🐝 LGTM

**Pull request merged**
