### PR TITLE
Bug/icon invalid icon prop

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- Found during downstream upgrade from Blue Ocean 1.1 -> 1.2. Since material icons impl changed, the icon names being used did not align with the new component. e.g. "search" instead of "ActionSearch". In particular this was a problem in `TextInput.iconLeft/iconRight`.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
@cliffmeyers does this need to be backported/cherry picked to release/1.2? 

cc @scherler @vivek

**Comment by michaelneale** [comment]
nice one @cliffmeyers 

If this goes in, can you `git cherry-pick` the commit for a PR on release/1.2 (or vivek or I can do it, should be clean) as I expect this may be wanted there one way or another.

**Comment by vivek** [comment]
@cliffmeyers Its change in JDL, does it not require JDL release to NPM and have that version used by rest of blueocean frontend?

**Comment by cliffmeyers** [comment]
@michaelneale just FYI, this fix isn't critical as 1. all of our downstream code in Blue Ocean was already fixed to use appropriate values for `icon` prop, and 2. Blue Steel has done the same thing on their end.

For that reason, it's perhaps debatable whether we need to cherry pick to 1.2 if it will cause much extra work.

To @vivek point, yes absolutely I need to publish this. Will do now.

**Pull request merged**
