### PR TITLE
Jenkins 37505 RunDetailsTestView: Uncaught TypeError: Cannot read property 'self' of undefined

### PR DESCRIPTION
**Pull request by scherler**
# Description
RunDetailsTestView: Uncaught TypeError: Cannot read property 'self' of undefined

See [JENKINS-37505](https://issues.jenkins-ci.org/browse/JENKINS-37505).

AT https://github.com/jenkinsci/blueocean-acceptance-test/pull/25

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes -> https://ci.blueocean.io/blue/organizations/jenkins/Acceptance%20Test%20PR/detail/Acceptance%20Test%20PR/4/pipeline

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
@scherler this looks like https://rollbar.com/i386/blueocean/items/34/?item_page=0&#instances and  https://rollbar.com/i386/blueocean/items/29/?item_page=0&#traceback ? If so, mark them as resolved in Rollbar :)

**Comment by scherler** [comment]
Well I thought I wait until it is fixed in master and you gave me my bee. ;) Anyway did that now.

**Comment by i386** [comment]
@scherler oh right wasn't sure if you were aware we had rollbar working :D

**Comment by scherler** [comment]
it is linked in the ticket ;)

**Comment by scherler** [comment]
bee please ...as well for AT ;)

**Comment by i386** [comment]
🐝

**Comment by i386** [comment]
Sorry Im tired - I shouldn't be working haha

**Pull request merged**
