### PR TITLE
Update JDL version (and core-js by necessity)

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

Update JDL version (and core-js by necessity)

### CODE REVIEW

**Comment by michaelneale** [comment]
@sophistifunk 
```
validating dependencies in /home/ubuntu/slave/workspace/an_task_bump-jdl-2017-05-04-3E3TFW3HGWIRZUQSAH2B4UDUW52IEEASC5PGURKN6FJ4UFFNSQHQ/blueocean-dashboard
@jenkins-cd/blueocean-core-js should be 0.0.111 but found 0.0.109
@jenkins-cd/design-language should be 0.0.128 but found 0.0.127
You can use bin/cleanInstall to install the dominant dependency in various places.
```

**Comment by sophistifunk** [comment]
Regenerated shrinkwrap from scratch, hopefully it'll stay up to date for a while

**Comment by michaelneale** [comment]
@sophistifunk need a hug? 

```

[an_task_bump-jdl-2017-05-04-3E3TFW3HGWIRZUQSAH2B4UDUW52IEEASC5PGURKN6FJ4UFFNSQHQ] Running shell script
+ node ./bin/checkshrinkwrap.js
validating dependencies in /home/ubuntu/slave/workspace/an_task_bump-jdl-2017-05-04-3E3TFW3HGWIRZUQSAH2B4UDUW52IEEASC5PGURKN6FJ4UFFNSQHQ/blueocean-dashboard
@jenkins-cd/eslint-config-jenkins@0.0.2 missing in shrinkwrap
@jenkins-cd/js-builder@0.0.56 missing in shrinkwrap
@kadira/storybook@2.20.1 missing in shrinkwrap
babel@6.5.2 missing in shrinkwrap
babel-core@6.17.0 missing in shrinkwrap
babel-eslint@7.0.0 missing in shrinkwrap
babel-preset-es2015@6.16.0 missing in shrinkwrap
babel-preset-react@6.16.0 missing in shrinkwrap
babel-preset-stage-0@6.16.0 missing in shrinkwrap
chai@3.5.0 missing in shrinkwrap
enzyme@2.4.1 missing in shrinkwrap
eslint@2.13.1 missing in shrinkwrap
eslint-plugin-flowtype@2.25.0 missing in shrinkwrap
eslint-plugin-react@4.3.0 missing in shrinkwrap
gulp@3.9.1 missing in shrinkwrap
gulp-mocha@3.0.1 missing in shrinkwrap
mocha@3.1.0 missing in shrinkwrap
nock@8.0.0 missing in shrinkwrap
react-addons-test-utils@15.3.2 missing in shrinkwrap
redux-mock-store@1.2.1 missing in shrinkwrap
skin-deep@0.16.0 missing in shrinkwrap
You can use bin/cleanInstall to install the dominant dependency in various places.
```

**Comment by michaelneale** [comment]
:bee: you get the ATH badge

**Pull request merged**
