### PR TITLE
Add most of the developers to the codeowners list

### PR DESCRIPTION
**Pull request by halkeye**
Update Codeowners to match the current list of developers.

### CODE REVIEW

**Comment by halkeye** [comment]
@vivek do you want to stay on it?
@michaelneale do you want to be added

I'm wondering if its worth adding `@jenkinsci/blueocean-plugin-developers` (https://github.com/orgs/jenkinsci/teams/blueocean-plugin-developers/members) so it doesn't need to be updated all the time

**Comment by michaelneale** [comment]
I don't mind staying

**Comment by halkeye** [comment]
> I don't mind staying

you were apparently never on it

**Comment by vivek** [comment]
>do you want to stay on it?
@halkeye yes, don’t mind staying on it.

**Pull request merged**
