### PR TITLE
Added a submitter checklist item for providing test instructions for the reviewer

### PR DESCRIPTION
**Pull request by tfennelly**
**Decription**

**Submitter checklist**
- [x] Change is code complete and matches issue description. __Not Applicable__
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests. __Not Applicable__

**Reviewer checklist**
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees 

Otherwise the reviewer probably does not know what/how to test the PR.

### CODE REVIEW

**Comment by tfennelly** [comment]
I just noticed a number of typos in this template haha

**Comment by michaelneale** [comment]
🐝  @tfennelly that was written by @i386 who has the worst spelling ever. Just the wurst.

**Comment by i386** [comment]
wurst_07

The Wurst.

**Comment by scherler** [comment]
ROFL :laughing: Stimmt Wurst ist gesund und alles andere ist Käse. Classic!

**Pull request merged**
