### PR TITLE
Jenkins 38753 truncate graph labels

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description
* Update JDL dependency to pull in graph fix
See [JENKINS-38753](https://issues.jenkins-ci.org/browse/JENKINS-38753).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
Nice - :bee: from me and @brody taking a look. 

I made some long ones: 

screen shot 2017-02-16 at 1 32 26 pm

**Comment by i386** [comment]
Ship it!

**Comment by brody** [comment]
Looks good 🐝

**Comment by sophistifunk** [comment]
Man, we all type some bullshit when trying to generate long text to test stuff 😁

**Pull request merged**
