### PR TITLE
JENKINS-47042# HTTP proxy support for github access release/1.1

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-47042](https://issues.jenkins-ci.org/browse/JENKINS-47042).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by vivek** [comment]
Port of https://github.com/jenkinsci/blueocean-plugin/pull/1414

**Comment by michaelneale** [comment]
This fails - doesnt' validate accesstoken: 

https://ci.blueocean.io/job/blueocean/job/github-proxy-server-fix-1.1/1/artifact/acceptance-tests/target/screenshots/io.blueocean.ath.live.GithubCreationTest_testGithubCreation.png screenshot in the failure shows it (I reproduced locally) so this seems a :bug:

**Comment by vivek** [comment]
@michaelneale bug identified and fixed, waiting for CI run to finish.

**Comment by michaelneale** [comment]
ok once green - get it in

**Comment by michaelneale** [comment]
:bee: nice one for spotting

**Pull request merged**
