### PR TITLE
Add Chinese localization for pipeline editor

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@jenkinsci/code-reviewers Any one can help me to review this pr, tks.

**Comment by imeredith** [comment]
@LinuxSuRen nice work. One change I would like to see is that the default option is removed from all JS code and the default is only in Messages.properties (thanks for already doing this part). That way we dont have 2 defaults to update in the future. I know we still have code that does this, at some point it will be removed though.

**Comment by michaelneale** [comment]
@vivek this one is also ok to merge (along with other one)

**Comment by vivek** [comment]
@LinuxSuRen There are conflicts as result of merging #1617. Please fix these conflicts and this should be in good shape.

**Comment by LinuxSuRen** [comment]
@vivek Thanks for the tip, conflicts alread been fixed.

**Comment by michaelneale** [comment]
once this is green, can get it in

**Pull request merged**
