### PR TITLE
JENKINS-47211 Hot-fix for 1.3 to resolve ResultItem overflow

### PR DESCRIPTION
**Pull request by sophistifunk**
Hot-fix to resolve ResultItem overflow without JDL update (only on 1.3)

* NOT FOR MASTER * This will break if combined with #1440 

# Description

See [JENKINS-47211](https://issues.jenkins-ci.org/browse/JENKINS-47211).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
thanks @sophistifunk

**Comment by sophistifunk** [comment]
GithubCreationTest again.

**Comment by michaelneale** [comment]
soon will be able to update to release/1.3... just a minute

**Comment by michaelneale** [comment]
ok @sophistifunk updating this to `release/1.3` would be a good idea

**Comment by sophistifunk** [comment]
Righto, pulled merged and pushed. Fingers crossed.

**Comment by michaelneale** [comment]
:bee:

**Pull request merged**
