### PR TITLE
feature/JENKINS-35994 - freestyle missing empty states

### PR DESCRIPTION
**Pull request by cliffmeyers**
Related to issue # JENKINS-35994. 

Summary of this pull request: 
* Branches and Pull Requests tabs now check the pipeline to see if branch names are available. If not, it immediately renders an empty state message and suppresses any REST API calls that would otherwise produce 404.

@reviewbybees

### CODE REVIEW

**Comment by kzantow** [comment]
:bee: LGTM - screenshot, tho?

**Comment by michaelneale** [comment]
@cliffmeyers sorry build not happy about this one.

**Comment by cliffmeyers** [comment]
@kzantow here ya go!

freestyle-branches
freestyle-pull-requests

**Comment by cliffmeyers** [comment]
@michaelneale weird build error, complaining about a SHA mismatch. Must be a fluke, seems good now.

**Pull request merged**
