### PR TITLE
JENKINS-48571# Create MBP SCMSource with Id

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-48571](https://issues.jenkins-ci.org/browse/JENKINS-48571).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by vivek** [comment]
@stephenc Blueocean only creates MBP pipeline jobs. No APIs to update MBP jobs. PTAL.

**Comment by michaelneale** [comment]
simple - nice. If it is green - get it in. Maybe worth a cherry pick to release branch as well?

**Comment by vivek** [comment]
Looks like flaky ath test, replayed.

**Comment by vivek** [comment]
@michaelneale should be ok for 1.4 too but should wait for it to be merged to master and see there is no side effect?

**Pull request merged**
