### PR TITLE
Feature/jenkins 41740 empty state no branches

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- See [JENKINS-41740](https://issues.jenkins-ci.org/browse/JENKINS-41740).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
placeholder-2017-03-23-10-12-54

**Comment by cliffmeyers** [comment]
ATH passed (!) https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/master/1904/pipeline/17

**Comment by michaelneale** [comment]
@cliffmeyers nice - does this still need work so the empty states make sense for all 3 tabs?

**Comment by i386** [comment]
Amazing 😍 😍 😍

**Comment by michaelneale** [comment]
yes looking at the google doc, I think there are a lot of unrepresentable states described, and a lot of them don't make sense now we look closely, so I think the scope/description for this was wrong, so lets not hurry this one in.

**Comment by cliffmeyers** [comment]
@brody how does this screenie look to you?

**Comment by michaelneale** [comment]
let me know when you want me to review this (had a look with previous commits..)

**Comment by brody** [comment]
Very nice @cliffmeyers !!!

**Comment by cliffmeyers** [comment]
@michaelneale no real need to review again. The JDL changes were super minor, mostly just adding flow which is stripped anyways, but wanted to make sure nothing weird happened. Will merge this once I get the dependent JDL PR merged and published.

**Comment by michaelneale** [comment]
OK, obviously small conflict to resolve etc.

**Comment by cliffmeyers** [comment]
placeholder-no-prs

**Comment by cliffmeyers** [comment]
@michaelneale Changes on PR tab are implemented. cc @brody 

The new "no branches" placeholder will only be shown if it's multibranch and if there are no branches. Basically, all of the old empty states still apply. There is a separate JIRA ticket for Dashboard, and then another ticket that covers remaining empty states.

I'm confident we'll get everything for Dashboard and Pipeline Detail in place before release. I am not sure about Run Details... it's possible. But I don't think we need to do a big bang PR that changes everything. It would be very difficult to manage with other PR's landing.

**Comment by cliffmeyers** [comment]
ATH passed: https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/master/1915/pipeline/17

**Comment by cliffmeyers** [comment]
I'm going to merge this to master now, as I feel it's a significant improvement over the existing empty states, especially the much-reviled pull requests empty state with the do-nothing "Enable" button.

If there's an issue, I'm happy to revert it, I just want to avoid the entire merge / republish / retest dance in case another update to core-js or JDL lands in the the next few days.

**Pull request merged**
