### PR TITLE
 upgrade jira plugin to 3.0.6

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: olivier lamy <olamy@apache.org>

# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by olamy** [comment]
ci is failing for an other reason....

**Comment by halkeye** [comment]
why'd you update all the package-lock files?

**Comment by olamy** [comment]
@halkeye dohh that's weird I didn't touch any of those files manually... Only building/running the app that's weird.
Sorry I should have checked before committing...
I will fix that

**Comment by halkeye** [comment]
I'm trying to find proof, but looks like newer npm switched from sha1 to sha512 for verification, maybe, which is causing ci and local to mismatch

**Comment by halkeye** [comment]
you may want to re-create this branch

Also, what issue # is this for?

**Pull request closed without merging**
