### PR TITLE
Ath spelling

### PR DESCRIPTION
**Pull request by jsoref**
# Description
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`
Split from #1664

# Submitter checklist
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@vivek @imeredith

### CODE REVIEW

**Comment by jsoref** [comment]
```java
at io.blueocean.ath.live.creation.GitCreationTest.testHttpsPrivateRepository(GitCreationTest.java:59)
```
I'll have to figure out if this is a cross related thing...

**Comment by jsoref** [comment]
Ok, this is green, it should be reviewable

**Comment by jsoref** [comment]
@michaelneale / @vivek / @kzantow

**Comment by michaelneale** [comment]
this one seems ok for me - no external api spelling fixes. Ok with you @imeredith ?

**Comment by vivek** [comment]
We can merge once we have ok from @imeredith.

**Pull request merged**
