### PR TITLE
JENKINS-37873# Self link fix for branch queue items

### PR DESCRIPTION
**Pull request by vivek**
# Description

See https://issues.jenkins-ci.org/browse/JENKINS-37873

* Create a MB project that has '/' in one of the branch
* Trigger build of this branch, make sure it ends up in queue
* See run list page in blueocean and see the POST /runs results has Link self reference with properly encoded branch names. For details see the JIRA ticket.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.
ATH runs fine locally.

# Reviewer checklist
- [x] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by vivek** [comment]
@cliffmeyers over to you:)

**Comment by vivek** [comment]
@cliffmeyers I have marked it do not merge and wip, I guess you are going to make UI changes in this same PR?

**Comment by cliffmeyers** [comment]
@vivek you're too quick, my friend :) The UI change I mentioned hasn't even been merged yet, so you can merge this one whenever it's bee'd. I will pull it down and test it here shortly.

**Comment by cliffmeyers** [comment]
@vivek verified branch name is correctly encoded. Thanks!

**Comment by vivek** [comment]
@cliffmeyers great. I will wait for @imeredith or @mic to review the code.

**Comment by michaelneale** [comment]
nice, code looks great, I love it when most of the code is a test case ;) I have not tried this locally yet (got some other things to try/review) but I think can be 🐝  if others have tried it.

**Pull request merged**
