### PR TITLE
DO NOT REVIEW [JENKINS-45482] potential unit test

### PR DESCRIPTION
**Pull request by jtnord**
# Description

See JENKINS-45482](https://issues.jenkins-ci.org/browse/JENKINS-45482).

Potential unit test - I have not been able to get any unit tests to reliably work in Ubuntu, and on windows the compilation does not even work.  This fails for some seemingly unknown reason on my box so seeing if the CI setup is any better at running this...

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by jtnord** [comment]
WIP - just to get some feedback from the CI system.  Will eventually be closed and rebased into #1252

**Comment by michaelneale** [comment]
@jtnord FWIW the org folders will be retired in favour of plain MBP project creation at some point (not sure if that helps of hinders your efforts). 

Perhaps, given your TZ, if you could find time with Cliff or Keith to try running unit tests locally?

**Comment by jtnord** [comment]
build has gone already...  
@michaelneale I think this test is ok - but needs the extra test from #1259

**Comment by jtnord** [comment]
all rebased into #1252

**Pull request closed without merging**
