### PR TITLE
[JENKINS-37021] Commit messages are missing on the activity view

### PR DESCRIPTION
**Pull request by scherler**
# Description

Commit messages are missing on the activity view

See [JENKINS-37021](https://issues.jenkins-ci.org/browse/JENKINS-37021).

I will add AT for this as soon I implemented multiBranch support for AT

screenshot from 2016-08-22 17-39-43

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes. https://ci.blueocean.io/job/Acceptance%20Tests%20Param/39/

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
🐛 should display the latest commit message - showing the last message

jenkins blue ocean 2016-08-23 10-19-41

hellonode 2016-08-23 10-19-50

**Comment by michaelneale** [comment]
ie it should say "Remove thunderdome message"

**Comment by scherler** [comment]
Fixed

**Comment by i386** [comment]
🐝👍😎👌

**Pull request merged**
