### PR TITLE
Dockerfile usable for dogfood

### PR DESCRIPTION
**Pull request by ydubreuil**
This is a follow-up to [JENKINS-37141](https://issues.jenkins-ci.org/browse/JENKINS-37141).

Depends on a fixed Jenkins LTS version instead of latest to ensure reproducible builds.
Don't bypass installation wizard by default as it's here to enforce security.

With this, Docker image built from master branch should be usable for dogfooding, which would make https://github.com/cloudbees/blueocean-docker-image obsolete 

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
@ydubreuil I wonder why this didn't trigger the normal multibranch build?

**Comment by michaelneale** [comment]
this looks like a tricky one to test - how do we verify it is ok?

**Comment by ydubreuil** [comment]
I did trigger the normal builder, but there was a GitHub request limit issue on CI yesterday, I had to kill the build.

Testing will be possible with the auto-deploy environment, it's nearly ready.

**Comment by ydubreuil** [comment]
Replaced with #527

**Pull request closed without merging**
