### PR TITLE
JENKINS-43471 never delete the item on reenterant case

### PR DESCRIPTION
**Pull request by i386**
# Description

See [JENKINS-43471](https://issues.jenkins-ci.org/browse/JENKINS-43471).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by vivek** [comment]
Nice catch, LGTM 🐝

**Comment by michaelneale** [comment]
Tried locally and looks good - just waiting on ATH. @vivek we will want to cherry pick this when merged in with 1.0.1/release branch I think (as it is a valid fix we can push out)

**Comment by vivek** [comment]
@michaelneale sure.

**Comment by michaelneale** [comment]
ok already cherry picked to 1.0.1 branch and all good to go there. Will shoot an email offline.

**Pull request merged**
