### PR TITLE
[WIP] added Docker build file

### PR DESCRIPTION
**Pull request by robtec**
Related to issue # . 

Summary of this pull request: 

**Motivation**

- Useful if I want to get Blue Ocean up and running without having java, maven etc installed

- Common image to test features/PRs

**Building the image**

`docker build -f Docker.build -t jenkinsci/blueocean-plugin .`

**Run the Container (interactive)**

`docker run -it -v ~/.m2:/root/.m2 jenkinsci/blueocean-plugin mvn clean install`

**TODO**

Expose `8080` and create entry point file which builds (`mvn clean install`) and runs (`mvn hpi:run`)

Initial thoughts guys? 😄 

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
Thanks @robtec - is this similar to: https://github.com/jenkinsci/blueocean-plugin/pull/214 ? 

This does look handy for those that want to run it in dev mode quickly with only docker. Perhaps putting this in a /bin directory might make sense? (I can't remember if the Dockerfile can refer to a context one level above its directory though).

**Comment by michaelneale** [comment]
@robtec I like this. Could you put a description of it in the file itself, just like you did in the PR? Then when people discover it it will be explained. Perhaps a section in the main README.md too. This could indeed be handy for PRs etc.. Is gulp and nodejs required? Mvn should pull it down (last I tried with that image, I needed to setup a user for git so the tests would run, did you not see that break?)

**Comment by ndeloof** [comment]
suggestion : `COPY` package.json and pom.xml before you `COPY .` command, so you can resolve dependencies and won't have to re-run dependency resolution any time you change a file on project and rebuild container.

**Comment by batmat** [comment]
+1, in the same vein of what @ndeloof says, you possibly want to "warm up" the maven local cache (aka the _repository_) so that you don't have to download all the maven dependencies each time you run mvn clean install from the CLI. It could accelerate the build with an order of magnitude.

See https://github.com/batmat/jenkins-pr-tester/blob/master/Dockerfile#L13L19 for an example.

**Comment by michaelneale** [comment]
@robtec you able to address the above by @batmat and @ndeloof ?

**Comment by ydubreuil** [comment]
Hi, I missed your PR before starting to work on #268. I think it supersedes Dockerfile in this PR and supports keeping the local maven repository around for following builds. Would you mind taking a look?

**Comment by robtec** [comment]
@ydubreuil looks cool - if the guys are happy with #268 then I can close this PR

**Comment by michaelneale** [comment]
@robtec cool yes. Feel free to close.

**Comment by blueoceandeploy** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
