### PR TITLE
[JENKINS-51921] Prevent onClick of generated syntetic events in dropDown

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-51921](https://issues.jenkins-ci.org/browse/JENKINS-51921).

Prevent synthetic events to trigger onClick.

Some browser like FF and IE will fire an onClick event if you focus the dropDownButton in another event loop.

Base cause described in http://helephant.com/2008/01/16/focus-event-handler-run-in-different-order-in-ie-than-firefox/ more info https://allyjs.io/tests/event-sequence/table.html

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by scherler** [comment]
@sophistifunk @NicuPascu @imeredith ping? If noone screams I will merge this in 12h.

**Comment by sophistifunk** [comment]
LGTM 🐝

**Comment by NicuPascu** [comment]
LGTM

**Comment by scherler** [comment]
I am now publishing 0.163 and then raise the version (meaning doing the dance right now, before merging into trunk)

**Pull request merged**
