### PR TITLE
[FIX JENKINS-37793] Developer can see meaningful page titles

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-37793](https://issues.jenkins-ci.org/browse/JENKINS-37793).

Implemented the different titles. Will add AT when I will implement test for the JENKINS-38329 regression

screenshot from 2016-09-27 00-15-26
screenshot from 2016-09-27 00-02-18
screenshot from 2016-09-26 23-45-06

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees 

…tests

### CODE REVIEW

**Comment by bhermosa** [comment]
Yo no dasabia que hacia un delito la verdad me asuste porque entraran  mi
cel yp.solo.baje un archivo y si Fue así por que. Me sorprendí lo lamento
mucho

**Comment by i386** [comment]
🐛 this may have not been obvious on the ticket but it should be 

`Dashboard`
`$org / $pipelineName`
`$org / $pipelineName / $runId`

**Comment by scherler** [comment]
@i386 no it was not.

**Comment by scherler** [comment]
screenshot from 2016-09-27 01-27-34
screenshot from 2016-09-27 01-27-26

**Comment by i386** [comment]
@scheler the only problem there is then everything will start with `Dashboard - Foo...` and you won't see the significant portion.

I suppose thats true of `Jenkins – Foo...` too. Ideas?

**Comment by scherler** [comment]
@i386 no, not everything starts with Dashboard. It would look like the first screenshots, but with dynamic $org.

**Comment by i386** [comment]
@scherler oh ok - I was wrong then ;)

On reflection we should use `/` rather than `-` as the separator

**Comment by scherler** [comment]
@i386 so ```Pipeline myOrg / $pipeName```?

**Comment by i386** [comment]
@scherler without the "Pipeline" or "Run" prefix

**Comment by scherler** [comment]
@i386 but with the / instead - ok

**Comment by scherler** [comment]
@i386 should I merge if CI pass?

**Comment by i386** [comment]
sure thing :)

**Pull request merged**
