### PR TITLE
[FIXED JENKINS-49991] Link to home should not full refresh

### PR DESCRIPTION
**Pull request by shssoichiro**
# Description

See [JENKINS-49991](https://issues.jenkins-ci.org/browse/JENKINS-49991).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [X] Appropriate unit or acceptance tests or explanation to why this change has no tests
 - UX fix, no logic changes or new features
- [X] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
 1. Go to a page in Blue Ocean other than the home page (e.g. Create New Pipeline)
 1. Click the "Jenkins" link in the top left to return to the home page
 1. Verify that the app has returned to the Blue Ocean home page
 1. Verify that no full page refresh was performed

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by shssoichiro** [comment]
The test failure seems to be a spurious one:

```
03:27:55 INFO - Running: &amp#27;[0;32mStep 06 - close modal and confirm returned to Branches tab&amp#27;[0m
03:27:55 INFO - &amp#27;[0;32m✔&amp#27;[0m Element <.ResultPageHeader-close> was visible after 52 milliseconds.
03:27:56 INFO - &amp#27;[0;32m✔&amp#27;[0m Element <.RunDetails-content> was not present after 538 milliseconds.
03:28:01 INFO - &amp#27;[0;31m ✖ Error: timed out waiting for url to contain: /branches, full url=http://172.17.0.2:60632/blue/organizations/jenkins/runDetailsBackwardNavigation/activity&amp#27;[0m
03:28:01 INFO - &amp#27;[0;90m at Timeout.<anonymous> (/home/jenkins/slave/workspace/blueocean_PR-1734-INZAHLWFDFGVN4QMET5XMOAQGNAGILTRHSHKFYYGZMGPMYT2H52A/acceptance-tests/src/main/js/custom_commands/waitForLocationContains.js:44:21)
```

**Comment by vivek** [comment]
@shssoichiro Nice! Changes look good. I have restarted the CI build. 

I will let @sophistifunk @scherler review it as well.

**Comment by imeredith** [comment]
@shssoichiro Nice! CI tests failing seem unrelated, I kicked off the build again.

**Comment by imeredith** [comment]
:bee: from me

**Comment by sophistifunk** [comment]
LGTM

**Comment by vivek** [comment]
Changes are in core-js, lets wait for @scherler to give a bee before merging.

**Pull request merged**
