### PR TITLE
JENKINS-44624# Fix to avoid multiple open blueocean menu

### PR DESCRIPTION
**Pull request by vivek**
When there are more than one implementation of BlueOceanActionUrl which
implements RootAction, there would (of course) be multiple menu items on
the left menu.

This fix changes the abstraction where BlueOceanUrlAction is a final
class and BlueOceanUrlObjectFactory is factory of BlueOceanUrlObject,
which defines properties to render 'Open Blue Ocean' left side menu.

# Description

See [JENKINS-44624](https://issues.jenkins-ci.org/browse/JENKINS-44624).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by vivek** [comment]
cc: @alvarolobato PTAL

**Comment by michaelneale** [comment]
this works for me so :bee: - however - lets let @alvarolobato bless it before merging it if possible?

**Comment by alvarolobato** [comment]
@vivek the code looks good to me. I couldn't test it though, I'm going to test it in the morning.

**Comment by i386** [comment]
Cherry picked to 1.1

**Pull request merged**
