### PR TITLE
Fix tests in intellij

### PR DESCRIPTION
**Pull request by imeredith**
# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
:bee: as long as build not upset

**Comment by michaelneale** [comment]
@vivek again that error with tests: https://ci.blueocean.io/job/blueocean/job/fix_tests_intellij/1/display/redirect - something is baaaad with pipeline. or tests.

**Comment by vivek** [comment]
@michaelneale Which pipeline tests? I see these tests failing:

```
Failed tests: 
  ProfileApiTest.badTokenTest1:363 expected:<401> but was:<404>
  ProfileApiTest.badTokenTest2:375 expected:<401> but was:<404>
  ProfileApiTest.createUserFavouriteFolderTest:203 expected:<200> but was:<403>
  ProfileApiTest.createUserFavouriteTest:151 expected:<200> but was:<403>
  ProfileApiTest.getAuthenticatedUser:296 expected:<200> but was:<404>
  ProfileApiTest.getUserDetailsTest:126 expected:<alice@jenkins-ci.org> but was:<null>
```

Looks like my fix yesterday to resolve these failures didn't help. Is this running with latest master?

**Comment by michaelneale** [comment]
@vivek hrm - ok that was different errors

**Comment by michaelneale** [comment]
:bee: I think this can't hurt

**Comment by vivek** [comment]
LGTM 🐝

**Comment by michaelneale** [comment]
:bee: this seems to work for me

**Comment by cliffmeyers** [comment]
FYI @vivek @michaelneale those errors are the same I've seen in the branch for #1002

**Comment by vivek** [comment]
@cliffmeyers yeah, looks like the fix I made (pin jenkins-test-harness to 2.15, didn't help). Worse, it doesn't reproduce locally so it's getting harder to fix.

**Pull request merged**
