### PR TITLE
decodeURI text in branch filter

### PR DESCRIPTION
**Pull request by NicuPascu**
The value of the input should be uri decoded because it comes from the "branch" url get param that is uri encoded

# Description

See [JENKINS-44260](https://issues.jenkins-ci.org/browse/JENKINS-44260).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
This shows "undefined" as the default value in the drop down: 

screen shot 2017-05-16 at 5 39 08 pm

Also there is a failure in the ATH (see the log linked) to do with this - probably just picking up the same thing.

**Comment by i386** [comment]
It would be good if we could get a unit test here.

**Comment by michaelneale** [comment]
yes agree - could that way check it is never undefined

**Comment by NicuPascu** [comment]
Ivan says that making a test for this is quite involved and we need to talk to Cliff about making this easier, should we create another ticket for the test and merge this branch or wait for the test before merging?
We will try to talk to Cliff tomorrow morning.

**Comment by michaelneale** [comment]
I think this is fine to go in as it is already :bee:

Nice one @NicuPascu !

**Pull request merged**
