### PR TITLE
[JENKINS-37859] Allow for 60s of clock skew

### PR DESCRIPTION
**Pull request by imeredith**
# Description

See [JENKINS-37859](https://issues.jenkins-ci.org/browse/JENKINS-37859).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
looks good (but have not tried it), how come there are changes to endSlash in this?

**Comment by imeredith** [comment]
@michaelneale because I branched off of the other PR by accident.

**Comment by michaelneale** [comment]
@imeredith so shoudl other PR be folded into this one?

**Comment by i386** [comment]
@imeredith @michaelneale just rebase this branch against master and then remove the end slash commits when doing so

**Comment by imeredith** [comment]
@michaelneale @i386 lol i had already rebased before either of your comments!

**Comment by kzantow** [comment]
just merge the end slash change ;) @imeredith

**Comment by kzantow** [comment]
looks fine, AFAICT :bee:

**Pull request merged**
