### PR TITLE
Task/jenkins 46218 reorder source control buttons 2

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- See [JENKINS-46218](https://issues.jenkins-ci.org/browse/JENKINS-46218)
- Original goal of PR: implements the sorting of the SCM providers via `ordinal` concept used elsewhere with extensions. Move `sortByOrdinal` into js-extensions, add tests, then use that function in the places that need it.
- Fix up a number of issues with the CI build:
   - JDL build and tests are now run again via blueocean-plugin CI. We lost this automation when JDL was merged to blueocean-plugin repo
   - JDL package.json / shrinkwrap now validated for consistency via CI build. Also lost this during JDL merge, and there were numerous inconsistencies that I fixed.
   - js-extensions build and tests now run in CI (for the first time)
   - JDL tests migrated to use Jest for consistency

New stage graph is here: https://ci.blueocean.io/blue/organizations/jenkins/blueocean/detail/task%2FJENKINS-46218-reorder-source-control-buttons-2/8/pipeline

Experimental build that parallelizes building of Blue Ocean and JS libs is here: https://ci.blueocean.io/blue/organizations/jenkins/blueocean/detail/task%2FJENKINS-46218-reorder-source-control-buttons-2/12/pipeline

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
I may have gone wacky but I figured this was a fun experiment:

blueocean-parallel-graph

**Comment by cliffmeyers** [comment]
blueocean-stage-graph

**Comment by michaelneale** [comment]
:bee:

**Comment by cliffmeyers** [comment]
@NicuPascu since the RAF polyfill is only used in headless testing capacity I think a simple function is fine, although if you feel like that should change by all means file a new PR :)

**Comment by NicuPascu** [comment]
@cliffmeyers nope, you are right, I didn't realise it was used only for testing

**Pull request merged**
