### PR TITLE
Feature/jenkins 36582 favorites realtime

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- See [JENKINS-36582](https://issues.jenkins-ci.org/browse/JENKINS-36582).
- Testing steps:
 - Add several favorites to the dashboard, ideally a simple Pipeline job, multi-branch Pipeline job, and a Freestyle job.
 - Using the classic UI, launch the jobs in those order. Note that the first two jobs should begin running while the Freestyle job is queued.
 - Jobs should update with the correct status as the builds complete.
 - Refreshing the page in the middle of runs should render jobs in correct status.
 - Navigating away and back should render jobs in correct status.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [x] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
This needs to be updated to master to get the fix for the capabilities api that @imeredith put in late yesterday (as it is, won't load multibranch activities).

**Comment by cliffmeyers** [comment]
Created to describe some known bugs which were classified as minor by @michaelneale; decided this PR should move forward since most cases ought to be handled well.

**Comment by cliffmeyers** [comment]
Want to try one more refactor to simplify some code down before soliciting review.

**Comment by cliffmeyers** [comment]
Ready for review. Perhaps @kzantow you can have a look, this includes the `SseBus` we'd talked about yesterday. Didn't have any great ideas on how to address tests for this, short of the eventual ATH suite I'll write for Personalization. Feel free to ding me there if you feel like I should find a way to get something in now.

**Comment by michaelneale** [comment]
I fav'ed a master branch, and than run it (from Branches tab) but saw this in console: 

```
jenkins-js-extension.js:6213 GET http://localhost:8080/jenkins/blue/blue/rest/organizations/jenkins/pipelines/keith/branches/michaelneale/runs/9/ 403 (Forbidden)_updateJob @ jenkins-js-extension.js:6213_handleJobEvent @ jenkins-js-extension.js:6164(anonymous function) @ jenkins-js-extension.js:6135listener @ jenkins-cd-sse-gateway-0.0.7.js:1707
jenkins-js-extension.js:6067 Uncaught (in promise) Error: Forbidden(…)checkStatus @ jenkins-js-extension.js:6067
```

**Comment by cliffmeyers** [comment]
@michaelneale interesting, that URL was definitely malformed but wasn't producing an error in my local environment. Fixed in commit a407264.

I just ran the ATH locally and all 100 assertions passed. From looking at the log it appears there was an error in the classic UI when creating the job and trying to build it?

`
2016-08-15 03:32:58,831 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - Running:  [0;32mCreate frestyle Job "hijo"[0m
2016-08-15 03:33:03,673 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - Waiting on job "hijo" to be deleted.
2016-08-15 03:33:03,701 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - Job "hijo" deleted.
2016-08-15 03:33:05,392 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - Waiting on job "hijo" to be created.
2016-08-15 03:33:25,402 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - [0;31m ??? Error: Timed out waiting for job "hijo" to be created. Something must have failed earlier and the job creation did not succeed.[0m
2016-08-15 03:33:25,403 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - [0;90m    at null._onTimeout (/home/ubuntu/slave/workspace/Acceptance Tests Param/acceptance/src/main/js/custom_commands/waitForJobCreated.js:19:21)
2016-08-15 03:33:25,404 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner -     at Timer.listOnTimeout (timers.js:92:15)[0m
2016-08-15 03:33:25,418 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - Disconnected from the Jenkins SSE Gateway.
`

**Comment by michaelneale** [comment]
ok verified locally and with ATH

🐝

**Pull request merged**
