### PR TITLE
[FIX JENKINS-35768] filter by branch

### PR DESCRIPTION
**Pull request by kzantow**
# Description

See [JENKINS-35768](https://issues.jenkins-ci.org/browse/JENKINS-35768).

Will add tests when this gets refactored to JDL.

Go to the Activity tab of a multibranch project and click the branch filter in the branch column header... works like this:

filter-branches-tab

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
I am going to cry!

**Comment by michaelneale** [comment]
Looking good - but has stopped new builds showing up in activity screen (I am not sure if this is missing an event or something else has broken). But it is specific to activity screen. Either multibranch or non, no new jobs appear in that list.  


The ATH catches this here: 

https://github.com/jenkinsci/blueocean-acceptance-test/blob/master/src/test/js/notMultibranch/freestyleRunning.js
https://github.com/jenkinsci/blueocean-acceptance-test/blob/master/src/test/js/notMultibranch/pipelineRunning.js

are both failing as per: 

https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/1556/

This is legit, you can try running a job from the activity screen. 

That is one way to reproduce it, another is to open activity in another tab and run a build

**Comment by kzantow** [comment]
@michaelneale thanks for looking in to this. I still have a hard time reading the ATH log...

**Comment by michaelneale** [comment]
@kzantow no worries - in this case it actually reports the test failures in junit style, so easy to see what broke. I ran it locally though to see it run on the screen via VNC (in which case it was screamingly obvious). I am going to take a crack at writing an ATH to test the sorting specifically today if I can.

**Comment by kzantow** [comment]
@michaelneale ATH passing now, if you want to try this one out

**Comment by michaelneale** [comment]
:bee: and passes the ATH.

**Comment by michaelneale** [comment]
how did you work that out so quickly?

**Comment by i386** [comment]
Merge this IMMEDIATELY

**Comment by michaelneale** [comment]
I am working on an ATH that proves the filtering

**Comment by michaelneale** [comment]
yes, ATH runs for this - :bee: (with new test for this too)

**Pull request merged**
