### PR TITLE
[JENKINS-47918] "plugins" dir is created as root

### PR DESCRIPTION
**Pull request by ndeloof**
# Description

See [JENKINS-47918](https://issues.jenkins-ci.org/browse/JENKINS-47918).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] explanation to why this change has no tests : we don't have test suite for docker demo image
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
@ydubreuil @imeredith can you PTAL?

**Comment by michaelneale** [comment]
nice - @rtyler is that a yes?

**Comment by michaelneale** [comment]
edit: I am stupid, it is a yes, I didn't see the github tick... so many ways to approve...

**Comment by michaelneale** [comment]
thank you @ndeloof great catch

**Pull request merged**
