### PR TITLE
JENKINS-43249# Return empty capabilities for unknown class

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-43249](https://issues.jenkins-ci.org/browse/JENKINS-43249).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
is there a ticket/background for this?

**Comment by vivek** [comment]
@michaelneale https://issues.jenkins-ci.org/browse/JENKINS-43249

**Comment by michaelneale** [comment]
ATH seemed to get in a bit of a spin over this one - not sure if related or not

**Comment by i386** [comment]
Changes look fine 🐝

**Comment by vivek** [comment]
@michaelneale kicked off another ATH run, lets see.

**Comment by vivek** [comment]
ATH passes https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/master/2420/pipeline.

**Pull request merged**
