### PR TITLE
[JENKINS-44866] Make the history button a component

### PR DESCRIPTION
**Pull request by imeredith**
# Description

Unit tests incoming.

See [JENKINS-44866](https://issues.jenkins-ci.org/browse/JENKINS-44866).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
@imeredith what's the status of this one? it would be good to get this into 1.1.2

**Comment by sophistifunk** [comment]
Code looks pretty reasonable to me 🐝

**Comment by NicuPascu** [comment]
LGTM

**Comment by michaelneale** [comment]
code looks good

**Comment by i386** [comment]
@imeredith  Can this please be cherry picked to 1.1.x after verification on dogfood?

**Pull request merged**
