### PR TITLE
upgrade declarative to the released version 1.2

### PR DESCRIPTION
**Pull request by michaelneale**
# Description

A simple version bump. see 

https://issues.jenkins-ci.org/browse/JENKINS-47083

@abayer @kzantow anything more than this needed?

### CODE REVIEW

**Comment by michaelneale** [comment]
@vivek will need help resolving this one with all the bounds checking... (which is new, and probably good, I hope)

**Comment by vivek** [comment]
@michaelneale upper bound check is enforced from parent plugin-pom, and yeah its supposed to do good to ensure one version of plugin/library version in class path. I am going to take a look at it.

**Comment by vivek** [comment]
@michaelneale pipeline-model-definition 1.2 was bringing in scm-api 2.2.2, we needed to bump it up from 2.2.1 to 2.2.2 as well.

**Comment by michaelneale** [comment]
this one is likely made redundant by https://github.com/jenkinsci/blueocean-plugin/pull/1394 - so will give that one a chance to land first...

**Comment by vivek** [comment]
@michaelneale This PR includes cleanup in rest-impl too (removes scm-api dependency). Can you get that change in #1394 as well? Or maybe upgrade declarative with this other change in this PR?

**Comment by michaelneale** [comment]
@vivek #1394 could be updated to have the rest-impl cleanup of removing scm api I think if we wanted...

**Pull request merged**
