### PR TITLE
Bug/jenkins 40163 baseline shift in breadcrumbs

### PR DESCRIPTION
**Pull request by NicuPascu**
# Description

See [JENKINS-40163](https://issues.jenkins-ci.org/browse/JENKINS-40163).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
Code changes are small, maybe can you inspect it visually @i386 ?

**Comment by i386** [comment]
Ill spin this up and take a look

**Comment by i386** [comment]
@NicuPascu looks good! Few changes here:
1. Can we remove the underline for the breadcrumb link in the header of the result dialog
2. The run number doesn't match the baseline of the breadcrumb

**Comment by michaelneale** [comment]
:bee: don't forget release dance!

**Comment by kzantow** [comment]
FYI, is helpful to link to other related PRs, if there are some

**Comment by michaelneale** [comment]
Good to go whenever makes sense @NicuPascu

**Pull request merged**
