### PR TITLE
JENKINS-37744# Support for Kyoto plugin

### PR DESCRIPTION
**Pull request by vivek**
# Description

See https://issues.jenkins-ci.org/browse/JENKINS-37744.

- cd blueocean && mvn hpi:run
- Create a kyoto style pipeline, you can clone vivek/hellokyoto
- Run this pipeline all stages and parallels should appear well
- Create legacy pipeline and all should work well
- Make sure anonymous read is disabled (default on fresh install), access http://localhost:8080/jenkins/blue or any other path inside blue should result in redirection to login page.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

Ran ATH master branch locally, all tests pass.

# Reviewer checklist
- [x] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees 

- Upgrades Jenkins core to 2.7.3 LTS
- Fixes regression where if JWT is disabled and anonymous read is not allowed access
  to /blue/... results in 403, resulting in to classic redirecting user to login page

### CODE REVIEW

**Comment by michaelneale** [comment]
:bee: - checked the above, seems good (I already had a new style pipe ready).

**Comment by imeredith** [comment]
LGTM 🐝

**Comment by abayer** [comment]
FYI, there's probably going to be another release of Pipeline Model Definition tomorrow - just bugfixes.

**Comment by i386** [comment]
Sounds good @abayer. Could you send us a PR with a version bump when it's out?

**Comment by abayer** [comment]
Sure thing!

**Pull request merged**
