### PR TITLE
JENKINS-44866 1.1.x merge

### PR DESCRIPTION
**Pull request by imeredith**
# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
as long as it passes and @vivek is happy

**Comment by michaelneale** [comment]
quite a few failures @imeredith - did you merge more than you bargained for?

**Comment by imeredith** [comment]
@michaelneale no there is enough divergance between 1.1 and 1.2 now that i have to rework ath specifically.

**Comment by michaelneale** [comment]
agree - :bee: once green tick!

**Pull request merged**
