### PR TITLE
JENKINS-37826# Regression listing Matrix style project on dashboard

### PR DESCRIPTION
**Pull request by vivek**
# Description

See https://issues.jenkins-ci.org/browse/JENKINS-37826

##Manual Test instructions
* Create matrix style project matrix1, added axises os  (linux, windows) and jdk (7, 8)
* Go to blueocean dashboard you should only see matrix1 project (none of its axis and value permutations should be listed)

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

Triggered https://ci.blueocean.io/job/Acceptance%20Tests%20Param/60/

# Reviewer checklist
- [x] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees 

…oesn't need flattening

### CODE REVIEW

**Comment by vivek** [comment]
@kzantow In pagination changes, 'hudson.matrix.MatrixProject' was removed accidentally on line 310 in actions.js, I have added it back and it lists matrix projects as expected.

**Comment by i386** [comment]
We need a test for this

**Comment by michaelneale** [comment]
This would have to be an acceptance test, as the backend tests cover this, it just needs to pass the argument. I think this is :bee: for such a small change.

**Comment by kzantow** [comment]
LGTM :bee: thought I kept all those during the merge, but must have botched this one :'(

**Comment by michaelneale** [comment]
:bee: :bee:

**Pull request merged**
