### PR TITLE
JENKINS-39790# SCM API to validate access token

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-39790](https://issues.jenkins-ci.org/browse/JENKINS-39790).

### Validate access token

This API does the following:

- Calls SCM provider API, for example GitHub API, to validate the token as well as look for appropriate scopes (in case of GitHub its repo and user:email). It picks up SCM provider from URL path (../scm/:id/validate)
- If the token is valid 
  - Look for domain 'github-domain' with github api url specifications in authenticated user's  credential store. If its not found then a new one is created. 
  - If the token is valid and there is no Jenkins credentials found with id 'github' in authenticated user scoped domain 'github-domain' then this new credential is created.
  - If there exists a Jenkins credentials with authenticated user scope, in user scope domain named 'github-domain' and credentialId == scm id 'github', then this credential is updated with the given token. SCM id is picked from URL path (../scm/:id/validate).
  - HTTP response with credentialId and status 200 is returned
- If the token is not valid for any reason then 403 error is returned with cause of validation failure.

eg: 
```
curl -v -u admin:admin -d '{"accessToken": "boo"}' -H "Content-Type:application/json" -XPUT http://localhost:8080/jenkins/blue/rest/organizations/jenkins/scm/github/validate 
```

Response:

````
{
  "credentialId" : "github"
}
````
If invalid/forbidden/unauthorized 403 error is returned. For bad request 400.

## Check SCM for available credentialId to use:

````
curl -v -u xxx:yyy http://localhost:8080/jenkins/blue/rest/organizations/jenkins/scm/github/

{
  "_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubScm",
  "_links" : {
    "self" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/"
    }
  },
  "credentialId" : ".....",
  "id" : "github",
  "uri" : "https://api.github.com"
}
````

@cliffmeyers @michaelneale @i386  This depends on certain core abstractions of PR 593. So we need to get that in before merging this.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests

Test is written but disabled as I can't use my personal access token with it. Any other ideas?

- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
@vivek nice work - implied in https://github.com/jenkinsci/blueocean-plugin/pull/673 is that with this api you can create credentials, but don't see how. Also, should the README.md be updated for this somewhere? (with the examples you posted)

**Comment by vivek** [comment]
@michaelneale I have updated the description above. Credentials creation is implicit, you validate and it creates a new one or updates the existing one. I can add it to somewhere in README.

**Comment by michaelneale** [comment]
This should create the domain if one doesn't exist already... BTW

**Comment by vivek** [comment]
@michaelneale Auto adding domain is implemented. If 'github-domain' in user's credentials store is not found a new one is created with Github API specification (host, path, scheme). README is updated as well.

**Comment by cliffmeyers** [comment]
@vivek validation definitely works very well; tested all the permutations with a real access key and it does the right thing. After successful creation I receive a response with:
```
{
  "credentialId": "github"
}
```

but I seem to have difficulty locating it. Is there a REST API call I can make to validate its presence? It doesn't seem to be returned by the search.

**Comment by michaelneale** [comment]
@cliffmeyers it is in the user - if you open classic and click on the user name, and then credentials - you can see the user scoped credential created. 

I ran: 

`curl -u admin:admin http://localhost:8080/jenkins/blue/rest/organizations/jenkins/scm/github/`
to see it returned -if that helps. 

This seems to work as advertised. :bee: from me, nice work @vivek !

**Comment by cliffmeyers** [comment]
@michaelneale right on, I see it now. I could not for the life of me find the right screen for this!

**Comment by vivek** [comment]
ATH and all other tests pass with latest master merge: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/725/

**Pull request merged**
