### PR TITLE
JENKINS-45595 Remove the server disambiguation (bitbucket)

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

* Remove server url display from BB server pipeline create

See [JENKINS-45595](https://issues.jenkins-ci.org/browse/JENKINS-45595).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
No screenshot, as I don't have a bitbucket server and Jenkins won't let me add a bogus one to the list.

**Comment by sophistifunk** [comment]
Also: This seems like a bad idea to me.

**Comment by michaelneale** [comment]
```

[INFO] /home/ubuntu/slave/workspace/ucket-remove-server-details-QVHPGZH5H2VEZK2HYMKJXLDEQPZM6ZWG3QJUTRWE3JUUZO6GI5SQ/blueocean-dashboard/src/main/js/creation/bitbucket/server/steps/BbChooseServerStep.jsx
[INFO]   91:15  error  'url' is defined but never used  no-unused-vars
```

@sophistifunk you think it is better to leave this in?

**Comment by sophistifunk** [comment]
Yes, being able to see the URL seems very handy if the user isn't sure what the names represent once they're added, or if they're troubleshooting, say if the names (or hostnames) are obscure codes that mean something internally, which is often the case. If you had a typo, or the host name has been changed but Jenkins doesn't know about that change.

**Comment by cliffmeyers** [comment]
I agree completely with this. In fact I've added it to GitHub Enterprise because it's very useful.

**Pull request closed without merging**
