### PR TITLE
JENKINS-43914# bleuocean-rest-impl test coverage improvement

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-43914](https://issues.jenkins-ci.org/browse/JENKINS-43914).

Test coverage now classes 100%, and 76% of line coverage.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
@vivek may as well update to master and kick off a new build - probably transient failure.

**Comment by vivek** [comment]
@michaelneale Merged latest master, lets see.

**Comment by michaelneale** [comment]
build failure: 

```
[WARNING] Rule violated for bundle blueocean-rest-impl: classes missed count is 1.00, but expected maximum is 0.00
```

**Comment by vivek** [comment]
Ugh, merging with master pulled in code that lacks this coverage, let me see.

**Comment by michaelneale** [comment]
hehe - the system works !

**Comment by michaelneale** [comment]
:bee: I have checked it out, looks good

**Pull request merged**
