### PR TITLE
Task/jenkins 37324 step description

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- See [JENKINS-37324](https://issues.jenkins-ci.org/browse/JENKINS-37324).

TODO:
- [x] Probably have to update some nightwatch tests that this will break.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
TODO:
- [ ] Probably have to update some nightwatch tests that this will break.

**Comment by cliffmeyers** [comment]
Long description, original code:
jenkins-41295-1-long-broken

Long description, after change:
jenkins-41295-2-long-fixed

Short description, original code:
jenkins-41295-3-short

Short description, after change:
jenkins-41295-4-short-fixed

No description (step only), after change:
jenkins-41295-5-no-description

**Comment by cliffmeyers** [comment]
@i386 for some reason, using `white-space: nowrap` isn't truncating the text; there seem to be some issues with with this when used with flexbox but I've been fiddling with it for a while with no luck.

I am going to spend a little more time with this - was also experiment with @sophistifunk 's `TruncatingLabel` component which did the truncation but had some other flashing issues... but it may have given me one or two other ideas on how to get this too cooperate.

Figured I would open the PR in the mean time, in case you think it looks acceptable for release we can always just merge now.

**Comment by i386** [comment]
@cliffmeyers this is acceptable to merge for now. 

Could you still follow up on truncation? If there is some work to do we need to schedule it.

**Comment by cliffmeyers** [comment]
Created https://issues.jenkins-ci.org/browse/JENKINS-44718 to track the bug.

**Pull request merged**
