### PR TITLE
JENKINS-38335# Slow search API response fix

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-38335](https://issues.jenkins-ci.org/browse/JENKINS-38335).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

Running ATH locally fails. If @michaelneale can give it shot will be great otherwise will try it tomorrow and ask for help around.

# Reviewer checklist
- [x] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees 

numberOfRunningPipelines is very expensive call, pretty much results in to
iteraring over all builds in the pipeline. With Search API, it gets worse as we
recursively iterate over each job/pipeline and determine if its running or not.
There is no esay way in Jenkins to compute this value optimally.

There is no UI code that needs this field and also numberOfQueuedPipelines field
is not used. As part of this fix, I am removing these fields from Pipeline API response.

### CODE REVIEW

**Comment by michaelneale** [comment]
look forward to driving this

**Comment by michaelneale** [comment]
odd @vivek not sure why REAME would conflict (some changes of Ivans I guess..)

**Comment by vivek** [comment]
@michaelneale conflict resolved. Btw, Ben installed plugins from this PR branch and his CI instance now loads dashboard successfully and search API call takes about 550ms, for me it took ~350ms. So thats another confirmation for this fix.

**Comment by michaelneale** [comment]
yes this looks great. :bee: - however, the ATH CI setup is busted right now, so may want to check it locally. I don't think this should have any impact as quite a small change. I think this should go in.

**Comment by michaelneale** [comment]
ATH passes: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/178/ so go for it unless @cliffmeyers objects (or anyone)

**Comment by tfennelly** [comment]
Awesome find @vivek .... I also love seeing code being deleted :)

🐝

**Pull request merged**
