### PR TITLE
JENKINS-36376# Annotate model classes with @Capability

### PR DESCRIPTION
**Pull request by vivek**
Related to issue # . 

Summary of this pull request: 
.
.
.

@reviewbybees

### CODE REVIEW

**Comment by cliffmeyers** [comment]
@vivek could you provide an example of the REST API in the README for this? I wasn't able to follow whether the endpoint needs to be called with a :id argument, or if the UI can simply call `/rest/classes/` to pull down all metadata information.

**Comment by vivek** [comment]
@cliffmeyers Its documented in this section: https://github.com/jenkinsci/blueocean-plugin/blob/master/blueocean-rest/README.md#class-of-resource-discovery

**Comment by cliffmeyers** [comment]
@vivek can we have a way to batch requests for multiple classes, or even pull down all of the known classes / capabilities that the backend supports in a single call?

I'm thinking ahead to the Pipelines screen, and we have at least three different types that will show up:  multi-branch, pipeline, and folder. As it stands now, I think we'd need to make three separate REST calls to fetch the capabilities for each, and then proceed with folder filtering. That seems a little heavy to me.

Since the metadata isn't something that will change, it seems sensible that we fetch it all once on initial app load. What do you think?

**Comment by cliffmeyers** [comment]
Discussed w/ Vivek and cut a new ticket for enhancement request. LGTM 🐝

**Pull request merged**
