### PR TITLE
Update dashboard fav card padding

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

Does what it says on the box.

See [JENKINS-41833](https://issues.jenkins-ci.org/browse/JENKINS-41833).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
screen shot 2017-04-03 at 2 41 55 pm

**Comment by michaelneale** [comment]
over to @brody @i386

**Comment by brody** [comment]
🐝

**Comment by sophistifunk** [comment]
Cheers lads.

**Pull request merged**
