### PR TITLE
JENKINS-48531# Upgrade to LTS 2.89.1

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-48531](https://issues.jenkins-ci.org/browse/JENKINS-48531).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by vivek** [comment]
PR to help debug PCT failure, we might eventually upgrade LTS.

**Comment by michaelneale** [comment]
@vivek perhaps should bump up some other versions of things that the PCT was saying are needed? (although we probably don't directly point to script security...)

**Comment by michaelneale** [comment]
@vivek perhaps should bump up some other versions of things that the PCT was saying are needed? (although we probably don't directly point to script security...) 

Also will need to update: https://github.com/cloudbees/blueocean-docker-image BEFORE merging this to master, or else it won't deploy on dogfood with the latest...

**Comment by vivek** [comment]
@michaelneale We do not intentionally depend on script-security, its supposed to come from upstream/core. @raul-arabaolaza is there anything else I should upgrade in blueocean to match URR?

**Comment by michaelneale** [comment]
hey @i386 we could bump required LTS - do you think it is time? (will need to also bump dogfood image etc... so not without cost). will mean people need latest..

**Comment by i386** [comment]
@michaelneale @vivek I am OK with this so long as this matches the next rolling that will ship along side 1.4

**Comment by vivek** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-48531 has been resolved as not defect, closing this PR.

**Pull request closed without merging**
