### PR TITLE
Experiment/ath wiremock

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- Experimenting with using Wiremock in ATH so we can more easily test edge cases

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
cc @kschultzcb

**Comment by cliffmeyers** [comment]
Need to track down a test failure first...

**Comment by cliffmeyers** [comment]
Fixed up now.

**Comment by michaelneale** [comment]
nice @cliffmeyers - could this help test things like bitbucket server as well? that may be a great use case as that has a gap right now.

**Comment by cliffmeyers** [comment]
@michaelneale absolutely. By default wiremock will proxy a HTTP/S endpoint, pass through requests to the endpoint and record all of the responses. This is how @vivek set up the unit tests for Github and Bitbucket so I'm really just building off his great work there.

I think for ATH which involves these third party services, we should strive to write the tests so they can be run in "live" or "mock" mode and perhaps we run mocks for our regular CI builds and then run live tests on a nightly or weekly basis.

**Comment by cliffmeyers** [comment]
cc @imeredith perhaps you can provide some feedback and a bee if you like what see here?

**Comment by imeredith** [comment]
I like what you have done but I would like to talk about this more. For example, i don't think we can use this method for end to end tests I think? :bee: for what is here, but will talk more next week. This ties in to what im looking at atm.

**Comment by michaelneale** [comment]
@cliffmeyers LGTM - I think we should just go with it, this covers things we don't otherwise have covered right?

**Comment by cliffmeyers** [comment]
@michaelneale strictly speaking it covers the same scenarios that the Github Enterprise test always did, although hopefully a bit more reliably without having to reach out to Github.

**Pull request merged**
