### PR TITLE
Update text-input.less

### PR DESCRIPTION
**Pull request by soufianez75**
resize input in pop up

# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by bitwiseman** [comment]
What is the visual difference this causes? 

Screenshots please.

**Comment by soufianez75** [comment]
Hello,

I have a long input who is cut



Le sam. 25 avr. 2020 à 20:52, Liam Newman <notifications@github.com> a
écrit :

**Comment by bitwiseman** [comment]
yes, I understand, but can you take a screenshot showing the before and after?

**Comment by soufianez75** [comment]
Hello,

You have attachements in my mail, you dont see?

Regards

Le dim. 26 avr. 2020 à 20:06, Liam Newman <notifications@github.com> a
écrit :

**Comment by soufianez75** [comment]
Capture d’écran 2020-04-25 à 23 02 56
Capture d’écran 2020-04-25 à 23 04 30

**Pull request closed without merging**
