### PR TITLE
workflow-support, scm-api, git, cloudbees-folders, matrix-folder, moc…

### PR DESCRIPTION
**Pull request by i386**
…kito

# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
@i386 nice: 

```
io.jenkins.blueocean.rest.impl.pipeline.BranchContainerImplTest.testBranchOrdering
io.jenkins.blueocean.rest.impl.pipeline.MultiBranchTest.createUserFavouriteMultibranchTopLevelTest
```

are only failures - will need @vivek to take a look at them at some point, probably some assumptions were violated. 

Both look like failures due to branch ordering:

**Comment by i386** [comment]
@michaelneale we should do a bump every month. I think this would be good for 1.1

**Comment by michaelneale** [comment]
@i386 agree.

**Comment by i386** [comment]
@vivek @michaelneale passes ATH https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/2042/

**Comment by vivek** [comment]
LGTM 🐝

**Pull request merged**
