### PR TITLE
Hibernation change has been going haywire on dogfood and on local mas…

### PR DESCRIPTION
**Pull request by i386**
# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees 

…ter with random refreshes.

Revert "Page reload after hibernate (#429)"

This reverts commit 9eaadfbb184464d6741c0f31d24ed1fc2d875329.

### CODE REVIEW

**Comment by i386** [comment]
@tfennelly FYI

**Comment by michaelneale** [comment]
@i386 you verified this locally?

**Comment by i386** [comment]
@michaelneale doing so now.

**Comment by kzantow** [comment]
:bee:

**Pull request merged**
