### PR TITLE
[FIX JENKINS-38751] Escape back to Jenkins classic

### PR DESCRIPTION
**Pull request by tfennelly**
# Description

See [JENKINS-38751](https://issues.jenkins-ci.org/browse/JENKINS-38751).

Can be manually tested. Look for the "escape to app" widget in the headers (main and run details).

screenshot 2017-02-22 16 44 16

ATH tests: https://github.com/jenkinsci/blueocean-acceptance-test/pull/123

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
nice to see this happening

**Comment by michaelneale** [comment]
@tfennelly is this ready for review?

**Comment by michaelneale** [comment]
not sure if this was final @tfennelly but it passed the ATH and :bee: from me as it looks great - but up to you.

**Comment by i386** [comment]
Did one get added on the result header too? Ticket called for one

**Comment by michaelneale** [comment]
@i386 yes it has one there 👏

**Comment by i386** [comment]
Sweet just checking 👏🏻🍾

**Comment by michaelneale** [comment]
and I checked with and without hpi:run

**Comment by tfennelly** [comment]
@michaelneale maybe you could give this and the ATH tests a quick pass again and a bee if ok. Thanks.

I had a serious pain ith with the ATH tests ... lost a fair bit of time on stupid shit, mostly confusion caused by myself.

**Pull request merged**
