### PR TITLE
bug/jenkins 42784 github creation single repo optimization changes

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- See [JENKINS-42784](https://issues.jenkins-ci.org/browse/JENKINS-42784).
- Currently if the user creates a single repo Github org folder that is empty or contains no Jenkinsfiles, there are no events sent back to the UI and it shows the very generic "pipeline creation pending" state (aka "timeout" state).
- This changes the logic so that org folder scanning is initiated in all cases, so that the "job_orgfolder_indexing_result" will propagate back to the UI and trigger the "create pipeline" state. 
- There are some concerns about this being wasteful that are totally legit, but trying to work within the limitations exposed by the upstream APIs.
- One other small advantage to this change is that the org folder now properly displays the Github org avatar (in classic). The prior code that was skipping the `organizationFolder.scheduleBuild()` call for single repo cases resulted in an org folder with a generic Github icon.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
cc @vivek @kzantow @michaelneale @i386 

Some folks have reservations about this approach and rightly so. If we discover that it's too wasteful or leads to strange inconsistent state in Jenkins then we can abandon it, and just change the UI to assume to show the "create pipeline" state when the event timeout is reached.

**Comment by kzantow** [comment]
I think this basically just undoes the optimization @vivek was trying to do...

**Comment by michaelneale** [comment]
@kzantow does it - it still fires the "shortcut" event it looks like? I'll give it a try.

**Comment by michaelneale** [comment]
This worked well for me with both the blank case and adding subsequent pipelines. Did not seem to slow it down. 

So assuming no one has objections  - :bee: from me (ATH was happy as of time of writing).

**Comment by kzantow** [comment]
I looked at this again, I think in the create case, we need to trigger the normal org scan, anyway otherwise it gets created incorrectly, without some of the data from github like the display name. I think we should just get rid of the single event for the create case, then it looks like they both would ultimately work correctly.

**Comment by michaelneale** [comment]
@kzantow isn't that what this is doing? Without the single event it is 60s to create a single repo still?

**Comment by michaelneale** [comment]
I believe after a discussion earler with Stephen C, @kzantow and @vivek were goign to look at some other approaches - is that fair to say? 

cc @cliffmeyers

**Comment by kzantow** [comment]
@michaelneale yes, going to see about adapting what we talked about earlier, probably can just close this PR

**Pull request closed without merging**
