### PR TITLE
upgrade to jira plugin 3.0.6

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: olivier lamy <olamy@apache.org>

# Description

See [JENKINS-50643](https://issues.jenkins-ci.org/browse/JENKINS-50643).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by halkeye** [comment]
@olamy the PCT was pretty stable last week. I've re-run this 3-4 times now, each time a PCT failure happens. Can you take a look and see if there's any chance the jira stuff breaks anything?

**Comment by olamy** [comment]
@halkeye yup I will try to reproduce locally....

**Comment by halkeye** [comment]
as you know PCT isn't perfect, but it is getting better. feel free to re-run while you investigate

**Comment by halkeye** [comment]
I suspect https://github.com/jenkinsci/blueocean-plugin/pull/1947/commits/6ce6d5e6db79b2fbf072984b0840f275880fc35b will help (not merged yet)

**Comment by halkeye** [comment]
@olamy can you rebase or close this?

**Comment by olamy** [comment]
close it. there will be a new one

**Pull request closed without merging**
