### PR TITLE
Fix test number '0' issue 

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

See https://issues.jenkins-ci.org/browse/JENKINS-47246

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
Can we run this in the cloud to test?

**Comment by sophistifunk** [comment]
screen shot 2017-09-29 at 3 49 22 pm

Old and busted

**Comment by sophistifunk** [comment]
New hot shit

screen shot 2017-09-29 at 3 49 43 pm

**Comment by sophistifunk** [comment]
Build still running, seems odd.

**Comment by michaelneale** [comment]
that test is being a SoB... I am pretty sure it is flaking... looking into it.

**Comment by michaelneale** [comment]
we do want this cherry picked too... to release/1.3

**Comment by sophistifunk** [comment]
It's only 3 characters, I'd just change it by hand rather than cherry-picking via git.

**Comment by michaelneale** [comment]
ok @sophistifunk :bee: from this - if you could open a `release/1.3` PR, or else @vivek could cherry pick this one, could be good.

**Comment by sophistifunk** [comment]
I'll sort one out.

**Comment by sophistifunk** [comment]
Wait, that feature isn't in 1.3 at all (ie, it doesn't have the buggy version). Do you want me to hotfix the whole thing or leave it for 1.4?

**Comment by michaelneale** [comment]
@sophistifunk oh it isn't? I could have sworn that made it in before last week wednesday. If it is not there... no only needs to be fixed on master.

**Comment by vivek** [comment]
@michaelneale @sophistifunk right, test badge is not on 1.3 so lets leave it only on master for 1.4.

**Pull request merged**
