### PR TITLE
JENKINS-36976# stop API with blocking call feature

### PR DESCRIPTION
**Pull request by vivek**
# Description

See https://issues.jenkins-ci.org/browse/JENKINS-36976

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.
Not sure if it applies to API only changes but anyways, provide link to how to run test harness. 

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
@cliffmeyers can you please review this one? It will effect tickets assigned to you.

**Comment by imeredith** [comment]
@vivek This PR only covers the blocking feature, it does not have a hard stop as far as I can see?

**Comment by vivek** [comment]
@imeredith yes and no. There is no reliable way to generically provide hard kill for all kind of Runs. Workflow run does better job where it does some cleanup  after executor is taken offline.  Basically as far as I understand there is no way to hard kill that takes executor offline so as part of blocking call we interrupt the running build and wait for executor to go offline and in some cases like workflow run there may be extra cleanup.

**Comment by cliffmeyers** [comment]
REST API looks good to me. Would probably make sense for @imeredith or @michaelneale to weigh in as to whether the server code should get a bee. I don't have enough depth on the Java side to critique it.

**Comment by michaelneale** [comment]
code looks good to me. It is clear that stopping is a "fire and pray" sort of thing, so we can only do what we can only do, but as long as the UX "feels right" (ie we acknowledged the user has requested it). 

There is no "stopping state" for a run unfortunately, so it is a bit fiddly, but @cliffmeyers seems happy with the api, so 🐝

**Comment by michaelneale** [comment]
FYI a change like this should have the ATH run against it...

**Comment by vivek** [comment]
@michaelneale sorry about that, for the next time, add how to run link to the reviewer's template, there isn't any, no idea how its run.

**Pull request merged**
