### PR TITLE
JENKINS-38136# capability map API changed to POST

### PR DESCRIPTION
**Pull request by vivek**
# Description

See https://issues.jenkins-ci.org/browse/JENKINS-38136

To test classes map functionality:

`curl -v -X POST  http://localhost:8080/jenkins/blue/rest/classes/ -d '{"q":["io.jenkins.blueocean.service.embedded.rest.PipelineImpl","io.jenkins.blueocean.service.embedded.rest.MultiBranchPipelineImpl"]`

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

Can't run ATH it started failing with "Error: Signature author is required." If reviewer can run, will be great.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees 

- Also pulls in well known capabilities in to a class as constant
- Fixes typo in PullRequest capability

### CODE REVIEW

**Comment by vivek** [comment]
@cliffmeyers Over to you:)

**Comment by cliffmeyers** [comment]
LGTM to using:

`curl -v -u cmeyers:test123 -XPOST -H "Content-Type:application/json" -d '{"q":["io.jenkins.blueocean.rest.impl.pipeline.PipelineImpl","io.jenkins.blueocean.rest.impl.pipeline.MultiBranchPipelineImpl"]}' http://localhost:8080/jenkins/blue/rest/classes/`

**Comment by cliffmeyers** [comment]
@vivek If you have a chance over the next day or two could you fix the test failure in this branch? I have a few branches that have merged this in to get the API change but all of their builds are failing due to that test failure. Thanks :)

**Comment by imeredith** [comment]
:bee: LGTM

**Pull request merged**
