### PR TITLE
Trying newer versions of declarative and favorite

### PR DESCRIPTION
**Pull request by michaelneale**
# Description

Just bumping some versions to be newer to see if tests still pass

### CODE REVIEW

**Comment by michaelneale** [comment]
cc @vivek for the PCT

**Comment by michaelneale** [comment]
@vivek interesting failure - so it won't allow those versions without some others being juggled? (so juggling some more...)

**Comment by vivek** [comment]
@michaelneale we don't need to upgrade the declarative and workflow apis. The specific failing test PipelineMetadataServiceTest.declarativeAgents() was fixed in 1.3.1, see https://github.com/jenkinsci/blueocean-plugin/pull/1496.

**Comment by michaelneale** [comment]
@Vivek ok what about the autofav failure?

**Comment by vivek** [comment]
Looking at other test failure `io.jenkins.blueocean.autofavorite.FavoritingScmListenerTest.testAutoFavoriteForRegisteredUser` needs to be fixed in blueocean-autofavorite-plugin not blueocean. So I don't think we need this PR.

**Comment by michaelneale** [comment]
@vivek yes this PR was just to try things. Why would it suddenly start failing? (It has not changed for months). I bumped the fav plugin as I wondered if it was it.

**Comment by vivek** [comment]
@michaelneale declarativeAgent test failure was reported by @alvarolobato and fixed in blueocean 1.3.1. Other test failure got nothing to do with blueocean, its in different plugin. Perhaps the test is failing with upgrade of autofavorite plugin. I am checking whats going on in that plugin.

**Pull request closed without merging**
