### PR TITLE
[JENKINS-51057] Use see-gateway plugin 1.18

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: olivier lamy <olamy@apache.org>

# Description

See [JENKINS-51057](https://issues.jenkins-ci.org/browse/JENKINS-51057).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by halkeye** [comment]
Oh nice. Wonder if it'll help make the ath more stable

**Comment by olamy** [comment]
I don't really understand the build failure :( 
```
Docker version is older than 17.12, working directory will be /home/jenkins/slave/workspace/blueocean_PR-1987 not /home/jenkins/slave/workspace/blueocean_PR-1987/acceptance-tests

+ bash -x ./run.sh -v=2.138.4 --host=172.18.128.14 --no-selenium --settings=-s /home/jenkins/slave/workspace/blueocean_PR-1987/settings.xml

bash: ./run.sh: No such file or directory

script returned exit code 127
```

**Comment by halkeye** [comment]
I updated all the plugins on ci.blueocean last week, GCE agents broke, instead of fighting with it, I re-enabled the static agent, and did a test run (but now thinking about itI guess i never made it to the ATH).

I just fixed the GCE agents, and am now triggering a rebuild

**Comment by halkeye** [comment]
Cool it's on the ath. Good luck

**Comment by halkeye** [comment]
:( that's one of the flakey ones I keep trying to poke at

**Comment by olamy** [comment]
@halkeye yeah it's green build!  I need 1 approval so I can merge it ;)

**Pull request merged**
