### PR TITLE
Task/jenkins 39789 Github organizations API

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-39789](https://issues.jenkins-ci.org/browse/JENKINS-39789).

## Get Github Organizations

> As prerequisite GitHub personal access token must be set as Credential with id 'github' at authenticated user scope. you can do it manually or using GitHub access token validate API. See PR https://github.com/jenkinsci/blueocean-plugin/pull/672.

> Credential id corresponding to github personal access token must be sent either as query parameter 'credentialId' or as HTTP header X-CREDENTIAL-ID. If both are provided query parameter takes precedence. 

````
curl -v http://localhost:8080/jenkins/blue/rest/organizations/jenkins/scm/github/organizations/?credentialId=github

[ {
  "_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubOrganization",
  "_links" : {
    "repositories" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/jenkinsci/repositories/"
    },
    "self" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/jenkinsci/"
    }
  },
  "jenkinsOrganizationPipeline" : false,
  "name" : "jenkinsci"
}, {
  "_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubOrganization",
  "_links" : {
    "repositories" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/CloudBees-community/repositories/"
    },
    "self" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/CloudBees-community/"
    }
  },
  "jenkinsOrganizationPipeline" : false,
  "name" : "CloudBees-community"
}, {
  "_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubOrganization",
  "_links" : {
    "repositories" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/cloudbees/repositories/"
    },
    "self" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/cloudbees/"
    }
  },
  "jenkinsOrganizationPipeline" : false,
  "name" : "cloudbees"
}, {
  "_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubUserOrganization",
  "_links" : {
    "repositories" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/vivek/repositories/"
    },
    "self" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/vivek/"
    }
  },
  "jenkinsOrganizationPipeline" : false,
  "name" : "vivek"
}, {
  "_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubOrganization",
  "_links" : {
    "repositories" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/stapler/repositories/"
    },
    "self" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/stapler/"
    }
  },
  "jenkinsOrganizationPipeline" : false,
  "name" : "stapler"
}, {
  "_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubOrganization",
  "_links" : {
    "repositories" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/jruby/repositories/"
    },
    "self" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/jruby/"
    }
  },
  "jenkinsOrganizationPipeline" : false,
  "name" : "jruby"
} ]
````

### Get SCM repositories in an organization

````
curl -v -u xxx:yyy curl -v -u xxx:yyy http://localhost:8080/jenkins/blue/rest/organizations/jenkins/scm/github/organizations/CloudBees-community/repositories/?credentialId=github&pageSize=10&pageNumber=3
{
  "_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubRespositoryContainer",
  "_links" : {
    "self" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/CloudBees-community/repositories/"
    }
  },
  "repositories" : {
    "_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubRepositories",
    "_links" : {
      "self" : {
        "_class" : "io.jenkins.blueocean.rest.hal.Link",
        "href" : "/organizations/jenkins/scm/github/organizations/CloudBees-community/repositories/"
      }
    },
    "items" : [ {
      "_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubRepository",
      "_links" : {
        "self" : {
          "_class" : "io.jenkins.blueocean.rest.hal.Link",
          "href" : "/organizations/jenkins/scm/github/organizations/CloudBees-community/repositories/bees-cli-router-plugin/"
        }
      },
      "defaultBranch" : "master",
      "description" : "CloudBees SDK \"router:*\" plugin",
      "name" : "bees-cli-router-plugin",
      "permissions" : {
        "admin" : false,
        "push" : false,
        "pull" : true
      },
      ...],
    "lastPage" : 5,
    "nextPage" : 4,
    "pageSize" : 10
  }
}      
````

#### Pagination for GitHub repositories

Repositories response includes nextPage, lastPage and pageSize. nextPage or lastPage might be null if there is no more pages available.

> use pageSize and pageNumber query parameter to get number of items in a page and which page number is needed. Default value of pageNumber is 1 and default and max size is 100. 

### Get SCM repository in an organization

````
curl -v -u xxx:yyy http://localhost:8080/jenkins/blue/rest/organizations/jenkins/scm/github/organizations/CloudBees-community/repositories/game-of-life/?credentialId=github

{
  "_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubRepository",
  "_links" : {
    "self" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/CloudBees-community/repositories/game-of-life/?credentialId=github"
    }
  },
  "defaultBranch" : "master",
  "description" : "Demo application for the 'Jenkins: The Definitive Guide' book",
  "name" : "game-of-life",
  "permissions" : {
    "admin" : false,
    "push" : false,
    "pull" : true
  },
  "private" : false,
  "fullName" : "CloudBees-community/game-of-life"
}
````

# Tasks
- [x] Repository API in an organization (https://issues.jenkins-ci.org/browse/JENKINS-39788)

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
Test is written up and locally tested but disabled as I need to figure a GitHub test account
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by vivek** [comment]
@michaelneale @cliffmeyers Implemented repositories API (https://issues.jenkins-ci.org/browse/JENKINS-39788) as part of this PR. Ready for your review.

**Comment by michaelneale** [comment]
Nice ! and tests (code looks good)

Nit: if you forget -u in curl, it says credentialId is wrong, which is not the right message. 

Also for second and 3rd api examples above (which are not correct URIs BTW) setting a query param for credential doesn't seem to work. 

`curl -v -H "X-CREDENTIAL-ID:github" -u admin:admin http://localhost:8080/jenkins/blue/rest/organizations/jenkins/scm/github/orgnizations/?Cloudbees-Community/ | jsonpp` does - however

**Comment by vivek** [comment]
> Nit: if you forget -u in curl, it says credentialId is wrong, which is not the right message.

Improved error message. Since it requires authenticated user, on detecting anonymous it will report 401.

> Took me a while to test as the examples weren't really copy and paste correct.

Docs fixed (I think:)

> needs documented in README.md.
All relevant docs added there.

**Comment by michaelneale** [comment]
ok :bee: from me - I think @cliffmeyers wanted to have a final say.

**Comment by cliffmeyers** [comment]
@vivek I tested the `/organizations` API and it returns something slightly different from what I was expecting based on past conversations:
- For my github user, I see `cloudbees` and `jenkinsci` orgs but no org for my own user account `cliffmeyers`.
- Also, we had some discussion that this would return a unified view of orgs in github as well as Github org folders already in Jenkins. I had created an org folder tied to the `cliffmeyers` organization but did not see this data. When I deleted that org folder I did not see any change to the data returned either.

**Comment by vivek** [comment]
> For my github user, I see cloudbees and jenkinsci orgs but no org for my own user account cliffmeyers.

I didn't realize that but it seems, GitHub organization API doesn't list user's organization. I guess its implicit - that is every user is an org? Not sure there is much we can do about it.

> Also, we had some discussion that this would return a unified view of orgs in github as well as Github org folders already in Jenkins. I had created an org folder tied to the cliffmeyers organization but did not see this data. When I deleted that org folder I did not see any change to the data returned either; I was thinking maybe the Github org was being filtered out based on the presence of Github org folder in Jenkins but that doesn't appear to be the case.

I remember this discussion, probably I forgot details on this. Thinking now about it not sure if its good idea from API perspective, GitHub orgs api lists the orgs that are present in GitHub. This would require merging of jenkins orgs with GitHub orgs. I would rather have UI manages such merging on its own. At any give time it has list of user's pipeline, its simply matter of filtering based on types of pipeline (org ones). Guess we need some discussion on this with use case that absolutely needs such API.

**Comment by cliffmeyers** [comment]
@vivek I am not opposed to using a separate API to fetch the Github org folders. Some questions around that approach:
- Do you think the existing search API could be used to fetch the org folders? I am not sure if there is a particular type I could use to filter the search, and how we'd best avoid hard-coding a class name into the UI.
- I am not sure how to best perform the match between the two data sets. Ideally the `GithubOrganization` would contain property which is the URL to the Github org. And we'd need the same URL exposed on the Jenkins Github org folder option.

With regard to the user not be returned as an org, perhaps @i386 and @michaelneale can provide some input?

**Comment by michaelneale** [comment]
@cliffmeyers @vivek:

* The user "org" should be returned in addition to the orgs the user has access to. From most points of view it is just an org, I think it makes sense to combine it in this api. 
* For the org folders that exist in Jenkins, ideally they would be taken into account, so when the list of orgs, or repos, re returned in this api, there is some flag to indicate it already exists in Jenkins (so the UI knows). 
   - If this is not done, then this api will need to change to include a unique id for an org and repos, and an ADDITIONAL api needs to exist to return just org folders in Jenkins (at the top level) of the github type. Using this unique id the GUI can then flag things as pre-existing or not (listing things via the flattened search won't work really, unless it is enhanced to do the above, like cliff suggests). 

I think it probably makes sense for the api to returned a flag saying that it already exists in jenkins.

**Comment by vivek** [comment]
> The user "org" should be returned in addition to the orgs the user has access to. From most points of view it is just an org, I think it makes sense to combine it in this api, odd that github does not.

Yeah GitHub doesn't treat user's login as an org from org API perspective. This complicates slightly implementation where for user login (as org) needs different treatment to get repos. I will get it implemented.

> For the org folders that exist in Jenkins, ideally they would be taken into account, so when the list of orgs, or repos, re returned in this api, there is some flag to indicate it already exists in Jenkins (so the UI knows).

This is certainly doable and easier than other option if this serves purpose. So to be clear lets say I have an org 'jenkinsci' and if there is one or more jenkins org folder found to exist then will have a field in json response, lets call it 'existsAsJenkinsOrg', as true. Sounds ok @cliffmeyers @michaelneale?

**Comment by vivek** [comment]
@cliffmeyers @michaelneale both have been implemented.

- User's login is included in the list of GitHub orgs
- Each GitHub org is flagged if there is existing Jenkins org pipeline. This element is `jenkinsOrganizationPipeline with value true or false`
- README examples have been updated accordingly.

**Comment by i386** [comment]
@vivek instead of the Boolean flag could we return a link to that org?

**Comment by vivek** [comment]
@i386 if link is needed then it would be an array as there could be multiple Jenkins orgs with same github org in them. Also classic allows to have multiple GitHub orgs in a single Jenkins org folder. Anyways either array of Jenkins org name or links can be returned. Let me know what would work best.

**Comment by vivek** [comment]
@cliffmeyers what would you prefer:

1. Boolean to tell there are jenkins orgs that has this repo (current implementation)?
2. List of Jenkins org names, e.g. ["cloudbeers", "jenkinsci"]  that has this GitHub org?
3. List of Links  e.g. ["/organizations/jenkins/pipelines/cloudbeers/", "/organizations/jenkins/pipelines/jenkinsci/"] of Jenkins org names that has this GitHub org?

**Comment by cliffmeyers** [comment]
@vivek for my needs, a boolean is sufficient... unless @i386 is driving at something I'm missing with his comment. We could always adjust the API later if we identify a gap.

**Comment by cliffmeyers** [comment]
🐝  from me unless @i386 objects!

**Comment by vivek** [comment]
Ok, will wait for @i386's comment:)

**Comment by i386** [comment]
Go for it

**Pull request merged**
