### PR TITLE
Feature/jenkins 37877 pipeline permissions

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description

See [JENKINS-37877](https://issues.jenkins-ci.org/browse/JENKINS-37877).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
   - Navigate to Pipeline Activity tab (for non-multibranch), Run Details (all types) and Branches / Pull Requests tabs (for multi-branch) and verify the Start, Stop and Replay buttons are shown and hidden as they should based on permissions. Trickiest ones to test will be "Stop" since you need to kick off the job as another user and then navigate there as the restricted use (unless you can configure a user *with start* but *without stop*)
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
I went to the activity tab for a non multibranch pipeline as anon read only user, and can still see the run button: 

screen shot 2016-09-20 at 11 42 14 am

so this seems wrong? am I meant to test with other permission permutations?

**Comment by cliffmeyers** [comment]
@michaelneale yes, sorry, something must be awry. Will jump on this first thing tomorrow.

**Comment by cliffmeyers** [comment]
@michaelneale sorry if you burned time on this yesterday: I had forgot to publish a new version of core-js and wire it up to the other packages. Also fixed an issue on Branches and Tabs. And noticed there was an opportunity to kill some dead CSS and assets.

One more note: permissions are not applied in the Favorites yet because that is still using its own version of Start / Stop / Rerun code. However #466 is complete, Favorites will get this feature "for free" since it will be using the button code from core-js.

**Comment by michaelneale** [comment]
look good to me. Kudos on tests 

:bee: - not closely reviewed the code though  @kzantow @scherler want to weigh in or not?

**Comment by michaelneale** [comment]
the big shrinkwrap changes - will they always be a pain? (not sure what it is about)

**Comment by cliffmeyers** [comment]
@michaelneale not sure why it's suppressing the shrinkwrap diff: it's just a very small change to the blueocean-core-js dep.

**Comment by tfennelly** [comment]
🐝 LGTM

On small comment might be to encapsulate the code for deciding whether or not to show the buttons into functions e.g. `showRun` and `showStop`, with some comments etc. It composes the code a bit better I think. Just a small NIT though. Nice job !!!

**Comment by cliffmeyers** [comment]
@tfennelly I have another branch in progress now and will make that adjustment. I agree those expressions are a bit lengthy and would work well as methods.

**Pull request merged**
