### PR TITLE
JENKINS-41348# Create credential store in system store

### PR DESCRIPTION
**Pull request by vivek**
Also fixes:

- HTTP connection not closed
- GitHubEnterprise object id is incorrect

# Description

See [JENKINS-41348](https://issues.jenkins-ci.org/browse/JENKINS-41348).

@michaelneale @i386 @cliffmeyers it changes few things:

- Credential for GitHub access token is created in system store instead of user's store. This means credential is usable by other users on that jenkins instance, perhaps it can be restricted but I am not sure about it.
- CredentialId changes from 'github' to 'github-$userId' 

#### Create new credentialId from your GitHub access token

```
curl -v -u admin:admin -d '{"accessToken": "boo"}' -H "Content-Type:application/json" -XPUT http://localhost:8080/jenkins/blue/rest/organizations/jenkins/scm/github/validate 

```

Response:

```
{
  "credentialId" : "github-admin"
}
```

#### List organizations

```
curl -v http://localhost:8080/jenkins/blue/rest/organizations/jenkins/scm/github/organizations/?credentialId=github-admin
```

Response:

```
[ {
  "_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubOrganization",
  "_links" : {
    "repositories" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/jenkinsci/repositories/"
    },
    "self" : {
      "_class" : "io.jenkins.blueocean.rest.hal.Link",
      "href" : "/organizations/jenkins/scm/github/organizations/jenkinsci/"
    }
  },
  "jenkinsOrganizationPipeline" : false,
  "name" : "jenkinsci"
}]
```

#### Create new Pipeline 

```
curl -v -u admin:admin -H 'Content-Type: application/json' http://localhost:8080/jenkins/blue/rest/organizations/jenkins/pipelines/  -d 
'{
  "name" : "cloudbeers", 
  "$class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubPipelineCreateRequest",
  "scmConfig" : {
    "uri":"https://api.github.com", 
    "credentialId": "github-admin",
    "config":{
        "orgName": "cloudbeers", //optional, if absent name element is used as orgName
        "repos" : [ "PR-demo" ] //optional, if not provided all repos in this org are tried
    }
  }
}'
```

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by cliffmeyers** [comment]
@vivek how will this change the behavior of the `/scm/github` API? Will this only ever return the token tied the user?

**Comment by vivek** [comment]
@cliffmeyers there is no change in behavior, to you the only change in behavior would be that the credentialId will look bit different but I think you are not hardcoding it in your code anyways so should have no impact on you.

**Comment by vivek** [comment]
@cliffmeyers PTAL and give it a try.

**Comment by michaelneale** [comment]
@vivek this is branched off a really old version of master.. not sure how easy it is to review. 

I can see this created a global git ssh key for system - but the id doesn't contain the user name, was the intention to have that? (the name does): 

screen shot 2017-01-25 at 7 13 05 pm

**Comment by vivek** [comment]
@michaelneale You are testing wrong thing, auto-name selection applies only for github creation flow. For git API is not automatically creating credential. See the instruction on how to test under description. 

BTW its off Jan 19 master, I can merge the latest.

**Comment by cliffmeyers** [comment]
@vivek looks good to me, although I hit Github rate limiting again before I could finish testing. Including the `credentialId` property worked just fine. I did not get to test it with ommitting it from the request but if you are confident then we should go ahead and merge.

When omitting `credentialId` from request...
```
{
    "name": "cliffmeyers",
    "$class": "io.jenkins.blueocean.blueocean_github_pipeline.GithubPipelineCreateRequest",
    "scmConfig": {
        "uri": "https://api.github.com",
        "config": {
            "orgName": "cliffmeyers",
            "repos": []
        }
    }
}
```

Response looks good...
```
{
    "_class": "io.jenkins.blueocean.blueocean_github_pipeline.GithubOrganizationFolder",
    "_links": {
        "pipelines": {
            "_class": "io.jenkins.blueocean.rest.hal.Link",
            "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/pipelines/"
        },
        "activities": {
            "_class": "io.jenkins.blueocean.rest.hal.Link",
            "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/activities/"
        },
        "self": {
            "_class": "io.jenkins.blueocean.rest.hal.Link",
            "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/"
        },
        "actions": {
            "_class": "io.jenkins.blueocean.rest.hal.Link",
            "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/actions/"
        },
        "runs": {
            "_class": "io.jenkins.blueocean.rest.hal.Link",
            "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/"
        },
        "queue": {
            "_class": "io.jenkins.blueocean.rest.hal.Link",
            "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/queue/"
        }
    },
    "actions": [],
    "displayName": "cliffmeyers",
    "fullDisplayName": "cliffmeyers",
    "fullName": "cliffmeyers",
    "name": "cliffmeyers",
    "organization": "jenkins",
    "parameters": null,
    "permissions": {
        "create": true,
        "read": true,
        "start": true,
        "stop": true
    },
    "numberOfFolders": 0,
    "numberOfPipelines": 0,
    "icon": "/jenkins/static/baf1834a/plugin/github-branch-source/images/32x32/github-scmnavigator.png",
    "latestRun": {
        "_class": "io.jenkins.blueocean.rest.impl.pipeline.OrganizationFolderRunImpl",
        "_links": {
            "nodes": {
                "_class": "io.jenkins.blueocean.rest.hal.Link",
                "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/1/nodes/"
            },
            "log": {
                "_class": "io.jenkins.blueocean.rest.hal.Link",
                "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/1/log/"
            },
            "self": {
                "_class": "io.jenkins.blueocean.rest.hal.Link",
                "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/1/"
            },
            "actions": {
                "_class": "io.jenkins.blueocean.rest.hal.Link",
                "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/1/actions/"
            },
            "steps": {
                "_class": "io.jenkins.blueocean.rest.hal.Link",
                "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/1/steps/"
            },
            "artifacts": {
                "_class": "io.jenkins.blueocean.rest.hal.Link",
                "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/1/artifacts/"
            }
        },
        "actions": null,
        "artifactsZipFile": null,
        "changeSet": null,
        "durationInMillis": -1,
        "enQueueTime": "1969-12-31T19:00:00.000-0500",
        "endTime": null,
        "estimatedDurationInMillis": -1,
        "id": "1",
        "organization": "jenkins",
        "pipeline": "cliffmeyers",
        "result": "UNKNOWN",
        "runSummary": "UNKNOWN:FINISHED",
        "startTime": "1969-12-31T19:00:00.000-0500",
        "state": "FINISHED",
        "type": "com.cloudbees.hudson.plugins.folder.computed.FolderComputation"
    }
}
```

**Comment by vivek** [comment]
@cliffmeyers you would encounter rate limit less often if you are using credentialId. If you do not provide credentialId then its anonymous access and rate limit is stringent here. Did you try giving credentialId and did it work? I think it did, just confirming as that was the original bug:)

**Comment by cliffmeyers** [comment]
@vivek good call. I just retested with `credentialId` - the create succeeds. However the organization indexing still fails with a rate limit.

Request:
```
{
    "credentialId": "github-cmeyers",
    "name": "cliffmeyers",
    "$class": "io.jenkins.blueocean.blueocean_github_pipeline.GithubPipelineCreateRequest",
    "scmConfig": {
        "uri": "https://api.github.com",
        "config": {
            "orgName": "cliffmeyers",
            "repos": []
        }
    }
}
```

Response:
```
{
    "_class": "io.jenkins.blueocean.blueocean_github_pipeline.GithubOrganizationFolder",
    "_links": {
        "pipelines": {
            "_class": "io.jenkins.blueocean.rest.hal.Link",
            "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/pipelines/"
        },
        "activities": {
            "_class": "io.jenkins.blueocean.rest.hal.Link",
            "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/activities/"
        },
        "self": {
            "_class": "io.jenkins.blueocean.rest.hal.Link",
            "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/"
        },
        "actions": {
            "_class": "io.jenkins.blueocean.rest.hal.Link",
            "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/actions/"
        },
        "runs": {
            "_class": "io.jenkins.blueocean.rest.hal.Link",
            "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/"
        },
        "queue": {
            "_class": "io.jenkins.blueocean.rest.hal.Link",
            "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/queue/"
        }
    },
    "actions": [],
    "displayName": "cliffmeyers",
    "fullDisplayName": "cliffmeyers",
    "fullName": "cliffmeyers",
    "name": "cliffmeyers",
    "organization": "jenkins",
    "parameters": null,
    "permissions": {
        "create": true,
        "read": true,
        "start": true,
        "stop": true
    },
    "numberOfFolders": 0,
    "numberOfPipelines": 0,
    "icon": "/jenkins/static/2896d5fb/plugin/github-branch-source/images/32x32/github-scmnavigator.png",
    "latestRun": {
        "_class": "io.jenkins.blueocean.rest.impl.pipeline.OrganizationFolderRunImpl",
        "_links": {
            "nodes": {
                "_class": "io.jenkins.blueocean.rest.hal.Link",
                "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/1/nodes/"
            },
            "log": {
                "_class": "io.jenkins.blueocean.rest.hal.Link",
                "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/1/log/"
            },
            "self": {
                "_class": "io.jenkins.blueocean.rest.hal.Link",
                "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/1/"
            },
            "actions": {
                "_class": "io.jenkins.blueocean.rest.hal.Link",
                "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/1/actions/"
            },
            "steps": {
                "_class": "io.jenkins.blueocean.rest.hal.Link",
                "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/1/steps/"
            },
            "artifacts": {
                "_class": "io.jenkins.blueocean.rest.hal.Link",
                "href": "/blue/rest/organizations/jenkins/pipelines/cliffmeyers/runs/1/artifacts/"
            }
        },
        "actions": null,
        "artifactsZipFile": null,
        "changeSet": null,
        "durationInMillis": 0,
        "enQueueTime": "2017-01-25T14:39:42.954-0500",
        "endTime": null,
        "estimatedDurationInMillis": -1,
        "id": "1",
        "organization": "jenkins",
        "pipeline": "cliffmeyers",
        "result": "UNKNOWN",
        "runSummary": "UNKNOWN:RUNNING",
        "startTime": "2017-01-25T14:39:42.954-0500",
        "state": "RUNNING",
        "type": "com.cloudbees.hudson.plugins.folder.computed.FolderComputation"
    }
}
```

Here's the errors from that org folder's indexing logs
```
Started by user Cliff Meyers
[Wed Jan 25 14:39:42 EST 2017] Starting organization scan...
[Wed Jan 25 14:39:42 EST 2017] Updating actions...
Looking up details of cliffmeyers...
ERROR: [Wed Jan 25 14:39:43 EST 2017] Could not refresh actions for navigator org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator@2903ecb0
org.jenkinsci.plugins.github_branch_source.RateLimitExceededException: GitHub API rate limit exceeded
	at org.jenkinsci.plugins.github_branch_source.Connector$1.onError(Connector.java:259)
	at org.kohsuke.github.Requester.handleApiError(Requester.java:649)
	at org.kohsuke.github.Requester._to(Requester.java:284)
	at org.kohsuke.github.Requester.to(Requester.java:225)
	at org.kohsuke.github.GitHub.checkApiUrlValidity(GitHub.java:669)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator.retrieveActions(GitHubSCMNavigator.java:476)
	at jenkins.scm.api.SCMNavigator.fetchActions(SCMNavigator.java:315)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:371)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:187)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:139)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:814)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
[Wed Jan 25 14:39:43 EST 2017] Consulting GitHub Organization
ERROR: [Wed Jan 25 14:39:43 EST 2017] Could not fetch sources from navigator org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator@2903ecb0
org.jenkinsci.plugins.github_branch_source.RateLimitExceededException: GitHub API rate limit exceeded
	at org.jenkinsci.plugins.github_branch_source.Connector$1.onError(Connector.java:259)
	at org.kohsuke.github.Requester.handleApiError(Requester.java:649)
	at org.kohsuke.github.Requester._to(Requester.java:284)
	at org.kohsuke.github.Requester.to(Requester.java:225)
	at org.kohsuke.github.GitHub.checkApiUrlValidity(GitHub.java:669)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator.visitSources(GitHubSCMNavigator.java:265)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:420)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:187)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:139)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:814)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
[Wed Jan 25 14:39:43 EST 2017] Finished organization scan. Scan took 0.63 sec
FATAL: Failed to recompute children of cliffmeyers
org.jenkinsci.plugins.github_branch_source.RateLimitExceededException: GitHub API rate limit exceeded
	at org.jenkinsci.plugins.github_branch_source.Connector$1.onError(Connector.java:259)
	at org.kohsuke.github.Requester.handleApiError(Requester.java:649)
	at org.kohsuke.github.Requester._to(Requester.java:284)
	at org.kohsuke.github.Requester.to(Requester.java:225)
	at org.kohsuke.github.GitHub.checkApiUrlValidity(GitHub.java:669)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator.visitSources(GitHubSCMNavigator.java:265)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:420)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:187)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:139)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:814)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Finished: FAILURE
```

**Comment by cliffmeyers** [comment]
Per discussion w/ @vivek I don't think this PR is intended to solve that rate limit issue. So PR looks good to me 🐝

**Comment by stephenc** [comment]
I am concerned with the storage of user credentials in the system store. This seems like a bad plan to me. @vivek we should discuss before you go too far down this road

**Comment by stephenc** [comment]
:bug: until @vivek discusses credential usage with me (no issues with the code, issues with the security model it promotes)

**Comment by i386** [comment]
@stephenc we all agree this isn't the best but it's a fall back. you're going to like his other PR.

**Comment by vivek** [comment]
@stephenc yeah till scm apis get fixed to take user scoped and user store credentials this is our fall back plan. I have some idea and should have a PR soon.

**Comment by michaelneale** [comment]
FWIW this is how everyone I have seen use credentials today for github branch source plugin(s) - slap a user access token in the system store with some name.

**Comment by vivek** [comment]
Closing this with https://github.com/jenkinsci/blueocean-plugin/pull/768.

**Pull request closed without merging**
