### PR TITLE
Revert "Jenkins 40299 fix remaining scmapi integration issues (#715)"

### PR DESCRIPTION
**Pull request by vivek**
This reverts commit 21286af0439053281830d6d6b98699f622ef1644.

# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
@michaelneale this is what is needed to get back into a releasable state.

**Comment by michaelneale** [comment]
@i386 we wont' be able to test this on dogfood as it has been upgraded to the new SCM api though. 

Also ATH will need to be changed back to this.

**Comment by vivek** [comment]
@michaelneale here is ATH PR https://github.com/jenkinsci/blueocean-acceptance-test/pull/102.

**Comment by michaelneale** [comment]
trying with corresponding ATH branch right now..

**Comment by i386** [comment]
@michaelneale I expect we may have to fiddle with dogfood a bit to get it back to a good state.

**Comment by michaelneale** [comment]
@i386 yeah for the /blue on dogfood to work we will likely haev to restore from a backup.

**Comment by michaelneale** [comment]
:bee: if/when is needed.

**Pull request merged**
