### PR TITLE
JENKINS-44964 sometimes replaceAction will fail because an action in …

### PR DESCRIPTION
**Pull request by i386**
…the list is null

This shouldn't happen but it does :/

# Description

See [JENKINS-44964](https://issues.jenkins-ci.org/browse/JENKINS-44964).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
update this to master to clear up that ATH test failure

**Comment by i386** [comment]
Updated

**Comment by michaelneale** [comment]
once green merge it

**Comment by michaelneale** [comment]
:bee:

**Comment by i386** [comment]
@vivek no duplicate links btw

**Pull request merged**
