### PR TITLE
Task/jenkins 38598 sse service remove handler

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- Needed a way for clients to remove their handler from the SSEService. This is important in Creation since the interest in SSE's is short-lived and needs to be cleaned up after leaving the flow.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by cliffmeyers** [comment]
cc @imeredith

**Comment by michaelneale** [comment]
:bee: passes sniff test - so as long as ATH happy - go for it.

**Comment by tfennelly** [comment]
All these SSE wrapper libs have my head in a bit of a spin ... `SSEService`, `SseBus` 😢

**Comment by michaelneale** [comment]
@tfennelly that SSEService wasn't introduced as part of this, and this actually brings test coverage to it.

**Comment by tfennelly** [comment]
@michaelneale yeah I get that ... it was just a general comment 😄

**Pull request merged**
