### PR TITLE
upgrade Jenkins 2.10

### PR DESCRIPTION
**Pull request by i386**
Related to issue # . 

Summary of this pull request: 
.
.
.

@reviewbybees

### CODE REVIEW

**Comment by blueoceandeploy** [comment]
Can one of the admins verify this patch?

**Comment by i386** [comment]
deploy on sandbox

**Comment by oleg-nenashev** [comment]
Seems the description is broken. I would not recommend updating to 2.10 unless there are required fixes. 2.7 is the better baseline since 2.7.1 is going to be the next LTS

**Comment by michaelneale** [comment]
yeah don't use a very experimental branch to test the PR builder

**Pull request closed without merging**
