### PR TITLE
FIX errors being swallowed

### PR DESCRIPTION
**Pull request by kzantow**
Try-catch-fail.

@reviewbybees esp. @scherler

### CODE REVIEW

**Comment by scherler** [comment]
As said in our face to face communication I would prefer an error message approach, but the changes fixes a really ugly bug so +1 :bee:

**Comment by i386** [comment]
@scherler @kzantow is there a ticket tracking adding the error messages as discussed?

**Comment by tfennelly** [comment]
🐝

**Comment by kzantow** [comment]
@scherler another tweak here, could you re-review and merge? I seem to have no merge privileges ...

**Pull request merged**
