### PR TITLE
Task/jenkins 42119 creation design tweaks

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- See [JENKINS-42119](https://issues.jenkins-ci.org/browse/JENKINS-42119).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
Screenies. Perhaps @brody can have a look.

creation-1-initial

creation-2-github

**Comment by i386** [comment]
Oh that is very nice :)

**Comment by i386** [comment]
@cliffmeyers  I had just tried this out - it's beautiful.

One thing I noticed is that the branch sources buttons never get displayed. Should that be done along side [JENKINS-42206](https://issues.jenkins-ci.org/browse/JENKINS-42206)? I believe this is assigned to @imeredith 

-blueocean-2017-02-28-18-11-18

**Comment by michaelneale** [comment]
:bee: and ATH happy - nice one @cliffmeyers !

**Comment by kzantow** [comment]
why would you disable the buttons? how could you undo clicking the wrong thing then?

**Comment by cliffmeyers** [comment]
Right, @i386 I think @kzantow makes a valid point. If those are disabled the whole time, then there's no easy way to start a new flow without refreshing this screen or navigating away and back.

**Comment by kzantow** [comment]
makes sense to highlight one as active, but i'd avoid disabling them.

**Comment by i386** [comment]
If we are not disabling the first one in this scenario then we shouldn't be disabling any steps.

**Comment by kzantow** [comment]
agree... unless there's a way to go back to the previous step, i'd avoid disabling them at all; if there's a way to go back to the prior step, then disabling them is just fine

**Comment by kzantow** [comment]
the source and single/multiple repository steps seem to be missing selected states, though

**Comment by i386** [comment]
@brody can you weigh in?

**Comment by brody** [comment]
@cliffmeyers Correct, previously selected buttons shouldn't be disabled, so the user can change their mind and change any selection in the flow... which obviously would have knock on affects unselecting any of the below selections.

**Comment by cliffmeyers** [comment]
@i386 @brody @kzantow to clarify, here is how it works today:

1. User can move through the steps in flow. If the user picks the wrong org or the wrong auto-discover option, they can obviously go back up to an early step and change their mind. The UI will re-render the next step appropriately.
2. Once the user presses "Create Pipeline", the buttons in the preceding steps are disabled. This is because while the system is working, listening for events, etc we probably don't want the user fiddling with selections. I mean we could, just realize it will open a whole new class of bugs to defend against.
3. There is a bug and oversight that when "Create Pipeline" is clicked, the Git and Github buttons at the top aren't disabled. This can be fixed, it will just take a modest effort - only because how those buttons are handled via extension point mechanism are subtly different than how the steps themselves are.
4. We could further enhance the UI so that when the creation process "completes" that the buttons at the top become enabled. If the user wants to do a new creation flow for Git or Github they just need to click one of those buttons and the old steps get wiped. (To clarify further, "completes" means that creation finishes with success, with an error, or after the 60s timeout currently in place if the right events aren't received).

**Comment by kzantow** [comment]
Ah, right... after clicking create. Yeah, makes sense how it is now and to disable the top selections after clicking create, as you said.

**Comment by brody** [comment]
1. 👍
2. Sweet. Disabling the entire form when "Create Pipeline" is clicked is perfect.
3. 👍
4. Once the creation process successfully completes, the intended action is to launch the pipeline. Reenabling the buttons on failure, while showing the error, would be good.

**Comment by cliffmeyers** [comment]
@michaelneale per your question in Gitter, I think this PR satisfies the work items in the ticket. If we want to fiddle with button enabling or disabling, I'm happy to cut another ticket and handle in another PR.

**Comment by michaelneale** [comment]
ok great @cliffmeyers - Ivan made a small change to creation so may want to update to master and be happy this is still ok (should be) - but LGTM

**Comment by cliffmeyers** [comment]
Created https://issues.jenkins-ci.org/browse/JENKINS-42507 to track the disabling issue.

**Pull request merged**
