### PR TITLE
JENKINS-36542# API to map of class details for multiple classes

### PR DESCRIPTION
**Pull request by vivek**
**Decription**

**Submitter checklist**
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

Already covered by test. But if you want to do follow this: https://github.com/jenkinsci/blueocean-plugin/blob/task/JENKINS-36542/blueocean-rest/README.md#get-detailed-map-of-all-given-classes

**Reviewer checklist**
- [x] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explaination given

@reviewbybees

### CODE REVIEW

**Comment by imeredith** [comment]
@vivek why is there all that commented out code?

**Comment by vivek** [comment]
@imeredith oops, forgot to delete. Let me do that.

**Comment by vivek** [comment]
@imeredith Removed the dead code, also handled case when param is null and added test for that case.

**Comment by i386** [comment]
@imeredith ping

**Comment by imeredith** [comment]
:bee:

**Comment by vivek** [comment]
@imeredith @cliffmeyers @michaelneale need someone to run and verify regressions etc. Reviewer Run checkbox is not checked yet.

**Comment by cliffmeyers** [comment]
Tested locally, data looks good! 🐝

**Pull request merged**
