### PR TITLE
JENKINS-35884# Capability annotation support

### PR DESCRIPTION
**Pull request by vivek**
Adds supports for [Capability annotation](https://github.com/jenkinsci/capability-annotation) with /rest/classes API. 

@reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
@vivek is there a plan to add the annotation to known parts of the codebase?

**Comment by vivek** [comment]
@i386 Yes, once this is in, good time to come up with reasonable capability and it to our code base.

**Comment by imeredith** [comment]
:bee:

**Comment by i386** [comment]
Can that be done as part of JENKINS-35884?

**Comment by vivek** [comment]
@i386 We could do that but putting annotation on API model resources is orthogonal, this is core functionality. I think we should merge this one and annotating our model classes can be done in another ticket. I will open a ticket for that.

**Comment by i386** [comment]
Sounds good

**Pull request merged**
