### PR TITLE
[JENKINS-41205] Request 10,000 nodes at a time

### PR DESCRIPTION
**Pull request by benlangfeld**
This is probably enough for most people’s pipelines. Alternative approach to https://github.com/jenkinsci/blueocean-plugin/pull/1530.

# Description

See [JENKINS-41205](https://issues.jenkins-ci.org/browse/JENKINS-41205).

There's no tests to modify/augment.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by benlangfeld** [comment]
Test failures are unrelated.

**Comment by michaelneale** [comment]
running tests again... I think this LGTM

@vivek ok with you?

**Comment by michaelneale** [comment]
@vivek if you think this is ok - please do merge it

thanks @benlangfeld

**Comment by vivek** [comment]
LGTM🐝

**Pull request merged**
