### PR TITLE
Minor fixes to Docker file and Jenkins file

### PR DESCRIPTION
**Pull request by halkeye**
# Description

* Add UID and GID support so it can be built on any jenkins install. Jenkins doesn't always run as user 1000
* Add latest npm so it never fails on fsevents (optional dep)
* Add phantomjs to speed up runtime

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
@halkeye nice - so where else are you planning to use this .build file? 
With "mvn install" and js-builder, it will pull its own version of npm anyway - but I assume you are doing something else with this image?

**Comment by michaelneale** [comment]
I think the way MBP works, I will have to put this in a branch so it "trusts" the Jenkinsfile change (I think in forks they are not used, for security reasons). or @halkeye I can give you repo access so you can work on a branch if you like (I suspect you will do PRs from time to time anyway).

**Comment by halkeye** [comment]
wasn't planning on using it anywhere else. Both blueocean-plugin and ATH use the exact same dockerfile (but named differently), so I have another PR coming for that too.

mvn install pulls npm? I never saw that behavior but i can easily be mistaken.

**Comment by michaelneale** [comment]
I checked this out on a branch of mine and LGTM - not sure if the phantomjs stuff is needed though - as it would be pull as part of the normal build anyway.

**Comment by michaelneale** [comment]
Doesn't seem faster, yet. Probably as it is building the docker image each time until warm. I have not used the build params to docker build, so not entirely confident how they affect build behavior.

**Comment by michaelneale** [comment]
thanks for this @halkeye !

**Pull request merged**
