### PR TITLE
[FIX JENKINS-36660] hooks for AT

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-36660](https://issues.jenkins-ci.org/browse/JENKINS-36660). 

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
I guess this is :bee: (hard to review here) - obviously needs the released versions of the dependencies - this will help ATH run more reliably?

**Comment by kzantow** [comment]
Might as well wait until there's a published version for a change like this

**Comment by michaelneale** [comment]
ok

**Comment by scherler** [comment]
@michaelneale @kzantow the version

```
"@jenkins-cd/design-language": "0.0.71-thor2",
```
is published under my tag. Anyway we need the new hooks for the AT.

**Comment by scherler** [comment]
BLOCKED BY jenkinsci/jenkins-design-language#87
BLOCKS jenkinsci/blueocean-acceptance-test#26

**Comment by michaelneale** [comment]
@scherler you have bees on those dependent ones - so I think this can go ahead right @kzantow ?

**Pull request merged**
