### PR TITLE
JENKINS-43907 Git Creation produces error in console after successful…

### PR DESCRIPTION
**Pull request by i386**
… pipeline creation

# Description

This was missing the check to ignore events related to non-jobs entering and exiting the queue.
Open console and check this error does not appear when you create a pipeline.

See [JENKINS-43907](https://issues.jenkins-ci.org/browse/JENKINS-43907).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
will need to build and take a look at tests aren't covering - only need to test git?

**Comment by michaelneale** [comment]
It would be nice to have a branch name that can easily be spotted ..

**Comment by michaelneale** [comment]
code review please @sophistifunk @kzantow

**Comment by sophistifunk** [comment]
Code looks fine, assuming it works 😁 

🐝

**Comment by michaelneale** [comment]
I didn't get a chance to test this - did you try all the permutations with creating github pipelines etc? messing with events is always risky

**Comment by michaelneale** [comment]
this broke github creation (it does't get event to take it to activity screen). 

I don't think we have the ability to hand test all the permutations for changes here.

**Pull request merged**
