### PR TITLE
Update README.md w/ note about installation on macOS

### PR DESCRIPTION
**Pull request by heisian**
Installing the project requires usage of JDK 1.8.

# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by halkeye** [comment]
I'm so absolutely certain the build will fail, cause the build is finicky.like that. Gonna just merge

**Comment by heisian** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Blue Ocean Parent 1.18.0-SNAPSHOT:
[INFO]
[INFO] Blue Ocean Parent .................................. SUCCESS [  3.643 s]
[INFO] Jenkins Design Language ............................ SUCCESS [ 46.251 s]
[INFO] Blue Ocean Core JS ................................. SUCCESS [ 41.576 s]
[INFO] Common API for Blue Ocean .......................... SUCCESS [  7.479 s]
[INFO] REST API for Blue Ocean ............................ SUCCESS [ 10.490 s]
[INFO] i18n for Blue Ocean ................................ SUCCESS [  4.994 s]
[INFO] Web for Blue Ocean ................................. SUCCESS [ 45.199 s]
[INFO] Pipeline SCM API for Blue Ocean .................... SUCCESS [ 16.242 s]
[INFO] JWT for Blue Ocean ................................. SUCCESS [ 20.144 s]
[INFO] REST Implementation for Blue Ocean ................. SUCCESS [02:58 min]
[INFO] Pipeline implementation for Blue Ocean ............. SUCCESS [15:07 min]
[INFO] Events API for Blue Ocean .......................... SUCCESS [ 33.874 s]
[INFO] Dashboard for Blue Ocean ........................... SUCCESS [01:19 min]
[INFO] Personalization for Blue Ocean ..................... SUCCESS [ 43.928 s]
[INFO] Config API for Blue Ocean .......................... SUCCESS [ 32.753 s]
[INFO] GitHub Pipeline for Blue Ocean ..................... SUCCESS [03:29 min]
[INFO] Git Pipeline for Blue Ocean ........................ SUCCESS [01:49 min]
[INFO] Bitbucket Pipeline for Blue Ocean .................. SUCCESS [02:58 min]
[INFO] Blue Ocean Pipeline Editor ......................... SUCCESS [01:37 min]
[INFO] JIRA Integration for Blue Ocean .................... SUCCESS [ 44.894 s]
[INFO] Blue Ocean ......................................... SUCCESS [ 36.134 s]
[INFO] Blue Ocean Executor Info ........................... SUCCESS [ 34.175 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36:24 min
[INFO] Finished at: 2019-08-16T12:04:26-07:00
[INFO] ------------------------------------------------------------------------
heisian@local:~/Work/blueocean-plugin
 [heisian L|…12] ▷ 
```
🎊

**Comment by heisian** [comment]
I was a bit preemptive in the notes, I think (in case it failed and needed additional setup), but it worked!

**Comment by halkeye** [comment]
oh the ath is still running, that one runs on ci.blueocean.io, and its super flakey these days

**Comment by heisian** [comment]
@halkeye Separately, I'm interested in using the latest version of Jenkins for dev:
```diff
diff --git a/pom.xml b/pom.xml
index 8bdb0cb6d..dae3fb739 100644
--- a/pom.xml
+++ b/pom.xml
@@ -27,7 +27,7 @@
     <revision>1.18.0</revision>
     <changelist>-SNAPSHOT</changelist>
     <java.level>8</java.level>
-    <jenkins.version>2.138.4</jenkins.version> <!-- Should be kept in sync with the version resulting from Dockerfile FROM statement-->                                                                                                     
+    <jenkins.version>2.189</jenkins.version> <!-- Should be kept in sync with the version resulting from Dockerfile FROM statement-->                                                                                                       
     <javadoc.exec.goal>javadoc-no-fork</javadoc.exec.goal> <!-- stop initialize phase plugins executing twice -->
     <frontend-version>1.7.5</frontend-version>
     <node.version>10.13.0</node.version>
```
(`Dockerfile` was also updated with `jenkins:jenkins:2.189-alpine`

However…
<details><summary>(Click to expand error log)</summary>
<p>

```
$ mvn install

…

[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (display-info) @ blueocean-parent ---
[INFO] Adding ignore: module-info
[WARNING] Rule 5: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for commons-codec:commons-codec:1.10 paths to dependency are:
+-io.jenkins.blueocean:blueocean-parent:1.18.0-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-core:2.189
    +-commons-codec:commons-codec:1.10
and
+-io.jenkins.blueocean:blueocean-parent:1.18.0-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-core:2.189
    +-org.jenkins-ci.main:cli:2.189
      +-commons-codec:commons-codec:1.10 (managed) <-- commons-codec:commons-codec:1.12
and
+-io.jenkins.blueocean:blueocean-parent:1.18.0-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-core:2.189
    +-commons-httpclient:commons-httpclient:3.1-jenkins-1
      +-commons-codec:commons-codec:1.10 (managed) <-- commons-codec:commons-codec:1.8
and
+-io.jenkins.blueocean:blueocean-parent:1.18.0-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-core:2.189
    +-org.acegisecurity:acegi-security:1.0.7
      +-commons-codec:commons-codec:1.10 (managed) <-- commons-codec:commons-codec:1.3
and
+-io.jenkins.blueocean:blueocean-parent:1.18.0-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-core:2.189
    +-org.kohsuke.stapler:stapler-jrebel:1.257.2
      +-org.kohsuke.stapler:stapler:1.257.2
        +-commons-codec:commons-codec:1.10 (managed) <-- commons-codec:commons-codec:1.9
,
Require upper bound dependencies error for org.slf4j:jcl-over-slf4j:1.7.25 paths to dependency are:
+-io.jenkins.blueocean:blueocean-parent:1.18.0-SNAPSHOT
  +-org.slf4j:jcl-over-slf4j:1.7.25
and
+-io.jenkins.blueocean:blueocean-parent:1.18.0-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-core:2.189
    +-org.slf4j:jcl-over-slf4j:1.7.26
,
Require upper bound dependencies error for org.slf4j:log4j-over-slf4j:1.7.25 paths to dependency are:
+-io.jenkins.blueocean:blueocean-parent:1.18.0-SNAPSHOT
  +-org.slf4j:log4j-over-slf4j:1.7.25
and
+-io.jenkins.blueocean:blueocean-parent:1.18.0-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-core:2.189
    +-org.slf4j:log4j-over-slf4j:1.7.26
,
Require upper bound dependencies error for org.slf4j:slf4j-jdk14:1.7.25 paths to dependency are:
+-io.jenkins.blueocean:blueocean-parent:1.18.0-SNAPSHOT
  +-org.slf4j:slf4j-jdk14:1.7.25
and
+-io.jenkins.blueocean:blueocean-parent:1.18.0-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-war:2.189
    +-org.slf4j:slf4j-jdk14:1.7.26
]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Blue Ocean Parent 1.18.0-SNAPSHOT:
[INFO]
[INFO] Blue Ocean Parent .................................. FAILURE [  1.535 s]
[INFO] Jenkins Design Language ............................ SKIPPED
[INFO] Blue Ocean Core JS ................................. SKIPPED
[INFO] Common API for Blue Ocean .......................... SKIPPED
[INFO] REST API for Blue Ocean ............................ SKIPPED
[INFO] i18n for Blue Ocean ................................ SKIPPED
[INFO] Web for Blue Ocean ................................. SKIPPED
[INFO] Pipeline SCM API for Blue Ocean .................... SKIPPED
[INFO] JWT for Blue Ocean ................................. SKIPPED
[INFO] REST Implementation for Blue Ocean ................. SKIPPED
[INFO] Pipeline implementation for Blue Ocean ............. SKIPPED
[INFO] Events API for Blue Ocean .......................... SKIPPED
[INFO] Dashboard for Blue Ocean ........................... SKIPPED
[INFO] Personalization for Blue Ocean ..................... SKIPPED
[INFO] Config API for Blue Ocean .......................... SKIPPED
[INFO] GitHub Pipeline for Blue Ocean ..................... SKIPPED
[INFO] Git Pipeline for Blue Ocean ........................ SKIPPED
[INFO] Bitbucket Pipeline for Blue Ocean .................. SKIPPED
[INFO] Blue Ocean Pipeline Editor ......................... SKIPPED
[INFO] JIRA Integration for Blue Ocean .................... SKIPPED
[INFO] Blue Ocean ......................................... SKIPPED
[INFO] Blue Ocean Executor Info ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.522 s
[INFO] Finished at: 2019-08-19T07:57:31-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (display-info) on project blueocean-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
```
</p>
</details>

Is this worth doing / something other contributors do?

**Comment by halkeye** [comment]
That changes how the plugin is compiled, just for runtime you change the property

mvn hpi:run -Djenkins.verison=2.189 -f blueocean/pom.xml

**Comment by heisian** [comment]
ah cool thanks!

**Pull request merged**
