### PR TITLE
JENKINS-39860 Messages column in blue ocean should display if there a…

### PR DESCRIPTION
**Pull request by i386**
…re more commits

# Description

See [JENKINS-39860](https://issues.jenkins-ci.org/browse/JENKINS-39860).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

screencapture-localhost-8080-jenkins-blue-organizations-jenkins-atlas-demo-activity-1493369833447
screencapture-localhost-8080-jenkins-blue-organizations-jenkins-atlas-demo-branches-1493369839851

### CODE REVIEW

**Comment by i386** [comment]
@brody played with it more to get the text to align right 

atlas-demo 2017-04-29 17-20-56

**Comment by brody** [comment]
🐝 👏

**Comment by michaelneale** [comment]
I think this is breaking commitMessages test in ATH - I will have to take a look

**Comment by michaelneale** [comment]
have a passing ATH branch - but @i386 was going to make the class name consistnt for the non lozenge case as that was a small :ant:

**Comment by i386** [comment]
@michaelneale the cause variant now has the `RunMessageCell` on it

**Comment by sophistifunk** [comment]
🐝

**Pull request merged**
