### PR TITLE
[JENKINS-43507] Plugin version and simple API migration

### PR DESCRIPTION
**Pull request by stephenc**
- Only moving to equivalent methods, not taking advantage of the new API

# Description

See [JENKINS-43507](https://issues.jenkins-ci.org/browse/JENKINS-43507).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by stephenc** [comment]
Speculative PR to check test results

**Comment by michaelneale** [comment]
nice - passes. Can this one be closed now that https://github.com/jenkinsci/blueocean-plugin/pull/1188 exists with more betterer stuff?

**Comment by stephenc** [comment]
@michaelneale depends, if the org folder stuff is being migrated away from, this may be a better short-term... but it is more at risk of JENKINS-45058 as we are hijacking the regex, which can then be edited by the user whereas #1188 explicitly adds a trait to hold the management by BlueOcean

**Comment by michaelneale** [comment]
@stephenc def being migrated away from, but I don't see a downside in #1188 - but will let @vivek decide when he has time which one is most appropriate. The most important is the binary compat - which seems good, so we have some choice here. 

Thanks.

**Comment by michaelneale** [comment]
looking good thanks

**Comment by michaelneale** [comment]
I don't think we want to do it this way right @vivek ?

**Pull request closed without merging**
