### PR TITLE
Upgrade rollbar to 1.9.2

### PR DESCRIPTION
**Pull request by i386**
# Description

New version includes a small bug fix. Should be safe to roll in.

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).
# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.
# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
shrinkwrap error

**Comment by michaelneale** [comment]
can this be bumped?

**Comment by i386** [comment]
@michaelneale strange thing is that NPM says its there https://www.npmjs.com/package/rollbar-browser

**Comment by michaelneale** [comment]
@i386 if you click on the failure link, helpfully linked above ;) you will see the actual failure: 

```
+ node ./bin/checkshrinkwrap.js
3 	validating dependencies in /home/ubuntu/slave/workspace/ocean_upgrade-rollbar-1.9.2-GFRQEF6H4SE3TANSKZ2NH5LDUMZEMMDTSNPKPDD45HQDHMTYHMOQ/blueocean-dashboard
4 	validating dependencies in /home/ubuntu/slave/workspace/ocean_upgrade-rollbar-1.9.2-GFRQEF6H4SE3TANSKZ2NH5LDUMZEMMDTSNPKPDD45HQDHMTYHMOQ/blueocean-personalization
5 	validating dependencies in /home/ubuntu/slave/workspace/ocean_upgrade-rollbar-1.9.2-GFRQEF6H4SE3TANSKZ2NH5LDUMZEMMDTSNPKPDD45HQDHMTYHMOQ/blueocean-web
6 	validating dependencies in /home/ubuntu/slave/workspace/ocean_upgrade-rollbar-1.9.2-GFRQEF6H4SE3TANSKZ2NH5LDUMZEMMDTSNPKPDD45HQDHMTYHMOQ/blueocean-config
7 	rollbar-browser should be 1.9.2 but found 1.9.1
8 	You can use bin/cleanInstall to install the dominant dependency in various places.
```

lovingly highlighted by blue ocean. Shrinkwrap is not configured correctly (bin/cleaninstall looks like the script to help that).

**Comment by i386** [comment]
@cliffmeyers what magic do I need to run for shrink-wrap?

**Comment by cliffmeyers** [comment]
@i386 it's in the main README

**Pull request merged**
