### PR TITLE
Bump Jenkins minimum to 2.7.4

### PR DESCRIPTION
**Pull request by i386**
workflow-cps now depends on this version and prevent a successful install on 2.7.1

# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by vivek** [comment]
@i386 Latest workflow-cps ver 2.35 require 2.7.3, https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Groovy+Plugin.

**Comment by i386** [comment]
@vivek might as well go to 2.7.4 anyway - I think that was a security release?

**Comment by imeredith** [comment]
I have bumped version ath defaults to. Assuming job passes its :bee: from me

**Comment by i386** [comment]
Thanks Ivan!

**Pull request merged**
