### PR TITLE
Don't check read permission for sidebar link

### PR DESCRIPTION
**Pull request by hughsaunders**
Theres no need, because the user wouldn't be viewing
the build page if they didn't have the required read permission.

# Description

See [JENKINS-46540](https://issues.jenkins-ci.org/browse/JENKINS-46540).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by hughsaunders** [comment]
The three tests that failed, also failed in master eg pbuid 1898](https://ci.blueocean.io/blue/organizations/jenkins/blueocean/detail/master/1898/tests) and I don't think they are related to my PR.

**Comment by hughsaunders** [comment]
Hey @daniel-beck thanks for the approval, does this need another approval before merge?

**Comment by daniel-beck** [comment]
I do not maintain this. It only looks like I'm a maintainer with the green checkmark, but that's because I'm an org owner.

**Comment by hughsaunders** [comment]
@bitwiseman Hey, is there anything else I need to do to enable this to be merged?

**Comment by bitwiseman** [comment]
@hughsaunders 
Thanks!

**Pull request merged**
