### PR TITLE
Upgrade to autofavorite 1.1.0

### PR DESCRIPTION
**Pull request by i386**
# Description

This is to fix the PCT problem discovered by @michaelneale @vivek

### CODE REVIEW

**Comment by i386** [comment]
@vivek do you mind bumping this in RFC?

**Comment by michaelneale** [comment]
@i386 want to try this also against the release/1.3 branch to see if it is ok there too? (should be)

**Comment by michaelneale** [comment]
@i386 @vivek may need other dependencies bumped for this to be compatible. 
https://ci.blueocean.io/blue/organizations/jenkins/blueocean/detail/topic%2Fautofavorite-1.1.0/1/pipeline

**Comment by vivek** [comment]
@michaelneale @i386 there were upper bound errors. I fixed them by updating offending dependency versions to most appropriate ones.

**Comment by michaelneale** [comment]
nice - happy with this @vivek ?

**Comment by vivek** [comment]
Yeah LGTM.

**Pull request merged**
