### PR TITLE
Update es6-promise to 3.3.1

### PR DESCRIPTION
**Pull request by paladox**
# Description

Updating es6-promise to 3.3.1

See changelog at https://github.com/stefanpenner/es6-promise/blob/master/CHANGELOG.md#331

Difference between 3.2.1 and 3.3.1.

### CODE REVIEW

**Comment by paladox** [comment]
I do not work for CloudBees.

**Comment by i386** [comment]
Hmm the bot seems very confused. 

Would you be able to tell us a little about the motivation for this change?

**Comment by paladox** [comment]
Oh, the motivation is that 3.3.1 includes a couple fixes, like for ie8, and fixes it's globals. I chose not to go with 3.4.0 since I'm unsure if that would break things.

**Comment by i386** [comment]
Cool. If your intention is to get IE 8 support I believe there might be a bit more work to be done to support IE. I have a suspicion that much of our CSS and Server Sent Events usage won't work.

**Comment by i386** [comment]
FWIW we are supporting only the latest versions of all browsers (including IE 11) but contributions are welcome!

**Comment by paladox** [comment]
Oh yep, I found that Object.assign is not supported in any ie release, so we will need to use the es6-shim there, I also found out that sub arrays of array.prototype.map for example array.prototype.map.apply wont work, and it carn't be polyfilled either.

**Comment by i386** [comment]
Ok no worries. @scherler could you take a look when you've got a spare moment?

**Comment by michaelneale** [comment]
yeah the bot is invoked because the PR template wasn't edited to remove that @ mention - we could change it to not include that? 

Anyway - if this can pass the ATH @scherler - why not, seems worthwhile to update 

(shrinkwrap is currently breaking the build too frequently right now, not related to this PR likely)

**Comment by michaelneale** [comment]
This is currently failing due to shrinkwrap json's needing to be updated (./bin/checkshrinkwrap.js will pick that up) - someone can take a look at this.

**Comment by paladox** [comment]
Thanks, fixed now :)

**Comment by michaelneale** [comment]
Passes ATH: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/build_forks/3

And I bench tested locally. This LGTM. 

@tfennelly @cliffmeyers I am not sure of impact of updating a dep and the shrinkwrap for a thing like this, but it seems all good. Would you mind merging it if you agree?

**Comment by paladox** [comment]
Thankyou

**Comment by tfennelly** [comment]
Thanks @paladox. So if you look at the source you should see that we do add some polyfills for IE browsers. The would be added (conditionally) via the main .jelly file in the blueocean-web plugin. I'm 99.99999% sure `Object.assign` was covered by that.

Those changes did get blue ocean running on IE 11. However, that was a few weeks ago now, so I would not be surprised if more work was needed again (knowing IE 😄  ).

@i386 @michaelneale @scherler

**Comment by tfennelly** [comment]
Hmmm ... I wonder who added those in the first place, and why.

**Comment by paladox** [comment]
Hi ie11 support is still broken since I get this error

object doesn't support property or method 'assign'

**Comment by paladox** [comment]
Hi ie11 support is still broken since I get an error about something with 'apply'

**Comment by paladox** [comment]
object doesn't support property or method 'apply'

**Pull request merged**
