### PR TITLE
JENKINS-41403# Add pipelineFolderNames and scallAllRepos to org folde…

### PR DESCRIPTION
**Pull request by vivek**
Add pipelineFolderNames and scallAllRepos to org folder response

- Added boolean scanAllRepos. scanAllRepos tells whether org folder was setup
  to scan all repositories or only filtered list.
- Add capabilities to org folder pipeline

# Description

See [JENKINS-41403](https://issues.jenkins-ci.org/browse/JENKINS-41403).

- Create a GitHub organization pipeline cloudbeers with no explicitly defined repos
- curl -v http://localhost:8080/jenkins/blue/rest/organizations/jenkins/pipelines/cloudbeers/

```
{
"_class": "io.jenkins.blueocean.blueocean_github_pipeline.GithubOrganizationFolder",
...
"displayName": "CloudBeers",
"fullDisplayName": "CloudBeers",
"fullName": "cloudbeers",
"name": "cloudbeers",
"pipelineFolderNames": [
"PR-demo",
"advanced",
"app-store-demo",
"blueocean-demo-project",
"demo-2",
"demo-2016-12",
"fu-manchu",
"hellonode",
"multibranch-demo",
"pipeline-model-definition-plugin"
],
"scanAllRepos": true,
...
}
```

- Create a GitHub organization pipeline cloudbeers with repo PR-demo
- response should only have PR-demo repo in list of pipelineFolderNames array and scanAllRepos set to false

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by vivek** [comment]
@cliffmeyers PTAL.

**Comment by michaelneale** [comment]
@vivek sorry I have no idea why there are failing javascript errors, but I saw it in other branches. @cliffmeyers are you able to help? Why are they happening just with unrelated changes?

**Comment by michaelneale** [comment]
ok rebuild fixed it - molto odd.. Never mind. Carry on!

**Comment by michaelneale** [comment]
:bee: this looks ok to me, passes ATH. 

Up to @cliffmeyers to give the final call

**Comment by cliffmeyers** [comment]
@vivek I've tested a number of scenarios and this LGTM 🐝

**Comment by michaelneale** [comment]
Tripping up the ATH git creation test it seems.. hopefully will look into it.

**Comment by michaelneale** [comment]
@vivek actually is busted on master :( so not related to this commit. BTW when running locally - did you run -DcleanNode on the ATH as well?

**Comment by michaelneale** [comment]
Ah the problem was introduced from this commit: https://github.com/jenkinsci/blueocean-plugin/pull/768 - it proboably passed the ATH as it it ran it before the git test may have been merged. So this commit may be :bee: to go, but need to resolve that other issue.

**Comment by vivek** [comment]
@michaelneale yes I did -DcleanNode. With some help from libgit2/nodegit on their slack channel, looks like the issue is NodeGit.Signature.default(repo); is returning null in ATH git.js. NodeGit.Signature.default(repo) computes author signature using user.name and user.email from gitconfig, which I have correctly. But still NodeGit.Signature.default(repo) gives null.

**Comment by michaelneale** [comment]
ah right - yes I saw that too.

**Comment by michaelneale** [comment]
passes ATH :bee:

**Pull request merged**
