### PR TITLE
JENKINS-48620 JENKINS-48416 Set sensible default traits for Github, Bitbucket and Git pipelines

### PR DESCRIPTION
**Pull request by i386**
# Description

See [JENKINS-48620](https://issues.jenkins-ci.org/browse/JENKINS-48620) and [JENKINS-48416](https://issues.jenkins-ci.org/browse/JENKINS-48416).

Add trait to discover forks

### CODE REVIEW

**Comment by michaelneale** [comment]
is there any test coverage for this? I know we don't yet do PRs in the ATH, but wondering if other tests can pick it up

**Comment by i386** [comment]
@michaelneale we need some unit tests for sure. Just running here to see if I broke anything.

**Comment by i386** [comment]
@michaelneale @vivek added some tests here, included some fixes for JENKINS-48416 as raised by @bitwiseman

**Comment by kzantow** [comment]
Most. Productive. Product Manager. Ever. :)

**Comment by i386** [comment]
@kzantow bored and jet lagged maybe?

**Comment by i386** [comment]
no idea why coverage is failing - I didn't add any classes. Ideas, @vivek ?

**Comment by vivek** [comment]
@i386 hmm, Jacoco [report](https://ci.blueocean.io/job/blueocean/job/bug%252FJENKINS-48620/3/artifact/blueocean-github-pipeline/target/code-coverage/report/io.jenkins.blueocean.blueocean_github_pipeline/GithubPipelineCreateRequest$1.html)  says https://github.com/jenkinsci/blueocean-plugin/blob/76af0a305b454fba4bff4bb687d2b26614b87496/blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java#L59 is not tested. Looks like test https://github.com/jenkinsci/blueocean-plugin/blob/76af0a305b454fba4bff4bb687d2b26614b87496/blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java#L62 is not executing that code block. I think I added this test to keep jacoco happy, looks like something changed thats resulting in https://github.com/jenkinsci/blueocean-plugin/blob/76af0a305b454fba4bff4bb687d2b26614b87496/blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractMultiBranchCreateRequest.java#L140 returning true instead of false?

**Comment by i386** [comment]
@vivek I think jacoco is telling fibs. We only changed a few lines to add traits to a collection (code we had before) and then added more tests. If anything, code coverage should have increased with this change.

**Comment by vivek** [comment]
@i386 From Jacoco failure it seems a code path is not executing, `GithubPipelineCreateRequest.createPipelineNoJenkinsFile()` tests that but there are no assertions there. I will try your branch later today.

**Comment by rtyler** [comment]
@vivek had a chance to take a look yet? I accidentally rediscovered this today again 😸

**Comment by vivek** [comment]
@rtyler looking in to it:)

**Comment by vivek** [comment]
@i386 @rtyler 
No one looks at jenkins [log](https://ci.blueocean.io/blue/organizations/jenkins/blueocean/detail/bug%2FJENKINS-48620/3/pipeline#step-49-log-2946):) There was a test failure:

```
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:73)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:542)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:660)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:501)
	... 29 more
Caused by: java.io.FileNotFoundException: http://localhost:36940/repos/vivek/empty1/pulls?state=open
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
	at org.kohsuke.github.Requester.parse(Requester.java:602)
	at org.kohsuke.github.Requester.parse(Requester.java:584)
	at org.kohsuke.github.Requester.access$200(Requester.java:70)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:496)
	... 29 more
```

Wiremock needed new mapping/files for pull api for test repo. I have added them, it should be good now.

**Comment by vivek** [comment]
@i386 LGTM 🐝 merge away.

**Pull request merged**
