### PR TITLE
JENKINS-36154# Link related fixes

### PR DESCRIPTION
**Pull request by vivek**
Related to issue # . 

Summary of this pull request: 
.
.
.

@reviewbybees

### CODE REVIEW

**Comment by blueoceandeploy** [comment]
Can one of the admins verify this patch?

**Comment by michaelneale** [comment]
:ant: failing test: io.jenkins.blueocean.service.embedded.MultiBranchTest.getMultiBranchPipelineRunChangeSets

**Comment by vivek** [comment]
@michaelneale oops, there was typo, fixed.

**Comment by scherler** [comment]
looks good, but you encode the branch name but a pipeline name could be "a/b" as well, or? If so, wouldn't you need the same for the name?

**Comment by vivek** [comment]
@scherler No, you can't have folder with '/' in them. Only applies to branch name, which could have any char.

**Comment by michaelneale** [comment]
🐝  I think this is good. Will any front end code need to change that was based on incorrect assumptions? if not - this is good to go.

**Comment by vivek** [comment]
@michaelneale I will let @cliffmeyers @scherler confirm that.

**Comment by cliffmeyers** [comment]
If this change requires that the branch name in the REST API be double URL encoded then yes it will have UI impact. I couldn't quite tell from the PR if that was the case, or if it's just updating the Link href's returned in the JSON.

**Comment by vivek** [comment]
@cliffmeyers This PR just fixes Link to return properly encoded url path, UI can use it as it is. I thought this is what you wanted, no?

**Comment by cliffmeyers** [comment]
@vivek yep, if we can follow the links then that's great.

**Comment by cliffmeyers** [comment]
:bee:

**Comment by michaelneale** [comment]
🐝

**Pull request merged**
