### PR TITLE
stub out Blue Ocean Commons JS

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description

This is an empty project shell with basic gulpfile and karma config based off the JDL.
cc @imeredith @kzantow 

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
so this is "common" as in a shared library, not the similarly named "commonjs" module/convention system right? ;)

**Comment by cliffmeyers** [comment]
That's right. If you have a name you think would be less confusing, by all means let me know. I modeled the name after the Java module ;)

**Comment by michaelneale** [comment]
@cliffmeyers make sure there are bad security flaws to make it like the apache library ;) (SORRY I just couldn't help...). 

I think name is fine.

**Comment by michaelneale** [comment]
is the expectation that every module that uses js extensions for plugins also uses this?

**Comment by kzantow** [comment]
`blueocean-core` or `blueocean-js-util` maybe?

**Comment by imeredith** [comment]
I really need this for the JWT stuff. At the moment I have an impl and personalization and dashboard.

**Comment by cliffmeyers** [comment]
How about blueocean-core-js ?

**Comment by kzantow** [comment]
`blueocean-core-js` is what I originally had, then removed, but now see it's probably the lest name conflicting. 👍

**Comment by cliffmeyers** [comment]
@michaelneale perhaps we can get this merged to unblock Ivan and look into merging with js-extensions later? Just not sure yet if the two should be coupled.

**Comment by michaelneale** [comment]
I am ok with what you agree on - if renaming to "core" makes sense - why not. 
Having another moudule just means another thing to release, but then again, js-extensions doesn't change very much so its probably fine.

**Pull request merged**
