### PR TITLE
Feature/jenkins 42515 even more empty states

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- May need a few refinements so for now leaving "wip" label
- See [JENKINS-42515](https://issues.jenkins-ci.org/browse/JENKINS-42515).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
Non multibranch, Activity tab, no runs:
placeholder-1-non-multibranch-activity-tab-no-runs

Non multibranch, Branches tab:
placeholder-2-non-multibranch-branches-tab

Non multibranch, Pull Requests tab:
placeholder-3-non-multibranch-prs-tab

Multibranch, Activity tab, no runs, but some branches exist. Note: this state is unlikely to happen unless an admin is manually deleting runs.
placeholder-4-multibranch-activity-tab-no-runs-with-branches

Multibranch, Activity tab, no branches. Note: current logic is that if there are no branches, this is displayed regardless of whether there are runs.
placeholder-5-multibranch-activity-tab-no-branches

Multibranch, Activity tab, branch filtering enabled, no runs. Note: this state is unlikely to be encountered unless an admin is deleting runs. I had to invent something here as this scenario was not being handled previously. If the user picked a branch w/ no runs, the entire table was hidden, including the header, which contains the dropdown for selecting a branch. This seemed bad to me, as the user's only option was to use the back button. So I invented something here. Since this uses the old table style, I did not introduce the new placeholder style.
placeholder-6-multibranch-activity-tab-no-runs-branch-selected

cc @i386 @michaelneale @brody

**Comment by cliffmeyers** [comment]
@michaelneale I suspect given the large number of changes that this will break some tests in ATH. Going to wait for the results in CI, and if so begin assessing the impact and testing ATH changes locally.

**Comment by i386** [comment]
> So I invented something here. Since this uses the old table style, I did not introduce the new placeholder style.

Can you please raise a new ticket for us to revisit this one when the tables go in?

**Comment by i386** [comment]
These look beautiful @cliffmeyers @brody - nice work :)

**Comment by michaelneale** [comment]
ok taking a look. ATH tests that need some surgery: 

Test Result (4 failures / +4)
smoke.Step 02
io.jenkins.blueocean.AllTest.nightwatchTestRun
folder.step 01
branchPRTabs.Step 02

**Comment by michaelneale** [comment]
tested a few permutations and looks good to me. 

Need to sort out ATH, and get a code review from @sophistifunk

**Comment by sophistifunk** [comment]
Code LGTM 🐝

**Comment by michaelneale** [comment]
ATH PR to cover this: https://github.com/jenkinsci/blueocean-acceptance-test/pull/131 will report back if it passes.

**Comment by brody** [comment]
👌 🐝

**Pull request merged**
