### PR TITLE
JENKINS-44223# Removed flaky test block

### PR DESCRIPTION
**Pull request by vivek**
It was not testing anything useful.

# Description

See [JENKINS-44223](https://issues.jenkins-ci.org/browse/JENKINS-44223).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
yes - as long as passes unit tests :bee: from me

**Comment by i386** [comment]
ahhh test was just shitty? Nice 🐝

**Comment by vivek** [comment]
@i386 yes, that block was testing execution of shell step in parallel block `sh 'echo right done'`. In another branch it has waiting input step. Test waits for execution to suspend and right after that it was expecting it to be in RUNNING state, which is absolutely time dependent as it could also be FINISHED depending on timing. There was no point checking that step's state anyways, so better to remove it.

**Comment by i386** [comment]
Is a unit test, does not need an ATH run.

**Comment by michaelneale** [comment]
yep, killed it.

**Pull request merged**
