### PR TITLE
Plugin description

### PR DESCRIPTION
**Pull request by i386**
# Description

Provide a description for the Blue Ocean plugin. We didn't have one!

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by vivek** [comment]
LGTM 🐝

**Comment by i386** [comment]
Thanks @vivek

**Comment by recena** [comment]
@i386 Great. In fact, it would be interesting if all BO components (plugins) have its own description. That description is used in different places on the Jenkins UI.

**Comment by recena** [comment]
🐝

**Pull request merged**
