### PR TITLE
Publish under "jenkins" dockerhub organization

### PR DESCRIPTION
**Pull request by ndeloof**
see https://github.com/jenkinsci/docker/issues/515

### CODE REVIEW

**Comment by michaelneale** [comment]
need a review from @rtyler for this - as shouldn't it publish to both?

**Comment by ndeloof** [comment]
I'd prefer we avoid duplication with two official names for our images organization.
jenkinsci could just be deprecated (like jenkins official image)

**Comment by michaelneale** [comment]
@ndeloof but as mentioned before - there is no real deprecation. People will still expect it to be there. Jenkinsci is the org that I know about so this is -1 from me until @rtyler agrees. Not our call.

**Comment by ndeloof** [comment]
I'm asking docker if they can configure redirects on dockerhub (like github does)
in the meantime we could indeed have dual deployment, at least for a transition period

**Comment by michaelneale** [comment]
thanks @ndeloof !

**Comment by ndeloof** [comment]
@rtyler added (expected to be temporary) dual publishing

**Comment by michaelneale** [comment]
ok, will wait for @rtyler to return from vacay to final bless - but :bee: from me

**Comment by i386** [comment]
I'd also like to see the README.md updated to reflect the documentation in the Jenkins base image. This can be as simple as a link to that container on Docker Hub.

**Comment by michaelneale** [comment]
hey @rtyler still interested?

**Comment by rtyler** [comment]
@michaelneale I'm not not interesting, but this is not something that I can spend any time on.


As far as the Blue Ocean container is concerned, this is fine. If the desire is that all containers move over to the `jenkins` organization, then somebody should champion this and bring it up as a topic in a Governance Meetings or on the dev list.

**Comment by michaelneale** [comment]
can open this back up later when we get time. In time a specific blue ocean image may not permanently be a thing (once blue ocean gets into recommended plugins, for instance). 

Just clearing this out as the number of PRs left open is exploding.

**Pull request closed without merging**
