### PR TITLE
[JENKINS-37832] Redirect to login page on 401

### PR DESCRIPTION
**Pull request by imeredith**
# Description

@michaelneale This needs some testing. it will redirect on a 401. But Im not sure if our api always returns 401! I found at least one case where that is not true.

See [JENKINS-37832](https://issues.jenkins-ci.org/browse/JENKINS-37832).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
@imeredith where was returning 401 not true?

**Comment by i386** [comment]
🐛 Be logged out. Visit `/blue` and get lots of 403's

jenkins blue ocean 2016-09-06 10-34-20

**Comment by imeredith** [comment]
sorry forgot to release core-js

**Comment by michaelneale** [comment]
@i386 on talking with Ivan, he is looking at another way of detecting session downgrade and forcing a login, which we hope will be better in the short term.

**Pull request closed without merging**
