### PR TITLE
Bug/jenkins 40662 run details close problem

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- ATH regression test:  jenkinsci/blueocean-acceptance-test#93
- See [JENKINS-40662](https://issues.jenkins-ci.org/browse/JENKINS-40662).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by cliffmeyers** [comment]
Running this branch against the ATH changes from jenkinsci/blueocean-acceptance-test#93 passed:

```
2017-01-03 17:33:36,986 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - OK. 933  total assertions passed. (9m 56s)
```

**Comment by cliffmeyers** [comment]
Re-ran after merge, passed.

```
2017-01-03 17:56:38,760 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - OK. 994  total assertions passed. (9m 56s)
```

**Comment by cliffmeyers** [comment]
Re-ran again. Failed three times for no reason - wasting 30m - then worked the 4th time. Yay :)

```
2017-01-04 13:46:48,658 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - OK. 927  total assertions passed. (9m 7s)
2017-01-04 13:46:48,717 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - [13:46:48] Finished 'default' after 9.13 min
**** NightwatchRunner - No failures.
```

**Comment by imeredith** [comment]
:bee: Confirmed fix locally.

**Comment by scherler** [comment]
:+1: but @cliffmeyers see my comments on the ath pr

**Comment by cliffmeyers** [comment]
ATH passed locally.

```
2017-01-09 11:50:59,824 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - OK. 928  total assertions passed. (9m 21s)
2017-01-09 11:50:59,884 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - [11:50:59] Finished 'default' after 9.37 min
**** NightwatchRunner - No failures.
```

**Comment by cliffmeyers** [comment]
Just waiting on green light for jenkinsci/blueocean-acceptance-tests#93 then will merge this puppy.

**Pull request merged**
