### PR TITLE
JENKINS-43208# Exclude job history config action

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-43208](https://issues.jenkins-ci.org/browse/JENKINS-43208).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by vivek** [comment]
@michaelneale @i386  PTAL https://github.com/jenkinsci/blueocean-plugin/pull/934

**Comment by michaelneale** [comment]
LGTM - lets let the tests run - but yeah :bee: otherwise.

**Comment by i386** [comment]
LGTM

**Comment by michaelneale** [comment]
:bee:

**Comment by vivek** [comment]
@michaelneale how about merging to release branch, let me know.

**Pull request merged**
