### PR TITLE
FIX JENKINS-38673

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-38673](https://issues.jenkins-ci.org/browse/JENKINS-38673).

JDL and AT related PRs

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

```
OK. 9 assertions passed. (3.023s)
Disconnected from the Jenkins SSE Gateway.

OK. 337  total assertions passed. (6m 22s)
```

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
@scherler is this ready for review? (has shrinkwrap failure BTW)

**Comment by michaelneale** [comment]
needs review by @cliffmeyers and or @kzantow

**Comment by sophistifunk** [comment]
Seems fine to me 🐝

**Comment by michaelneale** [comment]
I am seeing some oddness, not sure if related. After clicking around a while I see: 

```
jenkins-js-extension.js:48573 Uncaught (in promise) TypeError: Cannot read property 'filter' of undefined
    at http://localhost:8080/jenkins/adjuncts/411ec476/org/jenkins/ui/jsmodules/blueocean-dashboard/jenkins-js-extension.js:48573:37
    at http://localhost:8080/jenkins/adjuncts/411ec476/org/jenkins/ui/jsmodules/blueocean-dashboard/jenkins-js-extension.js:49845:13(anonymous function) @ jenkins-js-extension.js:48573(anonymous function) @ jenkins-js-extension.js:49845
```

**Comment by scherler** [comment]
@michaelneale did you fill a bug for above? It seems to related with favs somehow

**Comment by michaelneale** [comment]
@scherler no but I will. @cliffmeyers mind casting your "conservative eye" over this please?

**Comment by scherler** [comment]
If you do not Beat me to it, I will create a ticket tomorrow for it. From the looks it reminds me on something is not using unmount when it should. It has all the signs. Phantom fetches resulting in 404

**Comment by michaelneale** [comment]
@scherler if you can open a ticket, I would appreciate it (you can probably describe it better).

**Comment by michaelneale** [comment]
@scherler if you can update to master and kick off ATH that would be good

**Pull request merged**
