### PR TITLE
JENKINS-39635 Suppress click if selection

### PR DESCRIPTION
**Pull request by imeredith**
# Description

See [JENKINS-39635](https://issues.jenkins-ci.org/browse/JENKINS-39635).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
@imeredith this one is failing to build and needs to be resync'd

**Comment by michaelneale** [comment]
@imeredith checkdeps failed on this (I think)...

**Comment by michaelneale** [comment]
@imeredith 
```
Create new commits and check activity and branches page for correct commit messages – commitMessages
a few seconds
Error
Failed [equal]: (7 == 2)
```

Possibly legit error on ATH - investigating.

**Comment by michaelneale** [comment]
@imeredith I took the liberty of updating this to master and now it passes ATH

Also :bee:

**Comment by michaelneale** [comment]
@i386 can you verify this does what is expected?

**Comment by i386** [comment]
@michaelneale I had Ivan talk this over on a call last week and trust he got it right.

**Comment by cliffmeyers** [comment]
This PR doesn't actually include any code changes, just updates to package.json and shrink. Is that correct?

**Comment by imeredith** [comment]
@cliffmeyers sorry filed pr.

**Comment by cliffmeyers** [comment]
JDL change looks good, so this one LGTM 🐝

**Comment by i386** [comment]
Any reason this one is stuck?

**Comment by cliffmeyers** [comment]
Downsteam PR needs a fix to resolve a Flow error, I believe.

**Comment by NicuPascu** [comment]
I have updated this to master and confirmed the fix made by Ivan fixes the issue, from my point of view this is ready to merge after core-js and jdl non-beta publishing

**Comment by michaelneale** [comment]
there is a test error (missing method) so something isn't right

**Comment by NicuPascu** [comment]
fixed the failing test, it should build successfully now

**Comment by michaelneale** [comment]
nice one - would you mind updating this to master as this is a very old version of things.

**Comment by NicuPascu** [comment]
I already merged master in this branch on Friday, if you are happy with the changes I can do the releases for the jdl and core-js and merge this

**Comment by michaelneale** [comment]
@NicuPascu when I tried this, it was much older than that - didn't have a blue ocean link in the side but at the top - indicating it was from a very old (> 1 month) version of master (or perhaps I didn't pull it correctly... hrm).

**Comment by NicuPascu** [comment]
@michaelneale Can you please check again with this version? I merged master again and released the new versions of core-js and jdl so this should be ready for merge if the build succeeds

**Comment by michaelneale** [comment]
:bee: nice one @NicuPascu  thanks for taking this one on.

**Pull request merged**
