### PR TITLE
[NO-TICKET] Remove minimum java 11 from plugin. BO works fine in 8+

### PR DESCRIPTION
**Pull request by halkeye**
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [X] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [X] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by halkeye** [comment]
@borisivan reported it on gitter:

image

It was leftover from adding java11 support.

Its been fixed on the release/1.11 branch, and now merging into master.

**Comment by michelzanini** [comment]
I was just going to create a ticket for this 👍 
After merge, can we release a patch please, thanks

**Comment by halkeye** [comment]
> After merge, can we release a patch please, thanks

I did it in reverse order, 1.11.1 will be about 30 min to run though the build pipeline, then it'll go out.

**Comment by michelzanini** [comment]
I can confirm 1.11.1 is working fine

**Comment by halkeye** [comment]
thanks @michelzanini 

Just waiting for green on https://ci.blueocean.io/blue/organizations/jenkins/blueocean/activity/ even though I know it won't break anything

**Pull request merged**
