### PR TITLE
Task/jenkins 38597 clean slashes

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- Refine logic in core-js for cleaning up URL's and add some tests

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by cliffmeyers** [comment]
ATH passed locally.

```
2017-01-20 15:16:06,965 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - OK. 1088  total assertions passed. (10m 22s)
2017-01-20 15:16:07,033 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - [15:16:07] Finished 'default' after 10 min
**** NightwatchRunner - No failures.
```

**Comment by cliffmeyers** [comment]
ATH passed locally.

```
2017-01-20 15:51:43,660 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - OK. 1247  total assertions passed. (11m 5s)
2017-01-20 15:51:43,713 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - [15:51:43] Finished 'default' after 11 min
**** NightwatchRunner - No failures.

```

**Comment by sophistifunk** [comment]
LGTM 🐝

**Comment by michaelneale** [comment]
adding tests - nice. ATH seems happy so go for it !

:bee:

**Comment by cliffmeyers** [comment]
After merging master and publishing prod core-js the ATH passed locally 

```
2017-01-23 10:50:49,859 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - OK. 1375  total assertions passed. (11m 23s)
2017-01-23 10:50:49,914 [Thread-3] INFO   (InputStreamHandler.java:47) com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - [10:50:49] Finished 'default' after 11 min
**** NightwatchRunner - No failures.
```

Will merge as soon as CI build completes.

**Pull request merged**
