### PR TITLE
Compatibility test of bumped git-plugin and git-client-plugin levels

### PR DESCRIPTION
**Pull request by kshultzCB**
# Description

JENKINS issue N/A. This is a test-only PR.

But, see also [git-plugin beta-4.0](https://github.com/jenkinsci/git-plugin/tree/beta-4.0) and [git-client-plugin beta-3.0](https://github.com/jenkinsci/git-client-plugin/tree/beta-3.0) for the changes this is intended to test.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate: N/A
- [x] Change is code complete and matches issue description: N/A
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests: N/A
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below: N/A

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by kshultzCB** [comment]
Tagging @MarkEWaite so he'll know this is under way.

**Comment by MarkEWaite** [comment]
Thanks for the tag @kshultzCB .  I expect there are two tests that will fail, since they failed when I ran them in my development environment.  While exploring it, the tests seemed to fail on some credentials related UI pick.

The beta plugin releases include more credential validation than was done in previous releases.  I had assumed that was the cause of the failures, but when I ran the same automated tests with an earlier version of the plugin without those credential validation additions, the tests still failed.  That was the point where I shifted focus to other areas, hoping that someone with Blue Ocean test automation skills would investigate.

**Comment by kshultzCB** [comment]
There were two failures shown that look interesting, but they're really just one test that got retried.

`io.jenkins.blueocean.blueocean_git_pipeline.GitScmTest.shouldFailForBadCredentialIdOnCreate` failed with a TransportException from the jgit API:

```
SEVERE: Error running git remote-ls: org.eclipse.jgit.api.errors.TransportException: git@github.com:vivek/capability-annotation.git: remote hung up unexpectedly
hudson.plugins.git.GitException: org.eclipse.jgit.api.errors.TransportException: git@github.com:vivek/capability-annotation.git: remote hung up unexpectedly
```

The code for that test itself  can be seen [here](https://github.com/jenkinsci/blueocean-plugin/blob/master/blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScmTest.java#L188-L224)).

**Comment by halkeye** [comment]
@kshultzCB what do you want to do about this PR? Rebase it? 

Josh and I put in a lot of work over the last couple weeks getting the ATH running cleanly again, so that might be the source of your failures, not sure.

**Comment by MarkEWaite** [comment]
Definitely do not merge this PR until the test failures are understood and
resolved.

**Comment by halkeye** [comment]
> Definitely do not merge this PR until the test failures are understood and resolved.

Ah my bad, I was asking if this would ever be merged type thing. it says "this is just a test" so wasn't sure.

I vote rebase the branch with master and let things re-run

**Comment by halkeye** [comment]
Karl says its okay to close now. So closing :)

**Pull request closed without merging**
