### PR TITLE
Remove blueocean-web dependency from blueocean-rest

### PR DESCRIPTION
**Pull request by vivek**
This makes blueocean-rest pure model. Other components including
blueocean-web can depend on rest model to interconnect model and UI
components.

For example this will allow plugin developers to implement blueocean extensions without depending on UI components.

@i386 PTAL

# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
Similarly to https://github.com/jenkinsci/blueocean-plugin/pull/956 - what is the impact on the editor plugin? Having trouble understanding all these changes and the large effects it may have

**Comment by michaelneale** [comment]
This will need to be checked with @kzantow as I am not sure of impact on these dependency changes with the editor (external) plugin.

**Comment by i386** [comment]
Seems reasonable - thanks for doing this.

Echoing @michaelneale we need to ensure the editor works and it's tests pass before we do this

**Comment by michaelneale** [comment]
also looked at this some more - as long as @kzantow is ok - this is probably fine, go ahead if so.

**Pull request merged**
