### PR TITLE
JENKINS-43978 Stop really long cause messages from blowing out results screen

### PR DESCRIPTION
**Pull request by NicuPascu**
# Description

See [JENKINS-43978](https://issues.jenkins-ci.org/browse/JENKINS-43978).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
nice - not sure how to test though? any ideas?

**Comment by NicuPascu** [comment]
I just manually change the message via dev tools to something very long

**Comment by i386** [comment]
Got a screenshot Nicu?

**Comment by NicuPascu** [comment]
scrnshot

**Comment by NicuPascu** [comment]
I also added the title atr on the element so on hover the full text appears as a tooltip

**Comment by i386** [comment]
Looks great 👍

Have another developer LGTM and merge :)

**Comment by i386** [comment]
Good call on the title attribute!

**Comment by michaelneale** [comment]
:bee:

**Pull request merged**
