### PR TITLE
[JENKINS-56460] Remove log spam from System.out.println

### PR DESCRIPTION
**Pull request by reinholdfuereder**
See [JENKINS-56460](https://issues.jenkins-ci.org/browse/JENKINS-56460).

### CODE REVIEW

**Comment by reinholdfuereder** [comment]
The 2 failing ATH tests are IMHO completely unrelated and irrelevant: https://ci.blueocean.io/blue/organizations/jenkins/blueocean/detail/PR-1931/1/tests
* ATH - Jenkins 2.138.4 / testEditorParallel – io.blueocean.ath.live.GithubEditorTest53s
* ATH - Jenkins 2.138.4 / testEditorSetEnvironmentVariables – io.blueocean.ath.live.GithubEditorTest

**Comment by halkeye** [comment]
yea we've been working on ath for a while now, i'll retrigger your build on the "more reliable" agent, but i'll probabably just merge

**Comment by michaelneale** [comment]
haaa oops. Nice catch @reinholdfuereder !

**Comment by halkeye** [comment]
@reinholdfuereder Can you rebase with master We renamed the directory? Otherwise I'll do a manual merge tomorrow.

**Comment by reinholdfuereder** [comment]
@halkeye I tried to rebase (atop latest version), but somehow I have the feeling something went wrong (cf. files changes: 21!?) => sorry for the inconvenience

**Comment by halkeye** [comment]
yea :( the directory renaming is messing things up.

I can create a new PR and remove it, i'll try and use your commit so you get "credit"

**Comment by halkeye** [comment]
manually merged 44ba82633155806cfeb8d66435d3e408ffb6a970

**Pull request closed without merging**
