### PR TITLE
[JENKINS-38460] Move toaster from bottom left to bottom right

### PR DESCRIPTION
**Pull request by ModuloM**
# Description

See [JENKINS-38460](https://issues.jenkins-ci.org/browse/JENKINS-38460).

Warning: depends on https://github.com/jenkinsci/jenkins-design-language/pull/161.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
Nice job and thanks for contributing!

Could you add a screenshot here just so I can usually confirm please?

**Comment by michaelneale** [comment]
I'll spin this up later and show...

**Comment by michaelneale** [comment]
ATH passes: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/1975/

**Comment by michaelneale** [comment]
Here is what it looks like: 

screen shot 2017-03-29 at 6 06 12 pm

**Comment by i386** [comment]
LGTM 🙌

**Comment by michaelneale** [comment]
Does this really require the PR to the JDL? As it works just fine without it, as it is in this PR alone. I am confuse.

**Comment by ModuloM** [comment]
Initially there was a case where the toaster wasn't exactly to the right. This happened when restarting a pipeline for example. 
First I had overwritten the CSS rule in toaster.less. But it seemed like a hack to me. So I have submitted an other PR in JDL repo to properly change the rule.
Maybe I'm wrong or maybe you don't have the last modified version  of this PR.
Hope this helps.

**Comment by brody** [comment]
🐝

**Comment by cliffmeyers** [comment]
@michaelneale this raises an interesting point that contributors won't be able to publish a beta JDL so that those changes can be easily incorporated into PR's against blueocean-plugin.

@ModuloM Right now there is a PR with `align-items: flex-end` (right-aligned) in the JDL, and then CSS in this PR that places the `Toaster` on the right side of the screen. I think we want to ensure that the CSS which handles `Toaster` alignment is in the same repo.

I think perhaps we ought to close jenkinsci/design-language#161 and add the `align-items` CSS in this PR. You should be able to override it in `blueocean-web` by default, or can use a more specific selector if necessary.

**Comment by michaelneale** [comment]
@cliffmeyers yes good Q on JDL - I guess with any future solution we would have to treat it closer to a normal plugin? (I am not sure if that is the intent of the JDL though...). Not sure of the longer term solution to this...

**Comment by ModuloM** [comment]
Hi,

@cliffmeyers Ok, I have pushed an update that overwrite the JDL behavior. In this case, jenkinsci/jenkins-design-language#161 can be close. Do you want me to do it?

**Comment by cliffmeyers** [comment]
Tested this locally and looks good!

@ModuloM thank you for the contribution. I am merging this now. I also closed the JDL PR earlier today.

**Pull request merged**
