### PR TITLE
JENKINS-43671# Test coverage investigation

### PR DESCRIPTION
**Pull request by vivek**
haltOnFailure is false, that is building blueocean modules will not fail
build if coverage criteria is not met.

At present to enable this propert use -Djacoco.haltOnFailure=true with
mvn.

# Description

See [JENKINS-43671](https://issues.jenkins-ci.org/browse/JENKINS-43671).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
nice

**Comment by vivek** [comment]
@michaelneale I think we should let it merge. This will give warning but will be handy to determine if newly added code has good coverage or not. When we have all in good standing, we can turn on to fail if specific coverage threshold is not met.

**Comment by michaelneale** [comment]
SGTM :bee: in that case, s long as all tests happy etc.

**Comment by vivek** [comment]
@michaelneale For some reason ATH is failing. There has only test coverage related changes in pom, any idea what could this be? https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/master/2337/pipeline

**Comment by michaelneale** [comment]
@vivek update it to master - as there was a recent change on tables that affect ATH validation, and then it should be ok. If not, I will take a look later.

**Comment by vivek** [comment]
@michaelneale done. Lets see if it goes thru.

**Comment by michaelneale** [comment]
@vivek ATH passes if you are happy then :bee: from me as I think @i386 is happy

**Pull request merged**
