### PR TITLE
bug / jenkins 43259 parameterized form unstyled

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- The old empty state set `color: white` and the nested `ParametersRunButton` was eventually inheriting that since the `Dialog` is a child element. This is actually fixed in master already since the new empty state doesn't set that color. However it seems prudent to set a reasonable default color for this form to avoid similar issues in other places.
- See [JENKINS-43259](https://issues.jenkins-ci.org/browse/JENKINS-43259).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
Fixed a similar issue I noticed on ATH where whitespace was also inherited.

input-parameters-not-wrapping

**Comment by i386** [comment]
LGTM 👍

**Comment by michaelneale** [comment]
:bee:

**Comment by cliffmeyers** [comment]
ATH passed:  https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/master/2043/pipeline/17

**Comment by cliffmeyers** [comment]
ATH passed: https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/master/2045/pipeline/17

**Comment by kxepal** [comment]
Hi there! I just noticed that PR was merged for 1.0 release and was happy to check it, but suddenly, the problem is still actual:


I tried to comment this on JIRA issue, but eventually I cannot register /: Probably, due to 404 response on jquery.min.js.

**Comment by i386** [comment]
@kxepal it will be in Blue Ocean 1.1 - sorry for the confusion!

**Comment by kxepal** [comment]
Oh, good to know! Thanks a lot for fixing this! \o/

**Pull request merged**
