### PR TITLE
[JENKINS-62666] Adding a /jwt-auth/jwks endpoint that follows the RFC7517

### PR DESCRIPTION
**Pull request by Lucas-C**
# Description

See [JENKINS-62666](https://issues.jenkins-ci.org/browse/JENKINS-62666).

Many thanks to @lenaing with whom I coded this

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by Lucas-C** [comment]
Note that would had to fix the Base64 encoding of the `n` & `e` fields in `SigningPublicKey.java` in order to make the output of `/jwt-auth/jwk-set` fully compliant with the spec: a [base64url encoding](https://fr.wikipedia.org/wiki/Base64#base64url) must be used, with zero padding.
We learned that during our tests to make this work with HashiCorp Vault JWT auth.

**Comment by Lucas-C** [comment]
Note also that we could allow the existing `/jwks` endpoint to return a valid `{"keys": {...}}` JWKS JSON output, but this would mean that the endpoint could return 2 different types of output structure.

I prefered to avoid that, but I'd be happy to have the reviewer viewpoint on this.

**Comment by bitwiseman** [comment]
@Lucas-C 
Thanks for this high quality PR.   Documentation, test, comments, all present and a big help. 

I don't feel I personally have enough knowledge to review this yet. I'll pin it to my notifications and come back to it next week, okay?

**Comment by Lucas-C** [comment]
Sure, no hurry

**Comment by lenaing** [comment]
Hello,

As discussed with @Lucas-C , I added a "past year" check to handle month key change.
So we will list in the key set all potentially generated keys from the past year.

Kind regards,

**Comment by Lucas-C** [comment]
Hi !

Has someone been able to review this PR ? :)

**Pull request merged**
