### PR TITLE
Merge the pipeline-editor

### PR DESCRIPTION
**Pull request by kzantow**
# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
@kzantow when this goes to master - will be squashed into one I guess?

**Comment by kzantow** [comment]
@michaelneale no, I'll disable the squash temporarily (as I did for JDL)

**Comment by michaelneale** [comment]
@kzantow well, may not matter too much - its just if we are doing this to ease the release of 1.2 - not sure if that makes it easier or harder

**Comment by kzantow** [comment]
@michaelneale doesn't really change anything, just keeps the history.

**Comment by kzantow** [comment]
@michaelneale ... and it does make things easier, we just release one thing and don't have to do a maven release dance.

**Comment by kzantow** [comment]
For fun, I also ran the script against 1.2: https://github.com/jenkinsci/blueocean-plugin/pull/1346

**Comment by michaelneale** [comment]
that failure looks legit to me... worth checking out?

**Comment by michaelneale** [comment]
I removed the jackson version like the 1.2 branch (although perhaps you will just merge back from there to here... so ...)

**Comment by kzantow** [comment]
Superseded by: #1350

**Pull request closed without merging**
