### PR TITLE
Pass the run instance to 'jenkins.pipeline.run.result' implementation.

### PR DESCRIPTION
**Pull request by tfennelly**
# Description

See [JENKINS-37979](https://issues.jenkins-ci.org/browse/JENKINS-37979). No unit test practical here. Nothing you can really test ... will run the ATH.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by scherler** [comment]
yeah but I do not like much that we now do run.id and run, still :bee:

**Comment by tfennelly** [comment]
@scherler You are right but I need this in a hurry and I know fixing the EP impls will result in some BS ... Murphy's Law ... I created [JENKINS-37980](https://issues.jenkins-ci.org/browse/JENKINS-37980) for me to come back and tidy that up.

**Comment by kzantow** [comment]
:bee: agree, eventually get rid of the run.id but fine for now

**Comment by michaelneale** [comment]
LGTM  - should be fine with ATH right?

**Pull request merged**
