### PR TITLE
Feature/jenkins 36905 favorite card run rerun

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description

See [JENKINS-36905](https://issues.jenkins-ci.org/browse/JENKINS-36905).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [x] Run the changes and verified the change matches the issue description
 - Load up the application ensure you have a few favorited items. Ideally have one MBP, one regular Pipeline and one freestyle all of which fail at the end. Easy to do by pasting some nonsense command at the end of the script.
 - Verify that all three job types can be run via the run button. They should update in real time based on work done in a previous PR.
 - Verify that the replay buttons displays for MBP and Pipeline but not Freestyle. Verify that replay launches a new build and that they update in real time.
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
Wasn't able to run when logged in: 

on server: 
```WARNING: No valid crumb was included in request for /jenkins/blue/blue/rest/organizations/jenkins/pipelines/keith/branches/passing/runs/. Returning 403.
```

client: 
```
http://localhost:8080/jenkins/blue/blue/rest/organizations/jenkins/pipelines/pipe/runs/ Failed to load resource: the server responded with a status of 403 (No valid crumb was included in the request)
```

so a :bug: 

Also, I am not sure it matches the style:
screen shot 2016-08-19 at 10 15 35 am - does it @i386 ?

**Comment by i386** [comment]
@cliffmeyers that should be https://design.google.com/icons/#ic_play_circle_outline

**Comment by michaelneale** [comment]
@cliffmeyers people were being mean to me on twitter about being a manager so I tried debugging this like you showed me. That crump error seems to only show up with post, so I changed to PUT so it would work. Maybe follow that up with @vivek ? 

I also changed the icon (cc @i386)

It works for all three job types, but I am not sure what you mean by: 

"Verify that the replay buttons displays for MBP and Pipeline but not Freestyle. Verify that replay launches a new build and that they update in real time."

The same looking button shows up for all types, but I don't see a replay button (not sure what that should be). Replay means - replay that same commit, but just run means "run it again from HEAD"? I am not sure what the design is here so will defer to @i386 

Code looks good, and what I can tell works, so if this can be reviewed/verified then a provisional LGTM from me!

#managercode

**Comment by i386** [comment]
@michaelneale replay does not work for non-Pipeline jobs (ask @imeredith for a history of why that is the case).

Failing cards need to have three buttons on them:
* Replay (for Pipeline) https://design.google.com/icons/#ic_replay
* Run https://design.google.com/icons/#ic_play_circle_outline
* Favourite

**Comment by michaelneale** [comment]
@i386 yep verified, works great!

**Comment by i386** [comment]
@michaelneale @cliffmeyers wonderbar!

**Comment by cliffmeyers** [comment]
@michaelneale I will pull this down and do some testing later today. The docs say that starting a new build should use a POST (sensible) whereas a "replay" should use a PUT. This 403 thing might be the same bug we tracked down the other day; unfortunately with all these branches being worked at the same time I may have forgotten to make the fix. Will sort it out and let you know...

**Comment by cliffmeyers** [comment]
@michaelneale I noticed that some requests were to /jenkins/blue/blue so I fixed those. I am not sure if those were ultimately causing issues with POST / PUT or not. Maybe we can touch base when you are online today.

**Comment by michaelneale** [comment]
:bee:

**Comment by cliffmeyers** [comment]
Passed local run of ATH. Merging.

**Pull request merged**
