### PR TITLE
Merge JDL into blueocean

### PR DESCRIPTION
**Pull request by kzantow**
Check the history. Follow-on with the changes to turn JDL and core-js into plugins / fixing the NPM dance

### CODE REVIEW

**Comment by michaelneale** [comment]
ok with me if with others

**Comment by michaelneale** [comment]
(ignore failure)

**Comment by imeredith** [comment]
+1 for me

**Comment by michaelneale** [comment]
@sophistifunk would like this change in: https://github.com/jenkinsci/jenkins-design-language/pull/171 - cc @kzantow

**Comment by sophistifunk** [comment]
OK, I've merged 171 into the old master. Only the following files contain useful changes:

* src/js/components/jtable/JTable.jsx
* src/js/components/jtable/TableCell.jsx
* src/js/components/jtable/TableRow.jsx
* src/js/stories/JTableStories.jsx

**Comment by michaelneale** [comment]
@kzantow you can do this at your leisure - just ensure you get any recent changes @sophistifunk may have pushed in! Looks good to me.

**Pull request closed without merging**
