### PR TITLE
JENKINS-45099 escape step description so that it is ECMA script safe

### PR DESCRIPTION
**Pull request by i386**
# Description

See [JENKINS-45099](https://issues.jenkins-ci.org/browse/JENKINS-45099).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
I can't see a reason for this to be yellow, so I've restarted it.

**Comment by michaelneale** [comment]
nah failure looks legit: 

```
BlockStageStepsWithDesc – io.jenkins.blueocean.rest.impl.pipeline.PipelineNodeTest
Error
expected:<echo ["Building]"> but was:<echo [\"Building\]">
```

So @i386, is there some unfortunate side effect of this or is that escaping correct now and the test should be adjusted? As it looks funny...

**Comment by sophistifunk** [comment]
I didn't mean that I found the error and thought it was bogus, I just couldn't for the life of me find the error in the logs :(

**Comment by sophistifunk** [comment]
We get a "whole pipeline is yellow" alarm and then every individual step is green :(

**Comment by sophistifunk** [comment]
I'm not sure I understand the original problem well enough- why would escape characters in the log break UI stuff? We have them in ours and while it's not being shown in colour the way we'd like, it doesn't break.

**Comment by i386** [comment]
@michaelneale thinking about this fix - its not at the right level. We should be making sure stapler encodes JSON properly (hint: It doesn't).

**Comment by michaelneale** [comment]
@i386 agree - but that may be a battle. Should we open a ticket anyway for it?

**Comment by sophistifunk** [comment]
Sounds like fun. Surely we don't have code that relies on Stapler being able to generate bad JSON?

**Comment by michaelneale** [comment]
@sophistifunk stapler says "hold my beer..."

**Comment by i386** [comment]
@michaelneale I've submitted a PR for this in Stapler https://github.com/stapler/stapler/pull/122. When its approved, we can back port it to our own copy of stapler in master and close the ticket out.

**Comment by michaelneale** [comment]
@i386 nice! that will be great and I bet help a lot of people.

**Pull request closed without merging**
