### PR TITLE
[FIX JENKINS-42001] New Jenkins logo for Blueocean

### PR DESCRIPTION
**Pull request by imeredith**
# Description

@brody @michaelneale @i386 does that look right? it kinda seems to big but I'm having a hard time matching it to text exactly.

See [JENKINS-42001](https://issues.jenkins-ci.org/browse/JENKINS-42001).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by imeredith** [comment]
screen shot 2017-03-08 at 11 49 57 am

**Comment by michaelneale** [comment]
taking a look. So sad to see the swoosh go.

**Comment by imeredith** [comment]
That has a hieght of 20px (vs old circle logo having 24px)

**Comment by michaelneale** [comment]
@imeredith I am still seeing old logo even after a clean build - is there something missing?

**Comment by brody** [comment]
The design was 17px high.. not that I'm tied to that. 
If we can move it 1px lower, so its visually centred vertically, I'd bee that. ⬇

**Comment by michaelneale** [comment]
:bee: look ok to me - like @brody says a small tweak woudln't hurt at some point.

**Comment by kzantow** [comment]
@michaelneale @brody maybe we can use the swoosh somewhere else? blue ocean config or something? in a footer? who knows, it is sad to see the serif typeface back (though, I know it is sorta the trademark lettering...)

**Comment by brody** [comment]
@kzantow I'll be using the sloshy logo for the Bondi UI, the design language/system when I get around to it.
The intention is to update the logo down the line but that might be a marketing job.

**Comment by imeredith** [comment]
screen shot 2017-03-09 at 11 03 14 am

**Comment by imeredith** [comment]
@brody Is that better?

**Comment by imeredith** [comment]
screen shot 2017-03-09 at 11 05 28 am

17px high instead of 20px

**Comment by michaelneale** [comment]
:bee:

**Pull request merged**
