### PR TITLE
JENKINS-42105 Update all text copy for creation flow

### PR DESCRIPTION
**Pull request by i386**
# Description

Word smithing the creation flow and improved "pick one" and "auto discover" flows.

See [JENKINS-42105](https://issues.jenkins-ci.org/browse/JENKINS-42105).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
*Github*
screencapture-localhost-8080-jenkins-blue-create-pipeline-1490574721391

*Git*
screencapture-localhost-8080-jenkins-blue-create-pipeline-1490574908313

**Comment by i386** [comment]
PTAL @michaelneale @cliffmeyers

**Comment by michaelneale** [comment]
:bee: - ATH is happy so go for it.

**Comment by i386** [comment]
@michaelneale thanks!

**Pull request merged**
