### PR TITLE
[WiP] First class data types / extra extension points / extensible router

### PR DESCRIPTION
**Pull request by kzantow**
**Decription**

Add some appropriate extension points to the UI to handle different job data types.

**Submitter checklist**
- [ ] Change is code complete and matches issue description
- [ ] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

**Reviewer checklist**
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
@kzantow sorry there have been some refactorings that caused the conflict (a new module). 

I'll make it up to you somehow.

**Comment by tfennelly** [comment]
I think merges etc are needed for this.

Also ... can we get some real examples of what the proposed changes are hoping to enable?

**Comment by michaelneale** [comment]
is this still needed?

**Comment by michaelneale** [comment]
Closing as ancient... can bring back the goodness if needed

**Pull request closed without merging**
