### PR TITLE
JENKINS-48035: Fix to register webhook after creating and saving pipeline

### PR DESCRIPTION
**Pull request by vivek**
blueocean

# Description

See [JENKINS-48035](https://issues.jenkins-ci.org/browse/JENKINS-48035).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by halkeye** [comment]
Any way this can be unit tested to prevent it from breaking again in the future?

**Comment by vivek** [comment]
@halkeye yeah should be coming, I tried to do a mocked version to detect `GithubWebHook.registerHookFor()` is called, got some nasty power mock error. will take another look.

**Comment by vivek** [comment]
@halkeye Added unit test

**Comment by vivek** [comment]
CI is failing with `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`. @halkeye don't remember seeing it in past, do you know what might be going on or how to fix it?

**Comment by halkeye** [comment]
oh, agent-05 got re-enabled, its disabled again and should go back to the dynamic gcp ones.

**Comment by halkeye** [comment]
@vivek I'm happy.. well content to merge without the ATH passing, but i'm also ignoring the ath test that almost always fails at this point (works locally, fails on CI due to timing i think)

**Pull request merged**
