### PR TITLE
Added support for favorites for primary branches names other than "master"

### PR DESCRIPTION
**Pull request by murraybo**
* it is now possible to favorite projects with other primary branch names
  (ex. main <- githubs default) and see the correct state in all shown places
* kept current behavior with preloaded data, but added information about primary branch
* fixed some small issues related to non top level project and non pipeline projects
* removed related unused code
* added more tests

# Description
Currently the lower part of the pipeline overview is not showing the correct state for favorited pipelines with a primary branch with a name other then "master". Clicking on the the fav start leads to several error in different places and the state is not visualized correctly afterwards.

## Reviewers: 
* Create a pipeline for a project with primary branch "main" 
* try to fav/unfav it. 
* Try to fav/unfav it on the branch sub page 
* Try to fav/unfav in the pipeline header.

Maybe of interest to you:
@olamy
@jglick
@reviewbybees 

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [X] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [X] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by olamy** [comment]
@murraybo awesome it sounds like an interesting change!. Can you rebase it as there is some conflicts?

**Comment by murraybo** [comment]
> @murraybo awesome it sounds like an interesting change!. Can you rebase it as there is some conflicts?

here you go. the other pull request contained a similar but slightly different fix for the build breaker.

**Comment by olamy** [comment]
@murraybo thanks that's great. The content of PR is good but please remove what is not related to the primary focus which is support of branches names other than master. I would prefer at the end squash everything related to the feature in a single commit. 
Changes such jacoco, test classes rename and the class remove. 
I would prefer mark those classes as deprecated first then remove them in 1.25 version.
sorry for the nit picking but I would prefer keep following such rational

**Comment by murraybo** [comment]
@olamy as requested I removed all unrelated fixes and squashed all favorite related into one commit, I will open a separate pull request for the fixes

**Comment by olamy** [comment]
@murraybo thanks a lot for this contribution

**Pull request merged**
