### PR TITLE
[JENKINS-53697] 

### PR DESCRIPTION
**Pull request by runzexia**
# Description

See [JENKINS-53697](https://issues.jenkins-ci.org/browse/JENKINS-53697).

init scmSource

### CODE REVIEW

**Comment by olamy** [comment]
@runzexia I wonder if there is a way to have a unit reproducing the issue?

**Comment by runzexia** [comment]
```
curl -X PUT \
  http://127.0.0.1:8080/jenkins/blue/rest/organizations/jenkins/scm/git/validate/ \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
	"repositoryUrl":"https://github.com/jenkinsci/blueocean-plugin",
	"branch":"master",
	"requirePush":true,
	"userName":"xxxxx",
	"password":"xxxxx"
}
'
```
@olamy

**Comment by olamy** [comment]
well I mean a unit test  :)

**Comment by runzexia** [comment]
> well I mean a unit test :)

I need a git repository to perform unit test. I don't know how to add it. Do you have any suggestions?

**Comment by olamy** [comment]
@runzexia oh sure this might be complicated :)

**Pull request merged**
