### PR TITLE
[JENKINS-35890] Developer can click the commit ID on the Changes tab of the Run result screen to view the full commit details

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-35890](https://issues.jenkins-ci.org/browse/JENKINS-35890).

https://youtu.be/ONDs9iZkYwY

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes. -> https://ci.blueocean.io/job/Acceptance%20Tests%20Param/36/console

# Reviewer checklist
- [x] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
🐛 The hover style is an anchor even if there is no link
link

@scherler @michaelneale do you think its better to open in a new window or use the existing window?

**Comment by michaelneale** [comment]
@scherler shoudl the ATH run as is with this (to check against regressions) ?

**Comment by scherler** [comment]
@i386 I have added a test to only include the link if the url of the commit is set.

**Comment by scherler** [comment]
Waiting for next spot in AT build

**Comment by cliffmeyers** [comment]
@scherler @i386 I know this wasn't in the original requirements but I'm wondering if clicking the commit should open the SCM link in a new tab by default...

**Comment by cliffmeyers** [comment]
LGTM 🐝

**Pull request merged**
