### PR TITLE
Josh/checkdeps 2016 07 12

### PR DESCRIPTION
**Pull request by sophistifunk**
Related to issue #JENKINS-36555 . 

Summary of this pull request: 
Update checkdeps script to only look at production / runtime versions, and to also inspect some "blessed" first-level deps, such as JDL.

Coincidental small fix to Activity screen's blank state.

@reviewbybees

### CODE REVIEW

**Comment by sophistifunk** [comment]
This doesn't yet run checkdeps in the pipeline.

**Comment by kzantow** [comment]
:bee: don't like the node_module needs, but seems to be the common way to do things

**Comment by sophistifunk** [comment]
@kzantow the only other method would be to go out to npm.org to check, or to make assumptions about where on the filesystem those dependencies might be installed, unless I'm missing something?

**Comment by kzantow** [comment]
@sophistifunk I know, there's not a much better way AFAIK. More of a general comment, I'm not a fan of hardcoding `node_modules` paths, but it's a pretty common thing to do...

**Comment by sophistifunk** [comment]
Attempting to run in CI :D

**Comment by sophistifunk** [comment]
I ams teh pipeline mastah*

**Comment by sophistifunk** [comment]
mastah *
asterisk

**Comment by michaelneale** [comment]
Looks good @sophistifunk

**Pull request merged**
