### PR TITLE
[JENKINS-36828] fix BlueOcean Dockerfile relies on plugins deployed to UC

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by ndeloof** [comment]
@reviewbybees @michaelneale

**Comment by michaelneale** [comment]
:bee: I like it. This doesn't yet cover the dogfood case as mentioned by https://issues.jenkins-ci.org/browse/JENKINS-37141 - so we may need a different dockerfile for that? (not sure how to achieve that ones aims though)

**Comment by ydubreuil** [comment]
Agreed, this is the way is should be done. Unfortunately, I've found that plugin dependency resolution doesn't work.

I'm working on a PR for development image and I'm struggling to adapt `install-plugins.sh` to resolve dependencies correctly. I feel that it's not really possible to resolve them without walking the dependency tree, which is not really writable in Bash...  For example, I'm hitting an issue with optional dependencies. They are ignored by the script but it should be more clever. It should consider an optional dep if it is required by another plugin in a lower version.

**Comment by michaelneale** [comment]
This won't work as blue ocean is not in the main UC but the experiemental one - can this be done with the Dockerfile in its current form @ydubreuil @ndeloof 

:ant:

**Comment by ndeloof** [comment]
just need to change URL so it points to experimental

**Comment by michaelneale** [comment]
@ndeloof what url?

**Comment by ndeloof** [comment]
https://updates.jenkins-ci.org/experimental/

**Comment by michaelneale** [comment]
@ndeloof but shouldn't the Dockerfile have that in it? as it is it won't work.

**Comment by ndeloof** [comment]
yes, feel free to experiment. It worked with me, but maybe I didn't got the version you expected ? 
```
Step 3 : RUN mkdir /usr/share/jenkins/ref/plugins/ && cd /usr/share/jenkins/ref/plugins/ && install-plugins.sh blueocean
 ---> Running in 79a5311e6d54
Creating initial locks...

Analyzing war...

Downloading plugins...
Downloading plugin: blueocean from https://updates.jenkins.io/download/plugins/blueocean/latest/blueocean.hpi
 > blueocean depends on blueocean-commons:1.0-alpha-6,blueocean-rest:1.0-alpha-6,blueocean-pipeline-api-impl:1.0-alpha-6,blueocean-analytics-tools:1.0-alpha-6,blueocean-rest-impl:1.0-alpha-6,blueocean-web:1.0-alpha-6,blueocean-personalization:1.0-alpha-6,blueocean-dashboard:1.0-alpha-6
Downloading plugin: blueocean-commons from https://updates.jenkins.io/download/plugins/blueocean-commons/1.0-alpha-6/blueocean-commons.hpi
Downloading plugin: blueocean-rest from https://updates.jenkins.io/download/plugins/blueocean-rest/1.0-alpha-6/blueocean-rest.hpi
Downloading plugin: blueocean-pipeline-api-impl from https://updates.jenkins.io/download/plugins/blueocean-pipeline-api-impl/1.0-alpha-6/blueocean-pipeline-api-impl.hpi
Downloading plugin: blueocean-rest-impl from https://updates.jenkins.io/download/plugins/blueocean-rest-impl/1.0-alpha-6/blueocean-rest-impl.hpi
Downloading plugin: blueocean-analytics-tools from https://updates.jenkins.io/download/plugins/blueocean-analytics-tools/1.0-alpha-6/blueocean-analytics-tools.hpi
Downloading plugin: blueocean-web from https://updates.jenkins.io/download/plugins/blueocean-web/1.0-alpha-6/blueocean-web.hpi
Downloading plugin: blueocean-personalization from https://updates.jenkins.io/download/plugins/blueocean-personalization/1.0-alpha-6/blueocean-personalization.hpi
Downloading plugin: blueocean-dashboard from https://updates.jenkins.io/download/plugins/blueocean-dashboard/1.0-alpha-6/blueocean-dashboard.hpi
 > blueocean-rest depends on blueocean-commons:1.0-alpha-6,blueocean-web:1.0-alpha-6
 > blueocean-rest-impl depends on blueocean-rest:1.0-alpha-6,mailer:1.13,favorite:1.16,token-macro:1.12.1,scm-api:1.2
Downloading plugin: mailer from https://updates.jenkins.io/download/plugins/mailer/1.13/mailer.hpi
Downloading plugin: favorite from https://updates.jenkins.io/download/plugins/favorite/1.16/favorite.hpi
Downloading plugin: token-macro from https://updates.jenkins.io/download/plugins/token-macro/1.12.1/token-macro.hpi
Downloading plugin: scm-api from https://updates.jenkins.io/download/plugins/scm-api/1.2/scm-api.hpi
 > blueocean-pipeline-api-impl depends on workflow-job:2.3,scm-api:1.1,workflow-step-api:2.1,blueocean-rest-impl:1.0-alpha-6,workflow-api:2.1,workflow-support:2.1,github-branch-source:1.8.1,workflow-cps:2.8,git:2.4.2,workflow-multibranch:2.8,workflow-durable-task-step:2.0
...
```

**Comment by michaelneale** [comment]
@ndeloof but where is the url set to update to the experimental update center? can you change the dockerfile to reflect that?

**Comment by michaelneale** [comment]
Closing this in favour of #403

**Pull request closed without merging**
