### PR TITLE
Task/jenkins 37323

### PR DESCRIPTION
**Pull request by vivek**
# Description

See https://issues.jenkins-ci.org/browse/JENKINS-37323

* Create a pipeline job with stage as blocks, example here, https://gist.github.com/vivek/706b28a614b01df32fd5632522f3668d
* Run, check visualization, logs etc. of this job inside BO UI

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

Running locally is failing to parse update-center.html file. It worked until this morning and is failing since I pulled latest changes on ATH workspace. @tfennelly @scherler do you know whats going on here?

`Failed tests:   nightwatchTestRun(io.jenkins.blueocean.AllTest): Failed to parse update center   data of https://updates.jenkins-ci.org/update-center.json.html at /var/folders/5q/51y3qf0x5t39d4c4c_c2l1s40000gn/T/update-center.json.html`

# Reviewer checklist
- [x] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
Nice work @vivek !

This is worth a bee IF it can pass the ATH. I know @cliffmeyers was able to run it since beta was released so this may be something else, but I will talk to tom later. 

cc @scherler can you run ATH over this branch as well?

**Comment by michaelneale** [comment]
That ATH thing should be temporary, @scherler is trying it on this branch.

**Comment by scherler** [comment]
@michaelneale I applied the new syntax on local AT but that makes the stage.js to fail, the problem is that the steps are not showing up anymore. Will investigate.

**Comment by scherler** [comment]
Fixed it and updated the AT. https://github.com/jenkinsci/blueocean-acceptance-test/compare/JENKINS-37323?expand=1

**Comment by michaelneale** [comment]
@scherler the old syntax has to work too btw. So don't need to change it to new in the ATH yet.

**Comment by michaelneale** [comment]
@scherler so this passes with ATH master now? (We don't need to update the ATH to new syntax yet, as both old and new should work)

**Comment by michaelneale** [comment]
@vivek @scherler pushed a change to master of ATH that should pass against it. Also, he has a branch: https://github.com/jenkinsci/blueocean-acceptance-test/pull/30 that tests with the new syntax (if you think that is a good idea?) - if you are comfortable this passes for you, then I think we should 🐝  this and move ahead.

**Comment by vivek** [comment]
@michaelneale Merged latest master to this branch. ATH master runs fine. ATH JENKINS-37323 branch (with pipeline script with new stages) works fine as well. I need bee to merge this change.

**Comment by michaelneale** [comment]
:bee: :bee: :bee:
:bee: :bee: :bee:
:bee: :bee: :bee:
:bee: :bee: :bee:
:bee: :bee: :bee:
:bee: :bee: :bee:

**Pull request merged**
