### PR TITLE
Experiment/better hipchat message

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- Differentiating between builds that failed and those that were aborted.

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
@michaelneale different text / color in hipchat room when a build is aborted.

**Comment by i386** [comment]
@cliffmeyers for added effect, use `${env.RUN_DISPLAY_URL}` for the URL - it will default to Blue Ocean

**Comment by cliffmeyers** [comment]
cc @michaelneale you ok with merging this one in? It seemed like a nice improvement. Just wanted confirmation as I don't want to be flippant w/ changes to the `Jenkinsfile`

**Comment by michaelneale** [comment]
yas, as long as it all works! sure LGTM

**Pull request merged**
