### PR TITLE
Feature/pushstageevent

### PR DESCRIPTION
**Pull request by nidve01**

### CODE REVIEW

**Comment by i386** [comment]
HI @nidve01,

Thanks for contributing! Be sure to read our [Contribution Guide](https://github.com/jenkinsci/blueocean-plugin/blob/master/CONTRIBUTING.md) before we can review this PR.

Also, we'd need to get an idea of what the intention of this PR is. Could you update the description of what these changes do?

Thanks,
James

**Comment by nidve01** [comment]
@vivek 

Thanks for the comment. I was playing around with the code and not intended to push these change. You may ignore this Pull request. Im closing this down right away. Thanks!!

**Comment by i386** [comment]
@nidve01 we're always looking for contributors! So don't be a stranger :)

**Comment by nidve01** [comment]
Sure. Thanks!

**Pull request closed without merging**
