### PR TITLE
[JENKINS-47286] Adding translation for common.state.skipped

### PR DESCRIPTION
**Pull request by jsoref**
# Description

See [JENKINS-47286](https://issues.jenkins-ci.org/browse/JENKINS-47286).

image

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by halkeye** [comment]
@jsoref since the ticket doesn't really show the issue. Do you want to create a new ticket, or describe how to reproduce this exactly? (I assume declarative pipeline with a when? but do you have an example).

**Comment by jsoref** [comment]
Yeah, we have a step with
```
when {
branch "master"
expression {
env.something == true
}
}
``|

**Comment by halkeye** [comment]
@jsoref can you rebase with master?
(git fetch origin; git rebase origin/master)

We've been fixing up the test suite and I want to see green now before we merge.

**Comment by halkeye** [comment]
thank you @jsoref

**Pull request merged**
