### PR TITLE
[JENKINS-35854] Report Javascript exceptions to rollbar.com

### PR DESCRIPTION
**Pull request by imeredith**
This PR includes:
* The rollbar.com tracking javascript
* Data is only collected if usage statistics collection is enabled
* Anonymises IP addresses (sets them all to `0.0.0.0`)
* People tracking is off in rollbar by default

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
@imeredith is this ready for review? 

@i386 how reasonable is it for OSS to be posting to a non OSS service? (obviously is opt in, but I expect some resistance for this).

**Comment by i386** [comment]
deploy to staging

**Comment by i386** [comment]
deploy on sandbox

**Comment by i386** [comment]
@imeredith I rebased this and stopped it sending back IP addresses to rollbar (all requests are reported as `0.0.0.0`)

**Comment by i386** [comment]
This is what a rollbar payload looks like as sent from the browser

```
{
   "access_token":"81f3134dedf44871b9cc0a347b1313df",
   "data":{
      "environment":"production",
      "endpoint":"https://api.rollbar.com/api/1/",
      "uuid":"2cfb939c-5f88-45bb-e84e-df531adcdb5d",
      "level":"error",
      "platform":"browser",
      "framework":"browser-js",
      "language":"javascript",
      "body":{
         "message":{
            "body":"bae"
         }
      },
      "request":{
         "url":"http://localhost:8080/jenkins/blue/pipelines/",
         "query_string":"",
         "user_ip":"0.0.0.0"
      },
      "client":{
         "runtime_ms":5589,
         "timestamp":1466560297,
         "javascript":{
            "browser":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36",
            "language":"en-US",
            "cookie_enabled":true,
            "screen":{
               "width":2560,
               "height":1440
            },
            "plugins":[
               {
                  "name":"Shockwave Flash",
                  "description":"Shockwave Flash 22.0 r0"
               },
               {
                  "name":"Widevine Content Decryption Module",
                  "description":"Enables Widevine licenses for playback of HTML audio/video content. (version: 1.4.8.885)"
               },
               {
                  "name":"Chrome PDF Viewer",
                  "description":""
               },
               {
                  "name":"Native Client",
                  "description":""
               },
               {
                  "name":"Chrome PDF Viewer",
                  "description":"Portable Document Format"
               }
            ]
         }
      },
      "server":{

      },
      "notifier":{
         "name":"rollbar-browser-js",
         "version":"1.9.1"
      }
   }
}
```

**Comment by i386** [comment]
@imeredith this looks good to me but lets hold before sending this off. Need to email Jenkins Infra and check what we have done here is Kosher.

**Comment by i386** [comment]
No one has had any major objections so this can be merged

http://lists.jenkins-ci.org/pipermail/jenkins-infra/2016-June/000776.html

**Pull request merged**
