### PR TITLE
Bump dependency to Jenkins 2.7.3

### PR DESCRIPTION
**Pull request by i386**
# Description

We should bump the dependency to the latest LTS for the beta release

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees @vivek

### CODE REVIEW

**Comment by michaelneale** [comment]
@vivek thoughts on this?

**Comment by vivek** [comment]
@michaelneale Looks fine to me. @i386 have you run ATH against it? I can also run after I am done testing other PRs.

**Comment by vivek** [comment]
@michaelneale we also need this bump as Kyoto requires 2.7.1, needed for https://issues.jenkins-ci.org/browse/JENKINS-37744 is going to package kyoto plugin

**Comment by vivek** [comment]
@i386 can you merge latest master and push the merge? Many changes there.

**Comment by michaelneale** [comment]
@vivek why not close this and open a branch for https://issues.jenkins-ci.org/browse/JENKINS-37744 with both the Bundled kyoto and bumped to LTS dep?

**Comment by michaelneale** [comment]
Closing this as @vivek will open it with pipeline model bundled for review

**Pull request closed without merging**
