### PR TITLE
when a run is not replayable then do not show the replay button

### PR DESCRIPTION
**Pull request by i386**
# Description

When a run is not replayable then do not show the replay button

# Testing instructions
Start and stop a pipeline build very quickly and the run will be unplayable (this happens before Pipeline can store flow nodes). Increase your chances by making the number of executors zero.

The run should not have a rerun button.

See [JENKINS-42997](https://issues.jenkins-ci.org/browse/JENKINS-42997).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

PTAL @imeredith @cliffmeyers

### CODE REVIEW

**Comment by i386** [comment]
Tracked down the problem that was causing the ATH to fail

**Comment by michaelneale** [comment]
update this to master pls

**Comment by i386** [comment]
ATH running https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/2204/

**Comment by michaelneale** [comment]
actually, update to master when https://github.com/jenkinsci/blueocean-plugin/pull/987 is merged

**Comment by i386** [comment]
I had the ATH pass https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/2204/

**Comment by michaelneale** [comment]
nice - I'll take a look at this soon ideally if we wait for: https://github.com/jenkinsci/blueocean-plugin/pull/839 that would be nice ...

**Comment by i386** [comment]
@michaelneale remerged this with master after #839 landed

**Comment by michaelneale** [comment]
worth updating this to master again?

**Comment by i386** [comment]
@michaelneale it already is (1 hour ago)

**Comment by michaelneale** [comment]
ATH (latest) works nicely - but I would like @cliffmeyers to OK this one

**Comment by michaelneale** [comment]
seems to work as advertised, so up to @cliffmeyers - LGTM

**Comment by i386** [comment]
@cliffmeyers can you please eyeball this one again?

**Comment by cliffmeyers** [comment]
@i386 looked at the commits since I last approved and do not see anything that looks off. I also did a quick skim of the full set of changes and still LGTM 👍

**Comment by michaelneale** [comment]
can we hold off on this to give https://github.com/jenkinsci/blueocean-plugin/pull/962 a chance to get in for @sophistifunk ?

**Comment by i386** [comment]
@michaelneale sure :(

**Pull request merged**
