### PR TITLE
[JENKINS-43507] Binary compatibility test for branch source: plugin upgrade only, no API changes, on release branch

### PR DESCRIPTION
**Pull request by stephenc**
# Description

See [JENKINS-43507](https://issues.jenkins-ci.org/browse/JENKINS-43507).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by stephenc** [comment]
This is #1186 backported to 1.1.0-release

**Comment by michaelneale** [comment]
tested locally and passed ATH in another branch I tried the same thing so LGTM!

**Comment by i386** [comment]
That is awesome! Nice work @stephenc 👍

**Comment by michaelneale** [comment]
the one I tried: https://ci.blueocean.io/blue/organizations/jenkins/blueocean/detail/temp%2F1.1.0-release-branchapi-testing/2/pipeline which is: https://github.com/jenkinsci/blueocean-plugin/tree/temp/1.1.0-release-branchapi-testing

**Comment by michaelneale** [comment]
yep - ok from my PoV - binary compat is 👌🏽

nice one @stephenc

**Comment by michaelneale** [comment]
@stephenc are there new alphas/betas out there to try?

**Comment by stephenc** [comment]
Yeah... -alpha-4 I'll see if I can update if you have the spare cycles to test

**Comment by michaelneale** [comment]
nice @stephenc I did a full retest of this, and it seems good. No more warnings etc... so this is 👍🏻 from me.

**Comment by michaelneale** [comment]
beta1 passes ATH - and I manually retested - and it seems good. 

I opened a github org folder config I had created via blue ocean and saved it I see a warning in the log: 
```
Jul 06, 2017 2:33:18 PM hudson.model.Descriptor$NewInstanceBindInterceptor onConvert
WARNING: falling back to default instantiation jenkins.scm.api.trait.SCMTrait {"credentialsId":"github","stapler-class":"org.jenkinsci.plugins.github_branch_source.SSHCheckoutTrait","$class":"org.jenkinsci.plugins.github_branch_source.SSHCheckoutTrait"}
java.lang.NullPointerException
	at hudson.model.Descriptor$NewInstanceBindInterceptor.onConvert(Descriptor.java:661)
```

but no ill happened. I was able to add another pipeline via BO and it saved the pattern, no build rework happened etc. So I think it is an ignorable warning? If so - this is LGTM

**Comment by stephenc** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-45331 for the NPE (harmless but scary)

**Pull request closed without merging**
