### PR TITLE
JENKINS-46070 PR page broken on dogfood

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

* Fix an issue passing translate function to child components

See [JENKINS-46070](https://issues.jenkins-ci.org/browse/JENKINS-46070).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
I'm still confused as to why this didn't fail ATH :-/

**Comment by i386** [comment]
@imeredith do we not have ATH coverage for this page?

**Comment by NicuPascu** [comment]
LGTM, I totally agree with this way of passing the props along compared with the "..." way, this way is a lot clearer. And regarding the ATH, is it possible to fail the build if there is any JS error in the console? That would have caught this, don't know if it is possible though. :bee:

**Comment by sophistifunk** [comment]
It's not just that using the `...` is ugly for a single property, but it was also incorrect, which is the main reason I changed it when I noticed. It was `{...t}` which will explode `t` and use its enumerables as props. When you just want the same meaning as `t={t}` the syntax is `{..{t}}`

**Comment by sophistifunk** [comment]
Oh sure, ATH fails when I *fix* stuff :)

**Comment by sophistifunk** [comment]
@i386 @imeredith there's definitely coverage for PR tab, there must be something peculiar to the environment or the limited repos used for the tests that causes the `RunHistoryButton` to not render. Maybe it's only ever exercised for "virgin" pipelines that have never run, or the user does not have the permission.

**Pull request merged**
