### PR TITLE
hotfix/time harmonizer defend npe

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- Defend against the function not being made available on `context.config` - this was breaking storybooks in personalization, and also requires some mocking in `PipelineCard-spec` that would be nice to avoid.

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by cliffmeyers** [comment]
cc @scherler 

I have a larger question which is why we are passing this function down in the React context? Couldn't we just export the function from `core-js`? And let `blueocean-web` import it and set the skew value in appropriate place? Then we wouldn't have to worry about mocking it out in different places, or worry about it being null.

**Comment by michaelneale** [comment]
:bee:

**Comment by scherler** [comment]
@cliffmeyers https://github.com/jenkinsci/blueocean-plugin/blob/master/blueocean-core-js/src/js/config.js in there yeah makes lot of sense

**Comment by michaelneale** [comment]
any change this fixes this one? https://issues.jenkins-ci.org/browse/JENKINS-42318

**Comment by michaelneale** [comment]
@cliffmeyers looks like this one is worth it (no biggie)

**Comment by cliffmeyers** [comment]
@michaelneale looking at the code that produces that error message, I don't think it's related to this change. The error this was fixing was mostly coming up in a unit test or storybook environment if I recall. It would probably be better to make the broader fix discussed above once higher priority items get wrapped up.

**Comment by michaelneale** [comment]
@cliffmeyers SGTM

**Comment by michaelneale** [comment]
still seeing harmonizer errors - so this and more is still relevant IMO

**Comment by cliffmeyers** [comment]
@michaelneale if we merge this now, that's fine, but let's add a ticket to describe the better fix and slap it into the tech debt epic? If you agree w/ that approach, I'll make the ticket later today and the merge this sucker.

**Comment by michaelneale** [comment]
@cliffmeyers we can leave this if you like - just ensure there is a labelled ticket for it. 
@scherler may have some changes making this irrelevant anyway, so I think can close this but keep a link to the branch behind it in the ticket.

**Comment by michaelneale** [comment]
Closing this - feel free to resurrect one day if important (just too many olde PRs hanging around)

**Pull request closed without merging**
