### PR TITLE
[JENKINS-45766] Cherry pick organisation fixes from 1.1.0-release branch

### PR DESCRIPTION
**Pull request by vivek**
Cherry picked organization related fixes from 1.1.0-release branch: https://github.com/jenkinsci/blueocean-plugin/commit/a4fdb665ff6599140e618f22c04b3511bafe0509.

See [JENKINS-45766](https://issues.jenkins-ci.org/browse/JENKINS-45766).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
a lot of failed unit tests: 

```
Failed tests: 
  GithubApiTest.fetchExistingCredentialScopesInvalid:75->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubApiTest.fetchExistingCredentialTokenInvalid:57->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubApiTest.getOrganizationsAndRepositories:93->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubApiTest.validateGithubToken:29->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubOrgFolderPermissionsTest.canCreateWhenHavePermissionsOnCustomOrg:64->createGithubOrgFolder:78->createGithubCredential:117 428 expected:<200> but was:<428>
  GithubOrgFolderPermissionsTest.canCreateWhenHavePermissionsOnDefaultOrg:43->createGithubOrgFolder:78->createGithubCredential:117 428 expected:<200> but was:<428>
  GithubOrgFolderPermissionsTest.canNotCreateWhenHaveNoPermissionOnCustomOrg:74->createGithubOrgFolder:78->createGithubCredential:117 428 expected:<200> but was:<428>
  GithubOrgFolderPermissionsTest.canNotCreateWhenHaveNoPermissionOnDefaultOrg:53->createGithubOrgFolder:78->createGithubCredential:117 428 expected:<200> but was:<428>
  GithubOrgFolderTest.createGithubOrgTest:98->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubOrgFolderTest.createGithubOrgTest:98->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubOrgFolderTest.orgUpdateTest:169->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubOrgFolderTest.orgUpdateTest:169->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubOrgFolderTest.orgUpdateWithPOSTTest:126->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubOrgFolderTest.orgUpdateWithPOSTTest:126->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubOrgFolderTest.simpleOrgTest:67->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubOrgFolderTest.simpleOrgTest:67->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubScmContentProviderTest.getContentForMbp:59->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubScmContentProviderTest.getContentForOrgFolder:44->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubScmContentProviderTest.saveContentToMbp:109->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubScmContentProviderTest.saveContentToMbpMissingBranch:144->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
  GithubScmContentProviderTest.saveContentToOrgFolder:76->GithubMockBase.createGithubCredential:105 428 expected:<200> but was:<428>
```

**Comment by michaelneale** [comment]
@vivek having trouble getting this build healthy - second try was a different failure related to unit tests (the ATH failure - known intermittent) so may need a closer look...

**Comment by michaelneale** [comment]
:bee: finally! yaya @vivek

**Comment by kzantow** [comment]
Just a note... I'd avoid cherry-picking stuff as much as possible. But I'm sure you already know the ramifications, so 👍

**Comment by michaelneale** [comment]
@kzantow yeah not often used - but in this case it seems the best way to get a change from 1.1.5 across to master right? (that won't otherwise come across clean?) - do you have specific reasons? (I don't git well)

**Comment by michaelneale** [comment]
there was a minor conflict with the scm changes - see how this merge goes @vivek and take a look in the morning ;)

**Comment by michaelneale** [comment]
@vivek there may be a legit test failure `getPipelineWihoutNodesAllStepsTest – io.jenkins.blueocean.rest.impl.pipeline.PipelineNodeTest
` will see if a re-run shows it

**Pull request merged**
