### PR TITLE
Remove snake yaml dependency

### PR DESCRIPTION
**Pull request by olamy**
- Upgrade to snakeyaml 2.0
- use uap new maven coordinates

# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by olamy** [comment]
well. snakeyaml is used only to parse `User-Agent` and to collect some analytics data such:
- browserFamily
- browserVersionMajor
- browserVersionMinor
- osFamily
- osVersionMajor
- osVersionMinor

does someone really care of those data?

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
> well. snakeyaml is used only to parse User-Agent and to collect some analytics data such:

no

**Comment by olamy** [comment]
classes which need snake yaml removed

**Review by timja — APPROVED** [review]

**Review by car-roll — APPROVED** [review]

**Comment by timja** [comment]
Could this be released please?

**Comment by olamy** [comment]
> Could this be released please?

Please just wait a few more days. The release is yet ready. Still needs some issues to figure out.

**Pull request merged**
