### PR TITLE
Organization display name not serialized correctly 

### PR DESCRIPTION
**Pull request by i386**
# Description

See [JENKINS-44538](https://issues.jenkins-ci.org/browse/JENKINS-44538).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
@alvarolobato @vivek ping

**Comment by michaelneale** [comment]
WTF is up with this scary failure: https://ci.blueocean.io/blue/organizations/jenkins/blueocean/detail/bug%2FJENKINS-44538/1/pipeline cc @vivek - I have seen that on other branches. Did a dependency change recently that has caused pipeline or REST to be more problematic?

**Comment by michaelneale** [comment]
@vivek the error: 

```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: {
  "message" : "Stage 11 not found in pipeline pipeline1.",
  "code" : 404,
  "errors" : [ ]
}; line: 1, column: 1]
	at io.jenkins.blueocean.rest.impl.pipeline.PipelineBaseTest.get(PipelineBaseTest.java:142)
	at io.jenkins.blueocean.rest.impl.pipeline.PipelineBaseTest.get(PipelineBaseTest.java:120)
	at io.jenkins.blueocean.rest.impl.pipeline.PipelineBaseTest.get(PipelineBaseTest.java:111)
	at io.jenkins.blueocean.rest.impl.pipeline.PipelineNodeTest.testBlockedStep(PipelineNodeTest.java:1955)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.jvnet.hudson.test.JenkinsRule$2.evaluate(JenkinsRule.java:533)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: 
```

I swear I have seen that elsewhere just recently.

**Comment by michaelneale** [comment]
worried about those earlier failures, something is rotten in pipeline

**Comment by vivek** [comment]
@michaelneale This test was added recently as part of test coverage, it has timing component to it, although there is check to avoid that but there is something that makes it flaky. I am looking in to it.

**Comment by michaelneale** [comment]
@i386 that test failure doesn't look transient: 

```
organizationUsers – io.jenkins.blueocean.service.embedded.OrganizationApiTest
a few seconds
Error
expected:<null> but was:<alice@example.com>
```

**Comment by michaelneale** [comment]
:bee: in that case

**Comment by alvarolobato** [comment]
Thanks @i386 for the change.

**Comment by i386** [comment]
@alvarolobato you're welcome.

**Pull request merged**
