### PR TITLE
bug/JENKINS-44107-moar-commit-lozenge * Round off the commit lozenge …

### PR DESCRIPTION
**Pull request by sophistifunk**
…a bit less, since it's only 18px high

# Description

See [JENKINS-44107](https://issues.jenkins-ci.org/browse/JENKINS-44107).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
screen shot 2017-06-21 at 3 37 46 pm

**Comment by michaelneale** [comment]
up to @i386

**Comment by i386** [comment]
Still sharp :( https://cl.ly/380N10282f1b

**Comment by michaelneale** [comment]
Sharp is good if you are snoop

**Comment by sophistifunk** [comment]
screen shot 2017-06-22 at 9 02 05 am

Squircle mode

**Comment by michaelneale** [comment]
hrm https://twitter.com/loveskuchen/status/877676580415209472

**Comment by sophistifunk** [comment]
I'm going to the pub. I don't care what time it is, dad.

**Comment by michaelneale** [comment]
@sophistifunk needs moaar sandpaper

**Comment by michaelneale** [comment]
@i386 is https://cl.ly/380N10282f1b what is is meant to be?

**Comment by michaelneale** [comment]
@i386 needs more input from you - but not sure what @sophistifunk is asking. These were never correct

**Pull request closed without merging**
