### PR TITLE
JENKINS-42865: white-space:nowrap log line numbers

### PR DESCRIPTION
**Pull request by imeredith**
See example here that the 1px fixes https://ci.blueocean.io/blue/organizations/jenkins/blueocean/detail/PR-1095/3/pipeline/#step-29-log-1087

# Description

See [JENKINS-42865](https://issues.jenkins-ci.org/browse/JENKINS-42865).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
@imeredith I suspect there is an open ticket for this in the Log Improvments epic

**Comment by imeredith** [comment]
@i386 cheers, was bugging me so I fixed it w/o looking at jira

**Comment by i386** [comment]
Thanks for being proactive :)

I had noticed this one again on Friday so good to see a fix

**Comment by michaelneale** [comment]
:bee:

**Pull request merged**
