### PR TITLE
FIX-Jenkins-41341 standardize form descriptions

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-41341](https://issues.jenkins-ci.org/browse/JENKINS-41341).
screenshot from 2017-02-08 22-04-59
screenshot from 2017-02-08 22-44-10

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
This looks great to me. @brody can you please review?

**Comment by brody** [comment]
pasted_image_9_2_17__11_00_am

Lots of small tweaks around size & spacing.
- Text box, text area & dropdowns should be full width
- Max-width of 400px
- Spacing between labels and form elements are a little off. I'll add a redline version of the mock up to visually show spacing

form spacing

**Comment by michaelneale** [comment]
Mocha test failures - odd (same happend to keith - must have been some change in master, as master builds).

**Comment by scherler** [comment]
@brody I am confused https://issues.jenkins-ci.org/secure/attachment/35770/35770_Pasted_Image_6_2_17__12_21_pm.png here you use a thin line after the label. 

https://app.zeplin.io/project.html#pid=57eb0b8835431a24309f0d6d&sid=57f44383bcb58ed62c8b07c6 here I do not find none like in the above image.

Or do youi only want those lines only under certain circumstances?

**Comment by scherler** [comment]
screenshot from 2017-02-10 23-30-51
screenshot from 2017-02-10 23-30-21

**Comment by michaelneale** [comment]
@brody @i386 ^?

**Comment by michaelneale** [comment]
Lovely work @scherler - brody has blessed. :bee: and passes ATH

**Pull request merged**
