### PR TITLE
Ignore ... for Thor (that rhymes :) )

### PR DESCRIPTION
**Pull request by tfennelly**
IGNORE ... for @scherler only !!!

### CODE REVIEW

**Comment by michaelneale** [comment]
I look at this. Will anything bad happen to me now?

**Comment by i386** [comment]
1427290281-giphy

**Comment by scherler** [comment]
ROFL we are freaks!!! @tfennelly many thanks!

**Comment by scherler** [comment]
I merged by hand so closing this PR because I am using another branch

**Comment by scherler** [comment]
I merged by hand so closing this PR because I am using another branch

**Pull request closed without merging**
