### PR TITLE
Changed PowerMock Ignore due to a comflict with SSLSocketFactory

### PR DESCRIPTION
**Pull request by joseblas**
# Description

This is a PR for fixing a PCT problem with SSLSocketFactory and PowerMockIgnore

### CODE REVIEW

**Review by dwnusbaum — APPROVED** [review]
Looks fine, but which tests is this fixing? Is it these ones?

```
io.jenkins.blueocean.blueocean_bitbucket_pipeline.server.BitbucketServerEndpointTest.createThenDelete
io.jenkins.blueocean.blueocean_bitbucket_pipeline.server.BitbucketServerEndpointTest.should404OnDeleteNonexistent
```

**Comment by joseblas** [comment]
exactly. There is another PR from @jglick ignoring them, so I do not know which approach is better

**Comment by jglick** [comment]
compare #2098

**Review by jglick — COMMENTED** [review]
Great if it works. I suspected this was the right fix, but I did not manage to run this test in PCT, or did not manage to reproduce the failure (cannot recall which at the moment).

**Pull request merged**
