### PR TITLE
Update Pull Requests view to new tables

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

See [JENKINS-41833](https://issues.jenkins-ci.org/browse/JENKINS-41833).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
screen shot 2017-07-04 at 3 06 38 pm

**Comment by i386** [comment]
Looking good @sophistifunk. Think you could give a bit more space to the author column? almost double the width then 👌

**Comment by sophistifunk** [comment]
screen shot 2017-07-04 at 7 15 34 pm

**Comment by sophistifunk** [comment]
Pls merge this if you're happy with the updated widths, @i386

**Comment by i386** [comment]
Looks great mate.

**Pull request merged**
