### PR TITLE
Use InputStepExecution.proceed()

### PR DESCRIPTION
**Pull request by vivek**
Results in removing copy and paste code from InputStepExecution.

Follow up of PR https://github.com/jenkinsci/pipeline-input-step-plugin/pull/17.
# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
@vivek is this still needed in light of: https://github.com/jenkinsci/pipeline-input-step-plugin/pull/15 ?

**Comment by vivek** [comment]
It's orthogonal, cleans up copied code.

**Comment by michaelneale** [comment]
can't find the 2.7 snapshot of the library

**Comment by vivek** [comment]
@michaelneale yeah, will change this value once its merged upstream and released

**Comment by michaelneale** [comment]
@vivek  2.7 has been cut, should be available soon.

**Comment by vivek** [comment]
@michaelneale yeah but this PR needs https://github.com/jenkinsci/pipeline-input-step-plugin/pull/17 to be merged.

**Comment by michaelneale** [comment]
ah ok

**Comment by michaelneale** [comment]
still needed?

**Comment by i386** [comment]
I suspect this can be closed out as the problem was fixed in `pipeline-input-plugin`

**Pull request closed without merging**
