### PR TITLE
[JENKINS-45847] Dynamic ExtensionPoint registration/removal

### PR DESCRIPTION
**Pull request by tfennelly**
# Description

To support unknown ExtensionPoints - removed or added. This can happen when when using hosted UI assets.

See [JENKINS-45847](https://issues.jenkins-ci.org/browse/JENKINS-45847).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by tfennelly** [comment]
@michaelneale The ATH failures on this PR ... I'm also getting the same/similar failures against master running locally.

**Comment by tfennelly** [comment]
Hmmm ... ATH runs working now for both this PR and the https://ci.blueocean.io/job/blueocean/job/tf-zapme-now-test/ branch, so not sure what that was about.

**Comment by michaelneale** [comment]
nice one @tfennelly - some of the live ATH tests can be a bit tetchy (working on that, used to be worse) - if this is updated to a recent master there should be more tolerances built in, but the good news is this gets a green tick. 

Looks nice - will get @sophistifunk to take a quick look today as this looks important and useful.

**Comment by sophistifunk** [comment]
So as I understand it this is just to allow extensions to be registered for extensionpoints that haven't yet been requested? 

If so, LGTM 🐝

**Comment by michaelneale** [comment]
LGTM when updated - :bee:

**Comment by michaelneale** [comment]
it turns out it is a bad week for the npm shrinkwrap/package.json dance 😢

**Comment by michaelneale** [comment]
hey @tfennelly how up to date is this with master?

**Comment by kzantow** [comment]
Is this still needed? If so, could you resolve the conflicts?

**Comment by tfennelly** [comment]
Yes it's still needed. I'll update and try the build again.

**Pull request merged**
