### PR TITLE
JENKINS-48868# Dashboard page load performance fix

### PR DESCRIPTION
**Pull request by vivek**
Run actions can be expensive and not needed in pipeline API response. These
are available as part of Run API where each run object returns all
associated actions.

# Description

See [JENKINS-48868](https://issues.jenkins-ci.org/browse/JENKINS-48868).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by vivek** [comment]
@kzantow PTAL. This narrows down latestRun response to only whats needed by UI, removes few things that only activity and run details page need.

**Comment by michaelneale** [comment]
nice @vivek - running again to see if those failures are spurious (they are all in same area... so not clear yet)

**Comment by vivek** [comment]
ATH failures were legit. The returned run summary were supposed to have right capabilities. I think it should all be good now.

**Comment by michaelneale** [comment]
Nice one @vivek. tight code! this is a very nice improvement. :bee: :bee: :bee: :bee: from me

**Pull request merged**
