### PR TITLE
JENKINS-43748 remove "no steps" message

### PR DESCRIPTION
**Pull request by i386**
# Description

See [JENKINS-43748](https://issues.jenkins-ci.org/browse/JENKINS-43748).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
they don't actually bother me too much TBH... so I am ambivalent. I don't notice.

**Comment by michaelneale** [comment]
I still don't see the flashing of this... ar eyou sure? 

also if you update to master it will trigger a new build and it should be ok now

**Comment by michaelneale** [comment]
oh - you don't want this one?

**Comment by i386** [comment]
Nope I am going to think about it a bit more.

**Pull request closed without merging**
