### PR TITLE
[JENKINS-46879] Check permissions against the item for 1.2

### PR DESCRIPTION
**Pull request by vivek**
…  is in (#1393)

Backport of PR #1393 to release/1.2

* [JENKINS-46879] Check permissions against the item where the pipeline is in

* [JENKINS-46879] Fix failing test

# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by vivek** [comment]
@alvarolobato  PTAL. Its direct cherry pick from master, can merge once build is green.

**Comment by michaelneale** [comment]
:bee: when green  - and then may as well cut a release

**Comment by michaelneale** [comment]
hrm this may be failing due to : https://ci.blueocean.io/job/blueocean/job/JENKINS-46879_scm-permission-1.2/1/artifact/acceptance-tests/target/screenshots/io.blueocean.ath.live.GithubEditorTest_testEditor.png

**Comment by michaelneale** [comment]
yeah this is still a 🐛  - it is lacking some permission check to re-open the editor. 
The difference with master is github org folders are in use here - I wonder if there is a parent/cascading issue.

**Comment by michaelneale** [comment]
@vivek @alvarolobato given this is not a security issue - and it is applied in 1.3 (master), would you consider this not be accepted for 1.2.2 but as an enhancement coming in 1.3?

**Comment by alvarolobato** [comment]
@michaelneale  the problem is that this is the real change we need in. Because checking against root Jenkins Root makes other things fail.

**Comment by alvarolobato** [comment]
I don't get why is failing here I'm running locally

**Comment by michaelneale** [comment]
I saw failure locally with Hpi run. If CI is green means is good though. Happily ATH picks this up.

**Pull request merged**
