### PR TITLE
Add support for ANSI colour codes in logs

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

See [JENKINS-41200](https://issues.jenkins-ci.org/browse/JENKINS-41200).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [X] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
screen shot 2017-08-15 at 11 40 45 am

**Comment by sophistifunk** [comment]
Test pipeline https://github.com/sophistifunk/technicolor-pipeline

**Comment by sophistifunk** [comment]
@i386 I'm guessing you might wanna tweak the colours in the CSS, feel free to push changes to this branch if you like.

**Comment by sophistifunk** [comment]
Got some lint issues to fix

**Comment by i386** [comment]
@sophistifunk perhaps use our brand colours if not using them already? otherwise LGTM

**Comment by i386** [comment]
Nice 💯

**Comment by ssbarnea** [comment]
LGTM! .... bringing back the colors to the console. Once this goes in I may be able to promote the BlueOcean internally.

**Comment by sophistifunk** [comment]
screen shot 2017-08-15 at 10 55 00 pm

Update with BO theme colours /ping @i386

**Comment by i386** [comment]
This is looking quite good @sophistifunk. From a design PoV 🐝. Would be good to get some reviews from devs.

**Pull request merged**
