### PR TITLE
[FIX JENKINS-37166] - update test result console style

### PR DESCRIPTION
**Pull request by kzantow**
# Description

See [JENKINS-37166](https://issues.jenkins-ci.org/browse/JENKINS-37166).

Mostly a CSS change, didn't bother with a test. Just go look at the test results to verify.

NOTE: I used smaller font sizes than the ticket called for, they were too large, looked bad and quickly caused wrapping on the simple example I have in the screenshot.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] ~~Ran Acceptance Test Harness against PR changes.~~

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

image

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
🐛 based on that screenshot the gutter is not right.

Also, why is the header "New failing - 4" not flush to the left of the console log?

ad94646e-7538-11e6-9983-5c67d17c7de5

**Comment by kzantow** [comment]
@i386 whoops, check the updated screenshot

**Comment by i386** [comment]
🐝 🐝 🐝 🐝 🐝 looks great

**Comment by michaelneale** [comment]
:bee: (but haven't tried it)

**Comment by sophistifunk** [comment]
Code looks good to me 🐝

**Pull request merged**
