### PR TITLE
JENKINS-39627 Alignment of cog is off on Result 

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

See [JENKINS-39627](https://issues.jenkins-ci.org/browse/JENKINS-39627).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [x] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by sophistifunk** [comment]
screen shot 2016-11-14 at 11 09 30 am

**Comment by i386** [comment]
LGTM

**Comment by sophistifunk** [comment]
NFI why that build failed, I don't see anything resembling an error message when I click the "details" link.

**Comment by michaelneale** [comment]
@sophistifunk good old eslint errors - your favourite I know. 

```
[INFO] /home/ubuntu/slave/workspace/NKINS-39627-buttonbarlayout-CWCEU2OJBR6Z7FSTGZZ4XBLLTXB2B74SDZZX4WD3SM2MIX7PEBCQ/blueocean-dashboard/src/main/js/components/RunDetails.jsx
2492 	[INFO]   42:50  error  A space is required after '{'                object-curly-spacing
2493 	[INFO]   42:58  error  Missing space before value for key 'height'  key-spacing
2494 	[INFO]   42:64  error  A space is required before '}'               object-curly-spacing
```

**Comment by i386** [comment]
Build failed because autofavorite broke

**Comment by sophistifunk** [comment]
(ノಠ益ಠ)ノ彡┻━┻

**Comment by michaelneale** [comment]
LGTM functionality wise - need it to pass build and ATH but when it does - :bee: from me.

**Pull request merged**
