### PR TITLE
Feature/jenkins 38323 editor drag and drop 3

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
Not entirely sure I can finish this 100% before time runs out but it feels pretty close to me. Here are some of the pending items:
- In IE11 and Edge, there is a bug where dragging to the bottom of the list won't scroll it. Issue is discussed here with some links to libs or workarounds: react-dnd/react-dnd#324
- In the revised design, there was a desire to adjust the position of the steps in the list as the user drags over them to create an empty space to show where the item will be dropped (similar to JIRA board's interaction). This ought to be feasible but will require probably some use of `translate` and absolute positioning of element representing the "empty space."
- There may one or two small CSS bugs where borders overlap or a border is missing; there are a large number of combinations of nested steps and hard to test all of them.
- We might want to consider making the "there are no child steps defined" message a drop target. I can likely find time to do that this week, although might not be a bad task for @NicuPascu to try.

See [JENKINS-38323](https://issues.jenkins-ci.org/browse/JENKINS-38323).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
any reason why shrinkwrap file has changed?

**Comment by cliffmeyers** [comment]
@michaelneale yes, react-dnd was added as a dependency. Also js-builder-jest so tests are run for editor with the same tooling as other modules

**Comment by cliffmeyers** [comment]
A couple examples of the current interactivity:

editor-drag-drop-2018-01-16-a

editor-drag-drop-2018-01-16-b

**Comment by cliffmeyers** [comment]
@michaelneale I did a deep dive on this with @NicuPascu on Mon/Tue and plan to talk to him on Wed/Thu to answer any additional questions.

**Comment by michaelneale** [comment]
very nice @cliffmeyers and @NicuPascu !

This looks pretty close to being usable?

**Comment by michaelneale** [comment]
@NicuPascu I think these conflicts are due to https://github.com/jenkinsci/blueocean-plugin/pull/1629 - which should be ok to resolve

**Comment by NicuPascu** [comment]
If this goes green I think this would be ok to get merged :bee: , @sophistifunk, @kzantow, @imeredith, if any of you have a few minutes to also do a final review I would appreciate it, thanks

**Comment by michaelneale** [comment]
@NicuPascu if it is green - get it in on monday I say!

Wow this will be awesome

Any objections @kzantow ?

**Pull request merged**
