### PR TITLE
Bug/jenkins 44759 remove search query param

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- See [JENKINS-44759](https://issues.jenkins-ci.org/browse/JENKINS-44759).
- I'm fairly confident the original params code was intended to pass along the locale parameter for I18N but I don't think we really intend to support that anyways.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
@sophistifunk @NicuPascu would you mind reviewing please?

**Comment by sophistifunk** [comment]
The way pipeline links work is totally different in the tables branch, and almost every line in this diff is in conflict. Please assign the ticket to me and I'll make sure Cliff's fixes from this branch get re-applied to mine, and when I've done so I'll close this PR.

**Comment by cliffmeyers** [comment]
@sophistifunk I'm fine too with just redoing this PR after the table changes land. I don't want you to have to keep jumping through hoops to get that PR in.

**Comment by sophistifunk** [comment]
New PR with these changes and updated ATH selectors here: #1160

**Comment by cliffmeyers** [comment]
Closed in favor of #1160

**Pull request closed without merging**
