### PR TITLE
experiment/auto link hpis

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- Automatically link the HPI's for Maven submodules so we don't have to maintain the same list in two places

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
Seems that there might be some issues with this and probably needs more testing. Going to put it on the shelf for now.

**Comment by cliffmeyers** [comment]
Cool, perhaps @michaelneale could give this one a quick test too just to make sure we don't break anyone's ability to do local development easily.

**Comment by michaelneale** [comment]
it was ok when I tried it - but @vivek needs to confirm this one (https://issues.jenkins-ci.org/browse/JENKINS-46704 is breaking all builds even off older master)

**Comment by vivek** [comment]
LGTM 🐝 this is nice one @cliffmeyers!

**Pull request merged**
