### PR TITLE
[JENKINS-43892] Show passing tests

### PR DESCRIPTION
**Pull request by imeredith**
# Description

See [JENKINS-43892](https://issues.jenkins-ci.org/browse/JENKINS-43892).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
this is much asked for so good with me as long as clean. 

Are there any concerns about paging/loading/bloat?

**Comment by i386** [comment]
@imeredith Nice! could you share a screenshot here of this?

**Comment by imeredith** [comment]
@i386 will tomorrow, working on getting another PR tests fixed, so would have to rebuild this one for SS. It basiclally looks like the other tests but with the green tick. All code was already in place to handle them, basical just needed to load'em

**Comment by imeredith** [comment]
@michaelneale I really don't know. Its only gonna load 100 at a time so probably should be ok. Really each section should be async loading but not in scope i think

**Comment by imeredith** [comment]
nvm here it is

**Comment by imeredith** [comment]
image

**Comment by imeredith** [comment]
javascript tests failing, will fix tomorrow

**Comment by i386** [comment]
@imeredith looks great 👍

**Comment by AlanFoster** [comment]
I haven't had a chance to run this build, but I do know that some organisations have large test sets.

i.e. I know that in our organisation we have 20k+ JUnit tests in one monorepo, so I'm not sure if there will be any performance issues here yet 😅

**Pull request merged**
