### PR TITLE
RC preparation

### PR DESCRIPTION
**Pull request by vivek**
- Removed beta from aggreagator name
- Upgraded pipeline editor to 0.2-rc1

# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
Lovely 🐝

**Comment by michaelneale** [comment]
Just checking this locally - I wasn't able to resolve the rc1 via my maven mirror, so even that may take some time.

**Comment by michaelneale** [comment]
I think this is ok  runs locally. The version of the editor doesn't seem to behave well however. I can't save to a new branch when I could before.

**Comment by michaelneale** [comment]
:bee: that regression isn't related to the editor release or this - so can be merged.

**Comment by michaelneale** [comment]
fix for regression above incoming...

**Comment by vivek** [comment]
ATH passes https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/master/1818/pipeline

**Pull request merged**
