### PR TITLE
upgrade to scm-api 2.1.1

### PR DESCRIPTION
**Pull request by i386**
# Description

Minor dependency bump of scm-api

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by kzantow** [comment]
@i386 does this have Git save ability? :trollface:

**Comment by i386** [comment]
@kzantow 
e94be855f3c2bd28eb03bef0cb230519

**Comment by i386** [comment]
Passes ATH

**Comment by i386** [comment]
@kzantow just trying to keep on top of the latest stuff.

**Pull request merged**
