### PR TITLE
JENKINS-48074 show full log in case of no steps and no stages for a failed run

### PR DESCRIPTION
**Pull request by NicuPascu**
# Description
show full log in case of no steps and no stages for a failed run

See [JENKINS-48074](https://issues.jenkins-ci.org/browse/JENKINS-48074).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by NicuPascu** [comment]
no_steps

**Comment by michaelneale** [comment]
I like this approach!

So how to best test this - if this approach seems right (@vivek or @imeredith to code review?), could we have an ATH test for this?

**Comment by i386** [comment]
This bug has made me angry for so long - nice job! 

9d68265d933ede155fd468e859a8dd38df0b580b61a5dc02cc9a5773316c8648

**Comment by vivek** [comment]
@NicuPascu nice job 👍 can you add ATH test. May be a variation on one of the mbp test in ATH?

**Comment by NicuPascu** [comment]
@michaelneale @vivek Working on an ATH test now

**Comment by vivek** [comment]
LGTM 🐝

**Pull request merged**
