### PR TITLE
[FIX-JENKINS-49948] vulnerabilities in bo js dependencies

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-49948](https://issues.jenkins-ci.org/browse/JENKINS-49948).

Update vulnerable moment dep

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by scherler** [comment]
ShrinkCRAP ;) fixed

**Comment by kzantow** [comment]
Yeah, I hate shrinkcrap, too, but it's there for now. :'(

**Comment by kzantow** [comment]
🐝 from me after a passing build

**Comment by michaelneale** [comment]
looks like a breaking change for moment.js

**Comment by vivek** [comment]
@scherler breaking changes in `moment.duration.format()`:

```
TypeError: _moment2.default.duration(...).format is not a function at TimeManager.format (/home/jenkins/slave/workspace/blueocean_PR-1688-AHAFGL2KZN6M72CYTMXY66YILZBW3G3TCIEEPRTTH4TWNCVZ5XVQ/blueocean-dashboard/node_modules/@jenkins-cd/blueocean-core-js/dist/js/utils/TimeManager.js:46:54) at convertJenkinsNodeDetails (/home/jenkins/slave/workspace/blueocean_PR-1688-AHAFGL2KZN6M72CYTMXY66YILZBW3G3TCIEEPRTTH4TWNCVZ5XVQ/blueocean-dashboard/src/main/js/components/PipelineRunGraph.jsx:99:3380)
```

**Comment by scherler** [comment]
I raised now the version of  `moment-duration-format`. 

It works fine in my browser 
screenshot_2018-03-13_18-47-32

However the test in dashboard is failing, but should not

**Comment by scherler** [comment]
@vivek I think I know what is going on. I think the test needs to have a published version of the core-js since it seems that it is picking up the old version. (published: '0.0.170':  2017-10-18T20:11:52.822Z')

I tried to publish a new version, however the `dist` folder is not generated anymore hence it I cannot publish a version of core-js to use it in the tests.

**Comment by vivek** [comment]
@scherler I see. @NicuPascu, I think you released JDL to npm recently, how did it worked over there?

@kzantow any idea what might be going on? My understanding was that with hpi, the tests will continue using whatever the latest version there is, no need to publish new version of `blueocean-core-js`.

**Comment by NicuPascu** [comment]
I just published the JDL without re-publishing core-js, the reason I published the JDL was that if other projects would need the latest JDL they could get it from npm

**Comment by kzantow** [comment]
@vivek i think @scherler is right, basically because of the sorta lax publishing of core-js and jdl, tests are getting an old version (due to the horribleness of npm and my attempted workarounds for the upstream plugins)

**Comment by kzantow** [comment]
The "most correct" npm-ish fix is what I described before: spawning an npm proxy for the upstream dependencies. I have the code for that pretty much done, but it conflicts potentially with `frontend-maven-plugin`, as it will _also_ do an NPM install, potentially without the correct proxy being in place...

**Comment by vivek** [comment]
@kzantow so what can we do to make this test pass?

**Comment by scherler** [comment]
@vivek publish a versión for npm. ...most quick fix is bring back the dist generation and publish a new version of core-js. Then raise deps on all modules to that version. ...old school. 😉

...needless to say that I am doing the dance ATM as I adviced about that from happening, It has hit bo before us though ;)   

Anyway if no one beats me to it I wil bring back the dist generation and will go old shool to fix that, publishing a new version mañana.

**Comment by kzantow** [comment]
@vivek -- the easiest thing to do is just disable the test ;)

**Comment by vivek** [comment]
@kzantow hmm, not sure if we want to go that far though. Whats the downside resurrecting 'dist' generation? Such issues might come in the future, better to get it in order, no?

**Comment by kzantow** [comment]
We'll just have to bump all the versions all the time again, but not as bad as it was, as we only really have to do it in isolated situations like this.

**Comment by vivek** [comment]
@kzantow yeah, I think it should be ok. What changes are needed to create dist? is it matter of adding `mkdir dist` somewhere in script? Maybe suggest changes needed or open another PR to get what it needs to enable core js release?

**Comment by kzantow** [comment]
@vivek it's just a... _bump the version_ then `npm run gulp` and then `npm publish` and then update all the versions everywhere to the new one, I'm sure @NicuPascu can take care of it :)

**Comment by NicuPascu** [comment]
I have published and installed JDL and core-js, I also had to fix the TimeDuration-spec test because the test would substract 1ms from 178d 0h 0m 0s and expect the time to change to 177d 23h 59m 59s, in the new version that would happen only if a minimum of 501ms are substracted, for easier reading I substracted a full second, the build should succeed now

**Comment by scherler** [comment]
@NicuPascu cheers. BTW `npm run gulp` is not producing the dist dir anymore, however `npm run gulp build` does.

**Comment by vivek** [comment]
Thanks @NicuPascu!

**Pull request merged**
