### PR TITLE
Bug/jenkins 43861 input param modal grows too wide

### PR DESCRIPTION
**Pull request by NicuPascu**
# Description
JDL PR: https://github.com/jenkinsci/jenkins-design-language/pull/175
See [JENKINS-43861](https://issues.jenkins-ci.org/browse/JENKINS-43861).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by NicuPascu** [comment]
@cliffmeyers can you please fix the shrinkwrap in this PR for me? I get that fsevents error we encountered together and can't install the JDL beta package in core-js

**Comment by sophistifunk** [comment]
Code looks good 🐝

**Comment by michaelneale** [comment]
ping @cliffmeyers - I think @NicuPascu needs your help batman!

**Comment by cliffmeyers** [comment]
@michaelneale @NicuPascu I updated the shrink but then realized there was already a conflict with master. I reached out to Thor to see if he has similar npm / shrink issues since he's a Linux user as well.

**Comment by michaelneale** [comment]
@NicuPascu do you need any help from @cliffmeyers to get the shrinkwrap sorted out?

**Comment by NicuPascu** [comment]
after a few attempts I think I managed to make it work

**Pull request merged**
