### PR TITLE
JENKINS-40466# Reflect cause of blockage in synthetic step

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-40466](https://issues.jenkins-ci.org/browse/JENKINS-40466).

I tried this script:

```
pipeline {
  agent none
  stages {
    stage ('first') {
     agent { 
      label 'first' 
     }
     steps{
          sh 'echo "from first"'
      }
    }
  }
}
```

GET http://localhost:8080/jenkins/blue/rest/organizations/jenkins/pipelines/:pipelineId/runs/:runId/nodes/

```
[
   {
      "state" : "QUEUED",
      "result" : "UNKNOWN",
      "startTime" : "2017-01-10T13:35:30.688-0800",
      "id" : "4",
      "actions" : [],
      "_links" : {},
      "durationInMillis" : 8690535,
      "causeOfBlockage" : "Waiting for next available executor",
      "_class" : "io.jenkins.blueocean.rest.impl.pipeline.PipelineNodeImpl",
      "displayName" : "first",
      "edges" : [],
      "input" : null
   }
]
```

image

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
I tried with sample above, but could not see this happening, it never shows the synthetic step (this could also do with updating to master for the scm rollback)

**Comment by vivek** [comment]
@michaelneale Hmm, let me merge latest master and see if thats causing this. Otherwise I might ping you for some screen share time.

**Comment by i386** [comment]
@vivek I don't think we want the status to be queued/unbuilt here - can it be running?

**Comment by michaelneale** [comment]
@i386 I actually like that it is distinct from running *my* stuff, as it is in a holding pattern effectively.

**Comment by i386** [comment]
I'd be curious to get @brody's opinion on the indicator

**Comment by vivek** [comment]
@i386 Its queued so its marked queued, I thought I fixed a bug:) Lets wait for @brody's opinion.

**Comment by vivek** [comment]
@michaelneale with latest master, I see it working fine, that is with the script given in the PR description, the synthetic step is shown in UI with cause of blockage. See the gif:

out

**Comment by i386** [comment]
@vivek ship it. We can do a follow up on the status later

**Comment by brody** [comment]
@vivek @i386 the step colour should be blue with a pulsating icon to show its queued / in progress, without a progress ring. Grey is the colour used for abort, so the queued blue is definitely the way to go.
image

**Comment by i386** [comment]
@brody am I right by saying you want this indicator?

jan-23-2017 13-38-00

**Comment by brody** [comment]
@i386 correct, only reversed. White indicator on a blue background.

**Comment by i386** [comment]
@brody ack. 

@vivek is there some way for the frontend to discern this kind of step vs other steps? e.g. a different `_class` or field?

**Comment by michaelneale** [comment]
:bee: I can see this now nicely.. 

Well it does set "causeOfBlockage" that can be used by future UI enhancements, so I am ok with this going on in any case, so I think there might be enough here to go with for now.

**Pull request merged**
