### PR TITLE
Feature/jenkins 36974 35796 stop build

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- This PR includes changes from #440 so ideally we'll merge than first, then merge master again to clean up the diff.
- See [JENKINS-35796](https://issues.jenkins-ci.org/browse/JENKINS-35796).
- See [JENKINS-36974](https://issues.jenkins-ci.org/browse/JENKINS-36974).
- This PR incorporates the following changes
  - [x] Add a "Stop" button to the Activity tab, to the right of any build that is running or queued,
  - [x] Add a "Stop" button to Run Details for any build that is running (not sure if handling queued is in scope or feasible; conversations are in-progress)
  - [x] Replace the "Run" button on the Activity tab for non multi-branch projects with the new implementation
  - [x] Replace the "Run" buttons on the Branches and PR tabs with the new implementation (this wasn't called out in any ticket but seems sensible to do)
- TODO item:
  - [ ] Find a better way to prevent duplicate toasts being fired when a job is started or stopped. This is handled now in ToastService - and while it works - it's perhaps concerning that multiple instances of Run button bound to the same pipeline are firing dup toasts, and that Favorites from the dashboard will also attempt to propagate a toast.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
needs updating to master again...

**Comment by cliffmeyers** [comment]
Gonna wait for JWT to land before I merge again.

**Comment by michaelneale** [comment]
ace

**Comment by cliffmeyers** [comment]
Also closing this PR; superseded by #448

**Pull request closed without merging**
