### PR TITLE
Fixed 2.60.1 LTS version

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by vivek** [comment]
@imeredith There was incorrect version for 2.60.1 and download was failing. There is a bug in ATH that reports success even if jenkins download failed. That should come in separate PR.

**Comment by michaelneale** [comment]
:bee:

**Comment by michaelneale** [comment]
@imeredith can we merge this one in?

**Comment by imeredith** [comment]
🐝

**Pull request merged**
