### PR TITLE
Bug/jenkins 45083 ms edge x icon doubled on fastsearch

### PR DESCRIPTION
**Pull request by NicuPascu**
# Description
ms edge doesn't properly support the ':not([value=""])' selector, so it always shows the clear icon. It also has a built in clear icon that appears when text is inserted. This solution hides our custom clear icon because the built in one works as intended.

See [JENKINS-45083](https://issues.jenkins-ci.org/browse/JENKINS-45083).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
@NicuPascu got a screenshot handy?

**Comment by NicuPascu** [comment]
@i386 here is empty state with no focus
scrnshot1

text in input
scrnshot2

**Comment by i386** [comment]
@NicuPascu thanks 👍

**Comment by michaelneale** [comment]
nice :bee: (dont forget the deploy dance)

**Comment by sophistifunk** [comment]
Looks pretty clear to me 🐝

**Pull request merged**
