### PR TITLE
JENKINS-43923# Improve blueocean-git-pipeline code coverage

### PR DESCRIPTION
**Pull request by vivek**
Remove pipeline update API. It was done in the beginning thinking UI
needs it for github. Later on create API (POST) is used for both
creation and update. It's not used anywhere else.

# Description

See [JENKINS-43923](https://issues.jenkins-ci.org/browse/JENKINS-43923)

Now blueocean-git-pipeline code coverage is 100% class and 85% lines.

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
@vivek I wasn't able to setup a github pipeline with no Jenkisnfiles with this - it failed to save from the editor - could be related? 

This touches a lot of sensitive areas, a lot of testing is needed.

**Comment by vivek** [comment]
@michaelneale github save during creation is broken on master. That's separate. This is pretty straight forward change. Update API is removed because its not used and we planned to remove it anyways. Other changes are tests. I have done end to end testing on my part, more testing won't hurt, more the better:)

**Comment by cliffmeyers** [comment]
Let me know if you need any help troubleshooting it @vivek

**Comment by vivek** [comment]
@cliffmeyers There is nothing to troubleshoot. editor save is broken on master, is fixed in https://github.com/jenkinsci/blueocean-plugin/pull/1078. Maybe wait till that gets merged to avoid any confusion.

**Comment by vivek** [comment]
@michaelneale merged latest master, give it a spin whenever you can.

**Comment by michaelneale** [comment]
still getting failures due to the classic form not working. 

These failures are now worse than they have ever been, need to look into why.

**Comment by michaelneale** [comment]
I am wondering if it is something abotu this branch... can't possibly see how though.

**Comment by michaelneale** [comment]
yeah I tested creating a new git pipeline - so LGTM. 
I am still worried about intermittent ATH failures though - so can we wait until tomorrow and see if that can be fixed?

**Comment by cliffmeyers** [comment]
I was getting the exact same failure in ATH in my branch for #1059 . Once I merged master it was resolved.

**Comment by michaelneale** [comment]
I have updated this to master - if it passes and you are still happy vivek - consider this a :bee: from me

**Comment by michaelneale** [comment]
:bee:

**Pull request merged**
