### PR TITLE
clean up depManagement

### PR DESCRIPTION
**Pull request by jtnord**
slf4j is managed by the jenkins core bom via the plugin-pom so remove
these dependencies.

I left duplicates like hamcrest as there seems to be some questionable
useage and as I can not actually build the plugin in order to test it
felt like I should not break something

# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by jtnord** [comment]
checked the resulting hpi files after building with `mvn install -DskipTests -Dskip.npm -Dskip.yarn` (because the project does not build on windows)

`c:\cygwin\bin\find.exe . -regex ".*/target/[^/]*hpi" -exec unzip -l {} ; | grep WEB-INF/lib/[a-z]`

produces

```
     3953  03-11-2021 13:48   WEB-INF/lib/blueocean.jar
   103140  03-11-2021 13:47   WEB-INF/lib/blueocean-bitbucket-pipeline.jar
   339669  08-14-2020 18:19   WEB-INF/lib/commons-codec-1.12.jar
   577742  09-07-2020 13:54   WEB-INF/lib/commons-lang3-3.11.jar
    55003  08-14-2020 18:20   WEB-INF/lib/maven-artifact-3.5.0.jar
   247351  09-02-2020 18:12   WEB-INF/lib/plexus-utils-3.0.24.jar
    95421  03-11-2021 13:44   WEB-INF/lib/blueocean-commons.jar
    16981  03-11-2021 13:46   WEB-INF/lib/blueocean-config.jar
   238177  03-11-2021 13:44   WEB-INF/lib/blueocean-core-js.jar
    36549  03-11-2021 13:46   WEB-INF/lib/blueocean-dashboard.jar
    20241  03-11-2021 13:46   WEB-INF/lib/blueocean-events.jar
     3487  03-11-2021 13:47   WEB-INF/lib/blueocean-executor-info.jar
    56292  03-11-2021 13:46   WEB-INF/lib/blueocean-git-pipeline.jar
   284220  08-14-2020 18:11   WEB-INF/lib/commons-lang-2.6.jar
    77345  03-11-2021 13:46   WEB-INF/lib/blueocean-github-pipeline.jar
    13317  03-11-2021 13:44   WEB-INF/lib/blueocean-i18n.jar
    12156  03-11-2021 13:47   WEB-INF/lib/blueocean-jira.jar
  2256213  09-30-2020 10:57   WEB-INF/lib/guava-18.0.jar
    30424  03-11-2021 13:45   WEB-INF/lib/blueocean-jwt.jar
   257824  10-06-2020 15:05   WEB-INF/lib/jose4j-0.6.0.jar
    41139  08-28-2020 13:46   WEB-INF/lib/slf4j-api-1.7.26.jar
     8190  03-11-2021 13:46   WEB-INF/lib/blueocean-personalization.jar
   216086  03-11-2021 13:45   WEB-INF/lib/blueocean-pipeline-api-impl.jar
    27240  03-11-2021 13:47   WEB-INF/lib/blueocean-pipeline-editor.jar
    38421  03-11-2021 13:45   WEB-INF/lib/blueocean-pipeline-scm-api.jar
   284220  08-14-2020 18:11   WEB-INF/lib/commons-lang-2.6.jar
   121261  03-11-2021 13:44   WEB-INF/lib/blueocean-rest.jar
     3223  10-06-2020 15:05   WEB-INF/lib/capability-annotation-1.2.jar
   158486  03-11-2021 13:45   WEB-INF/lib/blueocean-rest-impl.jar
   751238  09-15-2020 12:23   WEB-INF/lib/commons-collections4-4.1.jar
     2715  10-06-2020 15:05   WEB-INF/lib/keen-client-api-java-5.2.0.jar
    46530  10-06-2020 15:05   WEB-INF/lib/keen-client-java-core-5.2.0.jar
    65261  08-14-2020 18:14   WEB-INF/lib/oro-2.0.8.jar
    59529  03-11-2021 11:31   WEB-INF/lib/uap-java-1.5.0.jar
    89556  03-11-2021 13:44   WEB-INF/lib/blueocean-web.jar
  1150577  03-11-2021 13:44   WEB-INF/lib/jenkins-design-language.jar
```

EEk need to update

**Comment by jtnord** [comment]
```
[INFO] Assembling webapp blueocean-jwt in C:\workarea\source\github\jenkinsci\blueocean-plugin\blueocean-jwt\target\blueocean-jwt
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, com.fasterxml.jackson.core:jackson-annotations:jar:2.12.1]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, com.fasterxml.jackson.core:jackson-core:jar:2.12.1]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, com.fasterxml.jackson.core:jackson-databind:jar:2.12.1]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.12.1]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.12.1]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, com.fasterxml.jackson.datatype:jackson-datatype-json-org:jar:2.12.1]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.1]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.1]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.12.1]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, io.jenkins.plugins:snakeyaml-api:jar:1.27.0]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.1, jakarta.activation:jakarta.activation-api:jar:1.2.1]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.1, jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, org.bitbucket.b_c:jose4j:jar:0.6.0]
[DEBUG] Processing: jose4j-0.6.0.jar
[INFO] Bundling direct dependency jose4j-0.6.0.jar
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:mailer:jar:1.32.1, org.jenkins-ci.plugins:display-url-api:jar:2.3.4]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:mailer:jar:1.32.1]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, com.fasterxml.jackson.datatype:jackson-datatype-json-org:jar:2.12.1, org.json:json:jar:20190722]
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, org.bitbucket.b_c:jose4j:jar:0.6.0, org.slf4j:slf4j-api:jar:1.7.26]
[DEBUG] Processing: slf4j-api-1.7.26.jar
[WARNING] Bundling transitive dependency slf4j-api-1.7.26.jar (via jose4j)
[DEBUG] Considering artifact trail [io.jenkins.blueocean:blueocean-jwt:hpi:1.24.5-SNAPSHOT, io.jenkins.blueocean:blueocean-commons:jar:1.24.5-SNAPSHOT, org.jenkins-ci.plugins:jackson2-api:jar:2.12.1, io.jenkins.plugins:snakeyaml-api:jar:1.27.0, org.yaml:snakeyaml:jar:1.27]
[INFO] Generating hpi C:\workarea\source\github\jenkinsci\blueocean-plugin\blueocean-jwt\target\blueocean-jwt.hpi
[INFO] Building jar: C:\workarea\source\github\jenkinsci\blueocean-plugin\blueocean-jwt\target\blueocean-jwt.hpi
[DEBUG] adding directory META-INF/
[DEBUG] adding entry META-INF/MANIFEST.MF
[DEBUG] adding directory WEB-INF/
[DEBUG] adding directory WEB-INF/lib/
[DEBUG] adding entry WEB-INF/lib/blueocean-jwt.jar
[DEBUG] adding entry WEB-INF/lib/jose4j-0.6.0.jar
[DEBUG] adding entry WEB-INF/lib/slf4j-api-1.7.26.jar
[DEBUG] adding entry WEB-INF/licenses.xml
[DEBUG] adding directory META-INF/maven/
[DEBUG] adding directory META-INF/maven/io.jenkins.blueocean/
[DEBUG] adding directory META-INF/maven/io.jenkins.blueocean/blueocean-jwt/
[DEBUG] adding entry META-INF/maven/io.jenkins.blueocean/blueocean-jwt/pom.xml
[DEBUG] adding entry META-INF/maven/io.jenkins.blueocean/blueocean-jwt/pom.properties
```

🤔

**Comment by jtnord** [comment]
so I think this is another bug in the HPI plugin in determining what to bundle.

jenins core depends on some slf4j libraries but not directly on `slf4j-api` (which is wrong).  so it is a transitive dep (3 level) and scope provided.  
`slf4j-api` is `compile` scope in `jose4j` so is a level 2 dep - as far as `maven` dependencies are converned this wins and is promoted.
my view however is that hpi should be Jenkins aware and ignoring this.

**Comment by olamy** [comment]
#2135 I prefer using the maven semantic `provided` for those dependencies as it's the use case here we use them directly here but they are provided by the `server`

**Comment by olamy** [comment]
fixed by #2135

**Pull request closed without merging**
