### PR TITLE
Jenkins 36131 "Show all" link required anywhere a log is displayed

### PR DESCRIPTION
**Pull request by scherler**
**Decription**

- [X] works for freestyle
- [X] works for pipeline
- [X] links "Full log" shown only if needed (e.g. when fetchAll was true we do not show the link)
- [X] in follow along the Full Log button should not never be shown, since you see everything already
- [X] you can link in a "full log"
- [X] in freestyle we really show the full log, however the "show all" link only apply to that step, so the user can look back if needed
- [X] loading the content using ?start=0 will trigger loading of all

AT: https://github.com/jenkinsci/blueocean-acceptance-test/pull/21

**Submitter checklist**
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

**Reviewer checklist**
- [x] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explaination given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
nice. 

It seems to work. 

2 minor things: 
1) the "full log" isn't quite clear it is a link/call to action (just blends in with the text)
2) when the full (large) log is loading (I used the examples from the ATH), it kind of chugs a bit, and there isn't a visual indication that it is busy fetching stuff (and hard to cancel). 

I think #1 could be easily done (is it possible to make it a link style somehow @i386 ?)

#2 may be another ticket/future thing to address 

so partial :bee:

**Comment by i386** [comment]
How about this? This uses a slightly smaller button style (height is 20px and font is 12px). Clicking this button will open the log in a new window.

Its important that the button does not use up the line numbers and should look like the mockup below.

upload-2
How about this? This uses a slightly smaller button style (height is 20px and font is 12px). Clicking this button will open the log in a new window.

Its important that the button does not use up the line numbers and should look like the mockup below.

failing result

**Comment by michaelneale** [comment]
@i386 that is a design change though, we did agree that it would fill in the lines above (in https://issues.jenkins-ci.org/browse/JENKINS-36131) as per classic, so it will take longer to change possibly. 

I do like that button though.

**Comment by i386** [comment]
@michaelneale so we should raise another ticket?

**Comment by michaelneale** [comment]
@i386 I think if the style could be tightened up (possibly to use that button, if Thor has time) then this can be merged, and then we can review/another ticket to "open in new tab".

**Comment by michaelneale** [comment]
Actually if the button is more work (I am aware Thorsten is taking vacation, yay!) then having it as a clear hyperlink would be enough to merge this in, and we can follow up changes as needed.

**Comment by scherler** [comment]
@michaelneale cheers mate! Yeah I am loving the AT, it helped me to develop the testing scripts/pipeline in a more meaningful way. I as well use them on my local box for developing, good to hear that you like them. 

Regarding the loading (#2), I am starting https://issues.jenkins-ci.org/browse/JENKINS-36770  which blocks https://issues.jenkins-ci.org/browse/JENKINS-36771. The last ticket will bring that loading bar and yes the whole rendering 10k logs is hitting my box hard and if you have two 10k logs open the browser is having REAL problems.

Will implement the button now.

**Comment by scherler** [comment]
screenshot from 2016-07-28 10-53-28

I changed as well "in follow along the Full Log button should not be shown, since you see everything already" I saw that while I was in the AT cinema watching "nightwatch"  - great movie, enjoying it every time. ;)  I added a test for that as well

**Comment by i386** [comment]
Hey @scherler if you add the classes `btn-secondary inverse` to the anchor for "Show complete log" it will be styled appropriately 

jenkins blue ocean 2016-07-29 09-20-13

**Pull request merged**
