### PR TITLE
fix official Docker image

### PR DESCRIPTION
**Pull request by ydubreuil**
install-plugins.sh script downloads a too recent version of workflow-job
let's force it to latest compatible version with 2.46 LTS to quickly fix
the Official image.

This is in order to fix the actual 1.1.0 image. 

@i386 @rtyler

### CODE REVIEW

**Comment by i386** [comment]
LGTM @ydubreuil 👍

**Comment by rtyler** [comment]
This pull request doesn't actually update the Jenkinsfile in any way to allow for the `FORCE_REBUILD` option to be passed in as a parameter. As such, I'm not sure how it's expected that this should be used

**Comment by ydubreuil** [comment]
@rtyler I'll follow up with an update of Jenkinsfile

**Comment by ydubreuil** [comment]
Follow up: https://github.com/jenkinsci/blueocean-plugin/pull/1151

**Comment by ndeloof** [comment]
install-plugins.sh is fixed upstream, but the docker image `jenkinsci/jenkins-lts` used by this image has not be regenerated as the Dockerfile was improved, and will probably only be updated on next LTS release. @rtyler I can't see where this image is built, used to run on https://jenkins.ci.cloudbees.com/job/docker/ but moved to jenkins.io IIUC. We should keep all (recent) tags up to date with repository.

`jenkins` official docker image is up-to-date.

**Comment by rtyler** [comment]
@ndeloof Because publishing the Docker container requires what would be considered "release credentials", we run this in an environment referred to as "trusted.ci.jenkins.io" (not a real name) which is off the public internet.

The next time an LTS is released, the Pipeline from jenkinsci/docker will execute automatically and publish those new images. I think the current solution from @ydubreuil will be sufficient until then.

**Pull request merged**
