### PR TITLE
Task/jenkins 44921 update action colors

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

See [JENKINS-44921](https://issues.jenkins-ci.org/browse/JENKINS-44921).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
Related JDL PR https://github.com/jenkinsci/jenkins-design-language/pull/177

**Comment by sophistifunk** [comment]
screen shot 2017-06-28 at 10 59 01 am

**Comment by sophistifunk** [comment]
screen shot 2017-06-28 at 10 59 18 am

**Comment by sophistifunk** [comment]
screen shot 2017-06-28 at 10 59 28 am

**Comment by michaelneale** [comment]
looks good -but I think master is broken, so until that is cleared up - have to sit this one here.

**Comment by sophistifunk** [comment]
Ack

**Comment by michaelneale** [comment]
all clear now

**Comment by i386** [comment]
Looks lovely to me. What say you @brody ?

**Comment by brody** [comment]
image
@i386 @sophistifunk

**Comment by michaelneale** [comment]
:bee:

**Pull request merged**
