### PR TITLE
Deflake `PipelineApiTest.testPipelineQueue`

### PR DESCRIPTION
**Pull request by jglick**
Would I think fix https://github.com/jenkinsci/bom/issues/2916. You can see

```
WARNING: pipeline1 #3 still seems to be running, which could break deletion of log files or metadata in the log
```

which is a good clue that the test is broken. Indeed the test times out reproducibly after

```diff
diff --git blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
index 6151d3a30..78c900448 100644
--- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
+++ blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
@@ -548,6 +548,7 @@ public class PipelineApiTest extends BaseTest {
         b2.doStop();
         j.assertBuildStatus(Result.ABORTED, j.waitForCompletion(b1));
         j.assertBuildStatus(Result.ABORTED, j.waitForCompletion(b2));
+        Thread.sleep(1000);
         for (Queue.Item i : j.jenkins.getQueue().getItems()) {
             j.jenkins.getQueue().cancel(i);
         }
```

since builds 1 and 2 are aborted and then build 3 is scheduled on an executor before the test gets a chance to cancel its queue item. It looks like the mistake came from the succession of #2450 & #2468.

### CODE REVIEW

**Comment by olamy** [comment]
uhm definitely not related to this PR
but it looks https://repo.aws.jenkins.io/public/ is not mirroring/proxying atlassian repos?
```
13:57:04  Caused by: org.apache.maven.model.resolution.UnresolvableModelException: The following artifacts could not be resolved: com.atlassian.platform:platform:pom:3.1.7 (absent): com.atlassian.platform:platform:pom:3.1.7 was not found in https://repo.aws.jenkins.io/public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aws-proxy has elapsed or updates are forced
```

**Comment by jglick** [comment]
> definitely not related to this PR

Yeah https://ci.jenkins.io/job/Plugins/job/blueocean-plugin/job/master/ is broken.

> it looks https://repo.aws.jenkins.io/public/ is not mirroring/proxying atlassian repos?

Maybe related to our no longer proxying Central? File https://github.com/jenkins-infra/helpdesk/issues as needed.

**Comment by olamy** [comment]
> > definitely not related to this PR
> 
> Yeah https://ci.jenkins.io/job/Plugins/job/blueocean-plugin/job/master/ is broken.
> 
> > it looks https://repo.aws.jenkins.io/public/ is not mirroring/proxying atlassian repos?
> 
> Maybe related to our no longer proxying Central? File https://github.com/jenkins-infra/helpdesk/issues as needed.

nah we need to have https://packages.atlassian.com/mvn/maven-public/ (proxying as it was in the past)

**Comment by dduportal** [comment]
> uhm definitely not related to this PR but it looks https://repo.aws.jenkins.io/public/ is not mirroring/proxying atlassian repos?
> 
> ```
> 13:57:04  Caused by: org.apache.maven.model.resolution.UnresolvableModelException: The following artifacts could not be resolved: com.atlassian.platform:platform:pom:3.1.7 (absent): com.atlassian.platform:platform:pom:3.1.7 was not found in https://repo.aws.jenkins.io/public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aws-proxy has elapsed or updates are forced
> ```

The dependency `com.atlassian.platform:platform:pom:3.1.7` is not availble on Atlassian **public** repo: `https://packages.atlassian.com/artifactory/maven-public/com/atlassian/platform/platform/3.1.7` is an HTTP/404.

Please note that https://packages.atlassian.com/mvn/maven-public/ is already mirrored by repo.jenkins-ci.org.

Either they (Atlassian) removed this version of the dependency (too old?) and we might want to bump it (I see the latest patch on the 3.1.x line is [`3.1.19`](https://packages.atlassian.com/artifactory/maven-public/com/atlassian/platform/platform/3.1.19/), or this dependency was stored somewhere else when we had to [clean up repo.jenkins-ci.org](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1857888563) and we have to find why/how it was not a publicly hosted one.

**Comment by olamy** [comment]
interesting as my local repo have it and downloaded it from repo.jenkins-ci.org

```
olamy@pop-os:~/dev/sources/jenkins/blueocean-plugin$ cat ~/.m2/repository/com/atlassian/platform/platform/3.1.7/_remote.repositories
#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Jul 24 10:57:21 AEST 2023
platform-3.1.7.pom>repo.jenkins-ci.org=

```

maybe Atlassian deleted some content (which is a bad idea)

**Comment by dduportal** [comment]
> interesting as my local repo have it and downloaded it from repo.jenkins-ci.org
> 
> ```
> olamy@pop-os:~/dev/sources/jenkins/blueocean-plugin$ cat ~/.m2/repository/com/atlassian/platform/platform/3.1.7/_remote.repositories
> #NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
> #Mon Jul 24 10:57:21 AEST 2023
> platform-3.1.7.pom>repo.jenkins-ci.org=
> ```
> 
> maybe Atlassian deleted some content (which is a bad idea)

Based on this (downloaded from repo.jenkins-ci.org), it most probably came from an old `jcenter` repository: we saw a few dependencies with this behavior (atlassian artifact not available from therer public repository because too old) across projects.

**Comment by olamy** [comment]
yes there is another PR to bump the dependency, I will look at it

**Review by olamy — APPROVED** [review]

**Comment by jglick** [comment]
This deserves a release I think. (CloudBees-internal reference: BEE-37864)

**Comment by olamy** [comment]
1.27.11 released

**Pull request merged**
