### PR TITLE
[JENKINS-39225] Improved (reverted) German translation of Branch(es) …

### PR DESCRIPTION
**Pull request by svijee**
# Description

See [JENKINS-39225](https://issues.jenkins-ci.org/browse/JENKINS-39225).

I've reverted the German translations of "Branch(es)" and "Pull-Request(s)". No one uses the words "Ableger" and/or "Integrationsanfrage" for those words. Both are highly confusing. And IMHO one should not simply translate common technical english words into German. (e.g. "Pipeline" isn't translated and that's good!)

Translations seems to be included in #556 

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

…and Pull-Request(s)

### CODE REVIEW

**Comment by michaelneale** [comment]
thanks @svijee - I will let @scherler and @daniel-beck - 2 native speakers review. 

I need to check this doesn't upset the acceptance test - as it looks in a few places for some specific german translations to make sure the subsystem is working (easy enough to change the test if any of those translations change) - I think it just looks for the nue pipeline button or something. 

cc @scherler 

Looks like ATH is happy with this: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/600/

**Comment by daniel-beck** [comment]
I complained about these terms in #556 already but was ignored. Apparently what gets translated from English into Spanish must also be translated into German.

https://github.com/jenkinsci/blueocean-plugin/pull/556#discussion_r84860841
https://github.com/jenkinsci/blueocean-plugin/pull/556#discussion_r84864307
https://github.com/jenkinsci/blueocean-plugin/pull/556#discussion_r84862969

So a clear :+1: from me.

---

@svijee What's your opinion on Build/Ausführung?

**Comment by svijee** [comment]
> @svijee What's your opinion on Build/Ausführung?

I would still prefer "Build" over "Ausführung". But as I didn't see that on the first attempt, it's not as bad as Integrationsanfrage/Ableger.

**Comment by scherler** [comment]
@svijee @daniel-beck do you really have no german translations for those words? Integrationsanfrage would explain a German from the 18th century what a pull request is. Not translating it is giving up our language. Anyway @svijee Buid is translated as it is in core jenkins (aka classic) where you find Ausführung. 

@svijee @daniel-beck  if you "have to" translate branch and pr into german what would it be?

**Comment by i386** [comment]
What does Github or Bitbucket use for their translation?

**Comment by svijee** [comment]
> do you really have no german translations for those words?

No, everyone uses "pull-requests" and "branch". Some people use "Zweig" for "branch" which is the closest translation but definitely not "Ableger".

> Integrationsanfrage would explain a German from the 18th century what a pull request is. Not translating it is giving up our language. 

Well everyone who uses git (or other SCM) and Jenkins should know what commits/repository/branches/pull-requests are. This is highly confusing and IMHO one shouldn't translate common english technical words. This has not much to do with 'giving up our language' because these are technical words and not common german words.

> Anyway @svijee Buid is translated as it is in core jenkins (aka classic) where you find Ausführung.

Classic jenkins uses "Build". The top-left menu on classic jenkins says "Build-Verlauf" and Build-Executors are "Build-Prozessor" and Build Queue is "Build Warteschlange". This should also be the translation in blue ocean.

> What does Github or Bitbucket use for their translation?
@i386 GitHub and Bitbucket are not translated at all. I think we should take the git cli tool as a reference. There, they don't translate "branch", "request-pull", "commit" etc.

**Comment by michaelneale** [comment]
I am fascinated by Germans from the 18th century talking about pull requests. I have a vivid mental image.

**Comment by svijee** [comment]
@michaelneale YMMD :laughing:

**Comment by scherler** [comment]
@svijee yeah could have sworn I took that from the core but looking at the classic UI I do not see it ATM. If you want to add that to this PR and I will merge it. 

@michaelneale german is a bit like Chinese in the sense that using many old words to describe the new concept  like "Datenverarbeitungsanlage" for computer. ;)

**Comment by svijee** [comment]
> @svijee yeah could have sworn I took that from the core but looking at the classic UI I do not see it ATM. If you want to add that to this PR and I will merge it.

Thanks, done!

> @michaelneale german is a bit like Chinese in the sense that using many old words to describe the new concept like "Datenverarbeitungsanlage" for computer. ;)

That would be rather 'Rechner'. ;)

**Comment by daniel-beck** [comment]
@scherler 

> do you really have no german translations for those words? … Not translating it is giving up our language

I remember the first computer science course in University. I was beyond confused by the terms *Halde* and *Stapel*. I've never heard or seen anyone use those terms for heap and stack before or since.

While perhaps admirable, you're not the *Gesellschaft für deutsche Sprache*. Go with what your users know and use. And they say Branch, Build, Pull-Request (adapted to German grammar only).

**Comment by michaelneale** [comment]
Do you want me to sing the german national anthem to sooth your souls?

**Pull request merged**
