### PR TITLE
JENKINS-36967# Favorite object self link fix

### PR DESCRIPTION
**Pull request by vivek**
**Decription**

**Submitter checklist**
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

1. Favorite a multi-branch project and a branch
2. favorite each of the projects created above. [See doc favorite multi-branch](https://github.com/jenkinsci/blueocean-plugin/tree/bug/JENKINS-36967/blueocean-rest#favorite-a-multi-branch-pipeline)
2. Check _link.self.href of the response, it should be same as the path in above step
3. Get user favorites, each favorite json object's _link.self.href should point to  the value in step 2 above. [see  doc to get user favorites](https://github.com/jenkinsci/blueocean-plugin/tree/bug/JENKINS-36967/blueocean-rest#fetch-user-favorites)

**Reviewer checklist**
- [ ] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explaination given

@reviewbybees

### CODE REVIEW

**Comment by vivek** [comment]
cc @cliffmeyers

**Comment by michaelneale** [comment]
code looks good but need confirmation from @cliffmeyers it solves what he was seeing.

**Comment by cliffmeyers** [comment]
I won't have a chance to test until tomorrow AM but I looked over the tests and the URLs there are what I expect. If you are keen to merge, by all means go ahead.

**Comment by michaelneale** [comment]
:bee: in that case

**Comment by cliffmeyers** [comment]
Tested it and confirmed it works, and have adjusted my UI code accordingly. Thanks @vivek !  🐝

**Pull request merged**
