### PR TITLE
Hacktoberfest - Project URL updated to use Github instead of Wiki

### PR DESCRIPTION
**Pull request by ocristian**
Project URL changed to use Github.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by halkeye** [comment]
Oh heck yes. I've been meaning to do this.

**Comment by halkeye** [comment]
@ocristian is this a hacktoberfest item?

**Comment by ocristian** [comment]
> @ocristian is this a hacktoberfest item?

Hi @halkeye, yes it is. 👍

**Comment by halkeye** [comment]
> Hi @halkeye, yes it is. 👍

awesome. Updated the title to match the slide deck - https://docs.google.com/presentation/d/1_RiCjOrWHCC-w2SwaY7i_jfx8c480oPHwoyI403yAPE/edit#slide=id.g61fd37c8c4_3_93

I'm going to wait for CI to finish, but its a noop change so I'll merge unless there's a major issue (our UI tests are a tad flakey sometimes)

**Comment by ocristian** [comment]
> > Hi @halkeye, yes it is. 👍
> 
> awesome. Updated the title to match the slide deck - https://docs.google.com/presentation/d/1_RiCjOrWHCC-w2SwaY7i_jfx8c480oPHwoyI403yAPE/edit#slide=id.g61fd37c8c4_3_93
> 
> I'm going to wait for CI to finish, but its a noop change so I'll merge unless there's a major issue (our UI tests are a tad flakey sometimes)

That is great. I'm happy to help.
Thanks 👍

**Pull request merged**
