### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@jenkinsci/code-reviewers Any one help me to review this pr, tks.

**Comment by michaelneale** [comment]
hi @LinuxSuRen - not sure why there are so many failures - is your fork possibly an older codebase? It seems a lot of the ATH tests are not working... maybe it is the change to PipelineEditorLink - does it work locally for you?

**Comment by LinuxSuRen** [comment]
My local running is well, and it was fork a latest codebase. So I have no idea why so many ATH tests warning.
@michaelneale

**Comment by michaelneale** [comment]
I'll try ATH locally

**Comment by LinuxSuRen** [comment]
How can I run ATH locally, througth command line?

**Comment by michaelneale** [comment]
yes - the README has details on how to do it - a tad fiddly if you haven't done it before.

**Comment by LinuxSuRen** [comment]
I can find anything about ATH test in README, can you tell where it is?

**Comment by michaelneale** [comment]
@LinuxSuRen oh sorry - the README in this dir: https://github.com/jenkinsci/blueocean-plugin/tree/master/acceptance-tests (commands are run from there).

**Comment by michaelneale** [comment]
Ah @LinuxSuRen I think I see a problem, but not sure of solution. 

When I ran the ATH with `./run.sh --dev` - I opened the URL that it sets up for the ATH jenkins (which runs slightly differently to hpi:run). 

I noted there were 404 errors loading the Messages for english for the editor. This is the first time the editor has been localised, so my theory is that it needs a Messages.properties in the same dir as the chinese one (other modules have it). Trying that now, but may need some help..

**Comment by LinuxSuRen** [comment]
I do not know Messages.properties is must, I will add it later.

**Comment by michaelneale** [comment]
@LinuxSuRen I just confirmed locally that by putting a Messages.properties it works fine

https://github.com/jenkinsci/blueocean-plugin/pull/1620 is my version - but if this one passes - COOL!

Thanks so much @LinuxSuRen for this

**Comment by michaelneale** [comment]
as this is the first localisation of the editor, could @kzantow bless this? or perhaps @NicuPascu ? (some tiny changes to the editor code)

**Comment by LinuxSuRen** [comment]
@michaelneale Any issues still?

**Comment by michaelneale** [comment]
No - should be fine!

**Comment by vivek** [comment]
There is similar PR #1629. @LinuxSuRen are they different?

**Comment by LinuxSuRen** [comment]
They are all translation.

**Comment by vivek** [comment]
@LinuxSuRen right they are. What I meant to ask is, these two PRs different or they overlap each other?

**Comment by LinuxSuRen** [comment]
They don't have different @vivek , the second PR just be laster commit.

**Comment by vivek** [comment]
@LinuxSuRen In that case we should close this PR and review and then merge #1629. Do you agree?

**Comment by michaelneale** [comment]
@vivek can merge this one AND the other one

**Comment by LinuxSuRen** [comment]
@vivek Two of them should be merge, they are not repeat.

**Pull request merged**
