### PR TITLE
[JENKINS-52944] Pass milliseconds to TimeDuration

### PR DESCRIPTION
**Pull request by rodrigc**
# Description

testCase.duration is in seconds, but we must pass milliseconds to TimeDuration.format().

See [JENKINS-52944](https://issues.jenkins-ci.org/browse/JENKINS-52944).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by rodrigc** [comment]
I built blueocean-plugin and did some debugging.

 

On this line:

https://github.com/jenkinsci/blueocean-plugin/blob/b02273dc2a6aee295ac8bd7dbab8eb3a8516a60e/blueocean-dashboard/src/main/js/components/testing/TestCaseResultRow.jsx#L24
 
```
 const duration = TimeDuration.format(testCase.duration, translation, locale);
 ```

the first argument to TimeDuration.format() needs to be milliseconds:

 
https://github.com/jenkinsci/blueocean-plugin/blob/b02273dc2a6aee295ac8bd7dbab8eb3a8516a60e/jenkins-design-language/src/js/components/TimeDuration.jsx#L82

but it is actually seconds:

**Comment by oleg-nenashev** [comment]
> I built blueocean-plugin

Achievement unlocked 🥇, it requires a lot of patience

**Comment by oleg-nenashev** [comment]
It seems that the master branch build is broken as well

**Comment by michaelneale** [comment]
nice one cc @NicuPascu @sophistifunk  if you want to review

**Comment by michaelneale** [comment]
nice one! good catch! (and green!)

**Comment by rodrigc** [comment]
@NicuPascu @sophistifunk @oleg-nenashev Thanks, this is my first time debugging Blue Ocean.  I asked a technical question about Blue Ocean on gitter her: https://gitter.im/jenkinsci/blueocean-plugin?at=5b7936dadd0b74601e2afc64

If you think you might know the answer, please respond over there, and I can read the answer later.

**Comment by rodrigc** [comment]
On ci.jenkins.io, the timestamps for the tests are all *<1s*: https://ci.jenkins.io/blue/organizations/jenkins/Core%2Facceptance-test-harness/detail/PR-224/20/tests

When this fix gets merged, and a new blueocean-plugin is deployed to ci.jenkins.io, we should see the timestamps on the tests there.

**Comment by michaelneale** [comment]
LGTM

**Pull request merged**
