### PR TITLE
[JENKINS-45292] Dropdown should allow custom footer 

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-45292](https://issues.jenkins-ci.org/browse/JENKINS-45292).

screenshot from 2017-07-04 15-09-30

Adding feature, story book and test case.

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
Nice! @sophistifunk review requested

**Comment by sophistifunk** [comment]
LGTM 🐝

**Comment by michaelneale** [comment]
:bee: nice one - and tests too 👌🏽

I see you grasped on to having JDL in same repo (nice to review). Dont' forget the publish dance too! (one happy day we may not need to do that).

**Comment by i386** [comment]
@scherler thank you for the tests ❤️

**Comment by scherler** [comment]
@i386 always trying to add tests, but welcome.

**Pull request merged**
