### PR TITLE
Move to pipeline-model-definition-plugin 0.3

### PR DESCRIPTION
**Pull request by abayer**
# Description

Update to the latest release (0.3) of pipeline-model-definition-plugin.

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by abayer** [comment]
Whoops, somehow borked the `pipeline-stage-step` dependency! Fixed and force-pushed a new commit.

**Comment by abayer** [comment]
Ok, the test failures are because `pipeline-model-definition` now executes empty stages for stages that were planned to run after a failed stage. That's fine and dandy, but it looks like, despite what I thought the result would be, the `FlowNode` that ends up getting the failure on it is the *last* one, not the one that actually failed. I'm trying to see if there's some way to set a `FlowNode` to failed while still continuing, but that logic is, so far as I can tell, very very very wrapped up in execution proper.

@vivek - any thoughts?

**Comment by michaelneale** [comment]
@abayer is this a bug with Kyoto or just a test assertion issue? I can see it would make more sense to have the failure on the flownode that was running... (I know vivek was reworking things with bismuth so that may help here possibly)

**Comment by abayer** [comment]
@michaelneale So it's at the very least a test assertion issue as a result of the changes to "execute" the empty post-failure stages. Then there's the question of where the failure shows up...

**Comment by michaelneale** [comment]
@abayer so - did you want to look at the issue from the pipeline model side first? We can then update this later.

**Pull request closed without merging**
