### PR TITLE
JENKINS-42366 Column filter must handle long values

### PR DESCRIPTION
**Pull request by i386**
# Description

* Min width of the filter should be 100% the width of the branch column
* Max width of the filter should be 250% the width of the branch column
* If text exceeds this limit then it should be ellipsed at the end
* Hovering over the item should reveal its full name

To test just have branches with very long names and some very short ones.

-blueocean-2017-02-28-18-11-18

See [JENKINS-42366](https://issues.jenkins-ci.org/browse/JENKINS-42366).

PTAL @kzantow @brody 

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
such whitespace -- if it passes ATH go for it. The ATH does select an item in teh list, so if it trips up - easy fix.

**Comment by i386** [comment]
Great code btw @kzantow - very easy to understand

**Comment by michaelneale** [comment]
going to get killed in the ghetto tomorrow for that.

**Comment by i386** [comment]
@michaelneale you gonna get popped lol

**Comment by brody** [comment]
@i386 👌  looks good!!

**Pull request merged**
