### PR TITLE
JENKINS-41352 	 JenkinsJENKINS-41352 New dashboard cards

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

See [JENKINS-41352](https://issues.jenkins-ci.org/browse/JENKINS-41352).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [X] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
screen shot 2017-03-13 at 3 41 25 pm

**Comment by michaelneale** [comment]
Looks good to me, passes ATH. 

Hopefully a tuesday blessing from the pope - @i386 and it can go in.

**Comment by i386** [comment]
Pontifex Producto has a nice ring to it. I'll take this for a spin in the morning :)

**Comment by i386** [comment]
@sophistifunk @michaelneale this looks good functionality wise on my local machine but the icons being out of whack makes it feel a bit unfinished (as mentioned yesterday). It would be good to have an answer for fixing the icons soon (not sure how hard this is or not or what is involved).

@brody can you please eyeball?

**Comment by michaelneale** [comment]
@i386 are icons worse than before? otherwise it is scope creep we dont' have time for.

**Comment by sophistifunk** [comment]
screen shot 2017-03-14 at 5 40 42 pm

**Comment by i386** [comment]
a87e8b2539c39b027a31dceed80c07d48516d2161018c1bb4c398f3b5138ca57

**Comment by michaelneale** [comment]
:bee:

**Comment by dragoonis** [comment]
:D best banter

**Comment by sophistifunk** [comment]
Suckers!

**Pull request merged**
