### PR TITLE
[JENKINS-40526] Download logs of stages

### PR DESCRIPTION
**Pull request by imeredith**
# Description

See [JENKINS-40526](https://issues.jenkins-ci.org/browse/JENKINS-40526).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
legit unit test failures as they will need to be changed: 

```

[INFO]   1) RunDetailsArtifacts empty artifacts renders EmptyStateView:
[INFO]      AssertionError: expected 0 to equal 1
[INFO]       at Context.<anonymous> (src/test/js/run-details-artifacts-spec.js:39:20)
[INFO] 
[INFO]   2) RunDetailsArtifacts valid artifacts renders a Table with expected data:
[INFO]      AssertionError: expected 2 to equal 1
[INFO]       at Context.<anonymous> (src/test/js/run-details-artifacts-spec.js:48:20)

```

heh, was just talking to @cliffmeyers this morning about unit tests. These are valid ones to fail but obvously the functionality is changing.

**Comment by michaelneale** [comment]
I still can't get download to work - even with latest change 

I am not sure if download can include the file extension according to html5 - also this won't be supported in IE11

**Comment by michaelneale** [comment]
Can I get someone else to try this and see if it downloads for them?

**Comment by i386** [comment]
@imeredith might have to switch back to the `&download=true` method I think.

**Comment by i386** [comment]
@michaelneale I tested it. BTW all our log methods support sending `content-disposition` if the download param is present.

```
    private void writeLog(StaplerRequest req, StaplerResponse rsp, AcceptHeader accept) {
        try {
            String download = req.getParameter("download");

            if("true".equalsIgnoreCase(download)) {
                rsp.setHeader("Content-Disposition", "attachment; filename=log.txt");
            }

            rsp.setContentType("text/plain;charset=UTF-8");
            rsp.setStatus(HttpServletResponse.SC_OK);

            writeLogs(req, rsp);
        } catch (IOException e) {
            throw new ServiceException.UnexpectedErrorException("Failed to get logText: " + e.getMessage(), e);
        }
    }
```

**Comment by michaelneale** [comment]
Ivan was able to reproduce it, not just my browser. Right clicking and download as also shows this misbehavior.

**Comment by michaelneale** [comment]
The ATH will need a small change to accomodate this too:

noStages.Step 09 (from log-karaoke.noStages)

as it is looking for an empty state - can instead look for log.

**Comment by michaelneale** [comment]
@imeredith do you want to do a PR to the ATH to cover this change?

**Comment by michaelneale** [comment]
Looks better now - works as advertised. If you could update this to master, update the ATH and show it passing - we can merge both in IMO.

**Pull request merged**
