### PR TITLE
add a retry and cleanup between runs

### PR DESCRIPTION
**Pull request by michaelneale**
A suddenly failing test seems related to timing - can only sometimes see it locally. Trying a thing

### CODE REVIEW

**Comment by vivek** [comment]
Failure looks like timing related. Lets see this CI run.

**Comment by michaelneale** [comment]
also have this one: https://github.com/jenkinsci/blueocean-plugin/pull/1613 - was able to see it fail occasionally locally, but really hard to see...

**Comment by michaelneale** [comment]
ok @vivek if this is ok with you - merge this (or the linked one) and we can move forward.

**Comment by vivek** [comment]
LGTM 🐝 Lets get this one in. Less amount of changes.

**Pull request merged**
