### PR TITLE
JENKINS-39763 Move new header components to blueocean-core-js for use in web and dashboard

### PR DESCRIPTION
**Pull request by sophistifunk**
* Move the header / logo components into blueocean-core-js, add storybook support
 * Make some adjustments to i18n so it doesn't block components from appearing in other modules' storybooks
 * Fix a couple of small issues in RunButton
 * Remove components from -dashboard that have been migrated to -core-js, and related stories
 * Add some excludes to storybook webpack config, which we haven't noticed because browserify is smart enough to know them already
 * Re-indent routes so they make sense

# Description

See [JENKINS-39763](https://issues.jenkins-ci.org/browse/JENKINS-39763).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
code looks ok from me (just quick look over) - perhaps @cliffmeyers could review. 

Good old lint errors in the build.. I know how you love them. 

What is to review here in terms of non code - just story books so far?

**Comment by sophistifunk** [comment]
Shouldn't be anything new here, besides the small cleanups and changes to i18n for testability. Just relocating the header components, and encountered a bunch of problems referencing core-js components in dashboard stories, because I initially left the old stories in dashboard as a way to make sure I'd integrated the components properly in core-js

**Comment by michaelneale** [comment]
I kicked it around and things did not catch fire. Which is good... so this might be ok. Would like @cliffmeyers or @imeredith to give this a blessing code wise.

**Comment by imeredith** [comment]
code looks good to me :bee:

**Pull request merged**
