### PR TITLE
Task/jenkins 42283 fetch promise error handlers

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- See [JENKINS-42283](https://issues.jenkins-ci.org/browse/JENKINS-42283).
- Add `ErrorUtils` which will log unhandled JS errors, and log rejected promises that were not handled. In my opinion, this is the most important part of the PR, so we can identify errors more easily during testing or during bug reports. We can also enhance this down the road to pump the error info into support bundle or similar if we so choose.
- Added some unit tests for Fetch

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by kzantow** [comment]
... so excited about this. But is there a way to _not_ import "bluebird" all over the place?

**Comment by cliffmeyers** [comment]
@kzantow yeah, that's a good question. The first time you import bluebird, I believe it overrides the global promise. Unfortunately if you are running say a unit test it may not necessarily get imported. I need to put a little more thought on whether there's a clean way to ensure it's always loaded first in every scenario.

**Comment by cliffmeyers** [comment]
Actually we might be able to handle this cleanly with Jest, and in normal deployment this will get handled automagically when core-js is loaded.. I'll do a little more experimentation with it.

**Comment by michaelneale** [comment]
@cliffmeyers if still relevant - want to update this? review from @NicuPascu or @sophistifunk ?

**Comment by cliffmeyers** [comment]
Yes, it's relevant, and I'll update the npm deps once it gets a thumbs up.

**Comment by cliffmeyers** [comment]
@sophistifunk your point is taken. The one thing we really need to evaluate in addition to basic Promise support is whether the "unhandledrejection" event is supported. Right now it doesn't look so good:

https://developer.mozilla.org/en-US/docs/Web/Events/unhandledrejection

**Pull request merged**
