### PR TITLE
Client-side support for multi-stage parallel branches

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

Client-side support for multi-stage parallel branches in the JDL PipelineGraph renderer and Dashboard client-side parser. 

Still needs changes to `io.jenkins.blueocean.rest.impl.pipeline.PipelineNodeGraphVisitor` to create new stage graph nodes rather than merging them into a single node.

See [JENKINS-38442](https://issues.jenkins-ci.org/browse/JENKINS-38442).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- X Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
screen shot 2017-09-08 at 9 58 26 am

**Comment by sophistifunk** [comment]
screen shot 2017-08-30 at 6 36 57 pm

**Comment by kzantow** [comment]
image

**Comment by kzantow** [comment]
Could we collapse the distance between the nodes on the same parallel branch? e.g. if the normal width is 120, the first has margin left of 60 margin right of 30, second has margin left of 30?

**Comment by sophistifunk** [comment]
@kzantow that's a pretty good idea, I'll experiment with that and see how it goes with long labels.

**Comment by sophistifunk** [comment]
Hmmm, ATH issue seems to be GH-related.

**Comment by michaelneale** [comment]
ATH failure is due to *long sad story* so if that is only failure can be ignored for now.

**Comment by michaelneale** [comment]
looking good

**Comment by sophistifunk** [comment]
Added a parameter to tweak the spacing as per @kzantow's suggestion. We can punt on the number until James gets back, particularly since the backend can't generate these graphs yet anyway. Check the storybook if you wanna play with it.

screen shot 2017-09-08 at 3 26 57 pm

**Comment by michaelneale** [comment]
nice - well if others think, this can go in when ready - nice hack week @sophistifunk !

**Comment by sophistifunk** [comment]
Not sure what's going on in CI, but it keeps failing on `GithubCreationTest`, which runs successfully for me locally from Idea.

**Comment by michaelneale** [comment]
image

@sophistifunk :bee:

**Pull request merged**
