### PR TITLE
Topic/include pr branch info in run

### PR DESCRIPTION
**Pull request by i386**
# Description

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
What's the best way to eyeball this?

**Comment by i386** [comment]
Fire it up and browse via rest to a run of a branch

**Comment by michaelneale** [comment]
@i386 did you mean to merge this or was it meant to wait for @scherler ?

**Comment by i386** [comment]
@michaelneale I did accidentally and reverted.

**Pull request merged**
