### PR TITLE
Bug/jenkins 43702 dashboard more scroll position

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- See [JENKINS-43702](https://issues.jenkins-ci.org/browse/JENKINS-43702).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
ATH passed: https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/master/2185/pipeline/16

**Comment by i386** [comment]
🐝🙌

**Comment by i386** [comment]
Lovely thanks for writing this test.

**Comment by i386** [comment]
@cliffmeyers is there a similar test for the activity and branches (I believe you said we had regressed there at some point?) If not, can you create another ticket to improve the coverage for that area please?

**Comment by cliffmeyers** [comment]
@i386 I had already added a comment to https://issues.jenkins-ci.org/browse/JENKINS-43083 to do just that.

**Comment by i386** [comment]
@cliffmeyers nice, thanks for being proactive :)

**Pull request merged**
