### PR TITLE
JENKINS-42450# optimized scan if there is one repo created.

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-42450](https://issues.jenkins-ci.org/browse/JENKINS-42450).

[x] Upgrade workflow-multibranch plugin to 2.13 and fix multi-branch changeset test

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by vivek** [comment]
@cliffmeyers It optimizes org scanning in case there is only one repo. PTAL.

cc: @i386 @michaelneale, will be great if you can take a look to see it gets you the optimization you were expecting.

**Comment by i386** [comment]
You legend @vivek. I'll give this a go tomorrow :)

**Comment by michaelneale** [comment]
ATH isn't entirely happy with it though. https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/1764/
althought for some reason it isn't showing good test reports any more when things fail (it used to).

**Comment by vivek** [comment]
`commitMessages.Create Job` is failing with a timeout error. Not sure if its legit.

**Comment by michaelneale** [comment]
It retries a lot of times, so it usually means something else is wrong and that may be hiding it. It used to show a better report of what things failed, but lately hasn't been doing a very good job in some cases where things fail in a few different ways. It might be worth running it again, but I think in all likelihood it has picked up something

**Comment by michaelneale** [comment]
still not happy - obvious question but this isn't based on a slightly older master is it?

**Comment by michaelneale** [comment]
I can see error locally with commitMesages, so I think it is real. Perhaps it is same thing - needs checkout scm in it to work properly. I'll try that.

**Comment by michaelneale** [comment]
OK trying with https://ci.blueocean.io/job/ATH-Jenkinsfile/job/improvement%252FJENKINS-42450/2/ and https://github.com/jenkinsci/blueocean-acceptance-test/pull/128

**Comment by vivek** [comment]
Ah, yeah that should be it. Thanks.

**Comment by michaelneale** [comment]
passes ATH tweaked and sniff test.

I tried it locally - not sure if it is noticably faster but I am not sure what i am comparing to. 

:bee: but also please merge the ATH one at same time.

**Comment by michaelneale** [comment]
OK @vivek wants to wait for @cliffmeyers to check this out. This seems ok - but I am not sure if it is practically any faster. When I add a repo I can see it just branch indexes that at the back end, but the front end sits there for about a minute as normal. 

I see this in the log: 

Mar 09, 2017 1:42:19 PM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: multibranchorg/newbie #20170309.134216 branch indexing action completed: SUCCESS in 2.9 sec

But it is almost a minute later before it shows the activity screen. Branches have even finished executing before it decides to show there. So I am not sure if there is a front end :bug: or what. This certainly works well, but maybe there is more work ? @cliffmeyers you abel to try this?

**Comment by michaelneale** [comment]
reminder to merge the ATH branch as well if this one goes in.

**Comment by cliffmeyers** [comment]
@michaelneale I believe we are seeing the 60s timeout because we changed the UI logic to always listen for "org folder scan complete" event and I'm guessing that event is not being sent now. Would be a simple change to allow it to react to either event. Will make a change in this branch and test it once I finish up what I'm working on currently.

**Comment by michaelneale** [comment]
ah that makes sense. Yes I can see the MBP scan finishes in seconds, so if this picked that event up - would be super snappy

**Comment by cliffmeyers** [comment]
@i386 @michaelneale @vivek I've pushed an update that allows the UI to respond to the multibranch indexing complete event. I tested this against jenkinsci (~1700 repos) and creation completed in under 10s on my machine. I'd say that's pretty good.

**Comment by vivek** [comment]
@cliffmeyers Some tests are failing PipelineCard related ones, https://ci.blueocean.io/blue/organizations/jenkins/blueocean/detail/improvement%2FJENKINS-42450/4/pipeline

**Comment by michaelneale** [comment]
@vivek I think theya re known flaky tests (very infrequent) so trying again to see if related.

**Comment by vivek** [comment]
@cliffmeyers @michaelneale is this all good to merge?

**Comment by michaelneale** [comment]
I am just testing it locally - ATH running here: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/improvement%252FJENKINS-42450/3/ as it needs that new branch to pass

**Comment by michaelneale** [comment]
:bee: once ATH passes - seems good to me locally from a quick test (both adding single repo and autodiscover)

**Comment by michaelneale** [comment]
GO GO GO 

GHOST RIDER YOU ARE CLEARED TO LAND. ATH passes - just remmeber to merge it at same time.

**Pull request merged**
