### PR TITLE
JENKINS-46009 Pipeline graph on safari is incorrectly placed to the left

### PR DESCRIPTION
**Pull request by sophistifunk**
bug/JENKINS-46009-safari-pipeline-alignment * Fix pipeline graph alignment issue in Safari

# Description

See [JENKINS-46009](https://issues.jenkins-ci.org/browse/JENKINS-46009).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
screen shot 2017-08-07 at 10 35 39 am

**Comment by sophistifunk** [comment]
Gave it a quick test with small and big (scrolling) pipeline in Chrome, FF, and Safari. Seems to be doing the right thing.

**Comment by i386** [comment]
@sophistifunk cool - screenshot looks good

**Comment by i386** [comment]
Thanks for the quick fix here!

**Comment by sophistifunk** [comment]
Ping @vivek @michaelneale what's the status on the code freeze lads?

**Comment by vivek** [comment]
@sophistifunk Sometime Monday PDT.

**Comment by sophistifunk** [comment]
Churbrew

**Pull request merged**
