### PR TITLE
[FIX JENKINS-47569] Finalize js-builder & js-extensions post-HPI

### PR DESCRIPTION
**Pull request by kzantow**
# Description

See [JENKINS-47569](https://issues.jenkins-ci.org/browse/JENKINS-47569).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
ping @sophistifunk mind givin this a spin at your leisure? 

@kzantow is the executor plugin also published in non snapshot form (just while we are talking finalising)

**Comment by michaelneale** [comment]
is https://github.com/jenkinsci/blueocean-plugin/pull/1505 really needed to finalize?

**Comment by kzantow** [comment]
@michaelneale yes, #1505 is required, this one first. I can't publish the executor plugin until this is released in beta, really.

**Comment by michaelneale** [comment]
if this passes I guess it is ok - not really code to review 👍🏻

**Pull request merged**
