### PR TITLE
Feature/jenkins 38598 message enricher org folder indexing

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- **Refer to commit accdc27 as it better illustrates the actual changes. The rename I did makes the usual diff hard to read unfortunately**
- Related to #700 and [JENKINS-39794](https://issues.jenkins-ci.org/browse/JENKINS-39794): the goal is to enrich the message when an org folder indexing succeeds or fails

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by cliffmeyers** [comment]
cc @tfennelly

**Comment by tfennelly** [comment]
LGTM 👍

**Comment by cliffmeyers** [comment]
per discussion, will move the enum into pubsub-light-module and revise this PR.

**Comment by cliffmeyers** [comment]
ATH passed: https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/master/1512/pipeline/18

**Pull request merged**
