### PR TITLE
[FIX-JENKINS-39802_REGRESSION_Copy_pasting_lines_from_the_log_also_copies…

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-39802](https://issues.jenkins-ci.org/browse/JENKINS-39802).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
@scherler can you explain what the new behaviour is?

**Comment by scherler** [comment]
@i386 the opposite of: "Copy/pasting lines from the log also copies line numbers" ;) Meaning you do not copy the line numbers anymore.

**Comment by michaelneale** [comment]
This seems to have upset the ATH around karaoke: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/991/console I think its expecting different behavior. I'm sure it is a minor thing.

**Comment by michaelneale** [comment]
functionality looks good - but the ATH is missing <code>: 

```
Timed out while waiting for element <code> to be present
```

in log-karaoke/stages-old.js at least (probably some other places). 
Once ATH is coaxed to be happy - :bee: from me as this works nicely. Good one.

**Comment by scherler** [comment]
@michaelneale true, good catch. Will fix that now.

**Comment by scherler** [comment]
ATH https://github.com/jenkinsci/blueocean-acceptance-test/pull/105

**Comment by michaelneale** [comment]
As long as ATH happy - :bee: from me.

**Pull request merged**
