### PR TITLE
[pre-push] Add pre-push hook and small introduction how to use it

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-37847](https://issues.jenkins-ci.org/browse/JENKINS-37847).

Enhancements for dev environments. Pre-Push Hooks to prevent triggering doomed builds on the ci.

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
perhaps belongs in bin dir? (that is what it is for, in theory)

**Comment by scherler** [comment]
BLOCKED BY https://github.com/jenkinsci/jenkins-design-language/pull/87
BLOCKS https://github.com/jenkinsci/blueocean-acceptance-test/pull/26

**Comment by kzantow** [comment]
Any way we could do this in a pre-receive or similar hook in the main repo, instead? Assuming there is a Github limitation... also is this a WiP or needs review?

**Comment by michaelneale** [comment]
@kzantow I don't think github let you do that type of thing. 

We could re-arrange the Jenkinsfile to do the checkdeps first, but I think little scripts like this are a good idea if documented.

**Comment by michaelneale** [comment]
can open this if want to resurrect

**Pull request closed without merging**
