### PR TITLE
FIX Jenkins 38009 Executing step is not expanded when there is a proceeding failing step

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-38009](https://issues.jenkins-ci.org/browse/JENKINS-38009).

screenshot from 2016-09-27 17-13-26

# Submitter checklist

- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by tfennelly** [comment]
🐝 LGTM

Not sure what the build fail is.

**Comment by michaelneale** [comment]
@tfennelly the build failure is as npm shrinkwrap seems to make things unstable. It causes it to fetch things from npm which end up corrupted (re-running the build will likely fix it).

**Comment by michaelneale** [comment]
@scherler might want to check the ATH as it claims it died here: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/12/

**Comment by i386** [comment]
Haven't tried it but looks good based on screenshot 👍

**Comment by michaelneale** [comment]
nice, kudos on test case

I think :bee: but watch for the ATH - claims it didn't work (I haven't run it directly against this branch) with a legit looking failure (but may be spurious). I only mention it as changing log behavior may affect karaoke right?

**Comment by scherler** [comment]
Will run ath against it now. Can be that AT is right.

**Comment by michaelneale** [comment]
@scherler did ATH pass for you?

**Comment by michaelneale** [comment]
yep passes here: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/51

so :bee: !

**Pull request merged**
