### PR TITLE
[FIX JENKINS-40116] Fix for null return on request.getPageInfo() in ResourceCacheControl

### PR DESCRIPTION
**Pull request by tfennelly**
# Description

See [JENKINS-40116](https://issues.jenkins-ci.org/browse/JENKINS-40116).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
Looks good, need to check ATH of course

**Comment by michaelneale** [comment]
Running this on the "good hand" ATH here: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/rollback-test/13/

**Comment by michaelneale** [comment]
@tfennelly the good hand is pleased - :bee: assuming ATH branch is sorted out

**Comment by vivek** [comment]
LGTM 🐝

**Pull request merged**
