### PR TITLE
Changes and testing for Declarative 1.2

### PR DESCRIPTION
**Pull request by abayer**
# Description

See [JENKINS-42753](https://issues.jenkins-ci.org/browse/JENKINS-42753), [JENKINS-44391](https://issues.jenkins-ci.org/browse/JENKINS-44391), and more as things get merged into `master` for Declarative 1.2.

Subsumes #1108, using a SNAPSHOT deploy of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/175 to pick up the change to using `stage('foo')` inside the parallel branches.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by i386** [comment]
Ive restarted this PR build

**Comment by abayer** [comment]
Hrm, I'm not getting the coverage check failure when I run locally, so I can't tell what it's complaining about. Good times.

**Comment by vivek** [comment]
Doesn't look like coverage check failure, unit tests succeeds. There are ATH failures though, looks flaky. I replayed the build. 

```
[INFO] Blue Ocean Parent .................................. SUCCESS [ 13.560 s]
[INFO] Common API for Blue Ocean .......................... SUCCESS [ 20.734 s]
[INFO] REST API for Blue Ocean ............................ SUCCESS [ 13.847 s]
[INFO] i18n for Blue Ocean ................................ SUCCESS [  9.379 s]
[INFO] Web for Blue Ocean ................................. SUCCESS [01:47 min]
[INFO] Pipeline SCM API for Blue Ocean .................... SUCCESS [ 13.696 s]
[INFO] JWT for Blue Ocean ................................. SUCCESS [ 29.410 s]
[INFO] REST Implementation for Blue Ocean ................. SUCCESS [03:51 min]
[INFO] Pipeline implementation for Blue Ocean ............. SUCCESS [04:45 min]
[INFO] Events API for Blue Ocean .......................... SUCCESS [ 47.211 s]
[INFO] Dashboard for Blue Ocean ........................... SUCCESS [03:06 min]
[INFO] Personalization for Blue Ocean ..................... SUCCESS [02:00 min]
[INFO] Config API for Blue Ocean .......................... SUCCESS [01:00 min]
[INFO] GitHub Pipeline for Blue Ocean ..................... SUCCESS [03:47 min]
[INFO] Git Pipeline for Blue Ocean ........................ SUCCESS [01:03 min]
[INFO] Bitbucket Pipeline for Blue Ocean .................. SUCCESS [03:16 min]
[INFO] Blue Ocean ......................................... SUCCESS [ 49.238 s]
```

**Comment by abayer** [comment]
@vivek Yup, gonna update this with the parser rewrite PR once the first one gets merged.

**Comment by i386** [comment]
Can the editor understand this format yet? If it can't that's going to be confusing for users

**Comment by kzantow** [comment]
@i386 it might not blow up, but it probably won't work like people expect

**Comment by abayer** [comment]
But then, there are already a lot of Declarative features the editor doesn't support - does it even have when yet?

**Comment by i386** [comment]
We shouldn't further widen that gap when we have the full power to do the opposite. This gets a big -100 from me. 

Lets do what's right for users not what is easiest for us.

**Comment by i386** [comment]
At a very minimum we should be [making sure the editor can roundtrip this format](https://issues.jenkins-ci.org/browse/JENKINS-44390) correctly.

**Comment by abayer** [comment]
So when will Blue Ocean have the time to work on the editor? Because there's only so long we can wait with this requested functionality in Declarative before it's just goofy (and we're already near six months).

**Comment by i386** [comment]
@abayer its next in @cliffmeyers's queue - hopefully next week.

blue ocean development - agile board - jenkins jira 2017-08-10 12-59-16

**Comment by vivek** [comment]
Right, I didn't notice it subsumes https://github.com/jenkinsci/blueocean-plugin/pull/1108 and forgot about that totally, has been there for a while:) Yeah editor experience as noted on this PR show blank screen with parallel stage so definitely something we need to fix that.

**Comment by abayer** [comment]
fyi, @kzantow is working on the editor support as we speak. He apparently had a fair amount of it ready but commented out already.

**Comment by kzantow** [comment]
Well, it's next after Git integration. Haven't started yet. @abayer

**Comment by abayer** [comment]
Ok, I got the ordering wrong. =)

**Comment by michaelneale** [comment]
no longer needed as master is using 1.2 successfully - if you disagree @abayer you can look at me with disapproving eyes (and reopen).

**Pull request closed without merging**
