### PR TITLE
[FIXED JENKINS-36336] Always show fixed tests if there are some

### PR DESCRIPTION
**Pull request by kzantow**
**Decription**

Show 'fixed' tests even if if all tests are passing and the encouraging message is displayed. Addresses: [JENKINS-36336](https://issues.jenkins-ci.org/browse/JENKINS-36336)

**Submitter checklist**
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

**Reviewer checklist**
- [x] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [x] Verified that the appropriate tests have been written or valid explaination given

image

NOTE: this also now addresses: [JENKINS-36930](https://issues.jenkins-ci.org/browse/JENKINS-36930)

@reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
@kzantow interesting case - is that when the build has failed but all the tests are OK?

**Comment by kzantow** [comment]
@i386 yes, not the best screenshot. The tests all passed in this case but the build ended up failing afterwards.

**Comment by michaelneale** [comment]
This was devilishly hard to test. Thanks Obama/ @rtyler 

This worked for the specific case, but I saw a case where there were failures, but they were not shown (only their count reported). 

https://github.com/kzantow/failure-project/tree/test-pass-fail-stage is a branch I created to reproduce this, however, as it probably will only run HEAD you won't see the fixed tests (but I can confirm they work). 

If you do change that branch so there are failing tests, they won't be showing up:

screen shot 2016-07-26 at 3 38 27 pm


So that is a minor :ant: from me.

**Comment by kzantow** [comment]
@michaelneale looks like you hit https://issues.jenkins-ci.org/browse/JENKINS-36930 I fixed it here, can you retest and verify your 🐜  is addressed (and it will now also address JENKINS-36930)?

**Comment by michaelneale** [comment]
🐝 🐝 🐝 🐝 🐝 🐝 🐝 🐝 🐝 

looks great, and adding a test... *side hugs*

**Comment by cliffmeyers** [comment]
Looks good, nice job w/ test. 🐝

**Pull request merged**
