### PR TITLE
verify pubsub-light 1.10 compatibility

### PR DESCRIPTION
**Pull request by tfennelly**
No need to merge this (unless ye want it). Just verifying BO compatibility with pubsub-light 1.10.

If ye want to upgrade, we can create a ticket etc and relabel this PR.

### CODE REVIEW

**Comment by i386** [comment]
Looks fine Tom. We probably should merge - what say you @vivek?

**Comment by michaelneale** [comment]
is this failure anything to do with this? 

```
parameterizedBranchTest(io.jenkins.blueocean.rest.impl.pipeline.MultiBranchTest)  Time elapsed: 18.664 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[SUCCESS]> but was:<[UNKNOWN]>
```

?

**Comment by vivek** [comment]
@michaelneale Probably flaky test. That should not fail because of pubsub plugin changes. I replayed it.

**Comment by tfennelly** [comment]
Definitely seems like this has made the ATH more unstable. The `master` branch seems to be building ok, but this one is hanging.

The only thing I can think of is that it's causing a bit of latency that's screwing with things coz the only diff here should be the fact that there's a `jenkins-instance-url` property in events.

**Comment by michaelneale** [comment]
@tfennelly is your branch well up to date with master? 

If so, does seem related as that hanging is when it misses events right?

**Comment by michaelneale** [comment]
I'll run it again to confirm...

**Comment by michaelneale** [comment]
yes this is very much not working with the ATH

**Comment by tfennelly** [comment]
Prob related to https://issues.jenkins-ci.org/browse/JENKINS-45416 ... obviously more than some latency thing ... I'll look into it first thing in the morning.

**Comment by michaelneale** [comment]
yes that would be it exactly - no events are being picked up, so not just ATH.

**Comment by i386** [comment]
Running a rollback https://github.com/jenkinsci/blueocean-plugin/pull/1248

**Comment by michaelneale** [comment]
will close this - can re-open when we have a new version of pubsub lite to try that has the desired changes (latest one is essentially a rolled back version of bits)

**Pull request closed without merging**
