### PR TITLE
Bug/jenkins 46436 parallel script graph error

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- See [JENKINS-46436](https://issues.jenkins-ci.org/browse/JENKINS-46436).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
The requirements on exactly how to fix this are a little fuzzy, so tagging as WIP for now.

**Comment by cliffmeyers** [comment]
This is an example of fixing the bug by hardening the `PipelineGraph` and `RunPipelineGraph` component to not throw exceptions when passing incomplete data.

jenkins-46436-1-limit-100-top

jenkins-46436-2-limit-100-bottom

**Comment by cliffmeyers** [comment]
cc @i386 @michaelneale please have a look at discussion on linked JIRA ticket and let me know how I should proceed. Thanks!

**Comment by sophistifunk** [comment]
bbm-bueno

**Pull request merged**
