### PR TITLE
Check the error details from Bitbucket API response if exist before parsing it

### PR DESCRIPTION
**Pull request by LinuxSuRen**
# Description

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [x] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
Hi @olamy, sorry to ping you directly. I'm not sure if you're a maintainer of this plugin. This is a very small fix. But please take a look at this PR if you don't mind. My project (as mentioned above) relies on this.

**Comment by olamy** [comment]
@LinuxSuRen no worries. Would it be difficult to add a test?

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen no worries. Would it be difficult to add a test?

Of course, I've done that. Please check https://github.com/jenkinsci/blueocean-plugin/pull/2141/commits/873eeb98aaa6adf164b477ed1859911fbb4188bf

**Comment by olamy** [comment]
@LinuxSuRen thanks a lot for this! I will check on my tomorrow morning.

**Comment by LinuxSuRen** [comment]
No worries. Glod to help here.

**Comment by LinuxSuRen** [comment]
hi @olamy , I'm wondering if you have the release permission on this plugin. This PR can fix [one bug](https://github.com/kubesphere/kubesphere/issues/3523#issuecomment-803730199) from my project [KubeSphere](https://github.com/kubesphere/kubesphere/). And we will release it soon. So it would be good to have a release if you're able to do that.

**Comment by olamy** [comment]
@LinuxSuRen yes I will. I just need 2/3 days to see if I can squeeze more PRs.
Is it fine for you?

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen yes I will. I just need 2/3 days to see if I can squeeze more PRs.
> Is it fine for you?

Thanks for the quick response. It's totally ok for me.

**Comment by LinuxSuRen** [comment]
hi @olamy , Just in case that you might be busy. Just a friendly reminder about the release.

**Comment by olamy** [comment]
@LinuxSuRen oops sorry been busy with long Easter weekend etc... if not tomorrow then no time before Monday

**Pull request merged**
