### PR TITLE
Generate URL to user avatar on User resource

### PR DESCRIPTION
**Pull request by i386**
# Description

See [JENKINS-39764](https://issues.jenkins-ci.org/browse/JENKINS-39764).

To test install the gravatar plugin and have a gravatar registered for your Jenkins email address. Hit the rest resource for your user and you should see an avatar field in the response.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by vivek** [comment]
Changes LGTM 🐝 Please add a test for it, :bug for that:)

**Comment by michaelneale** [comment]
Does this need a client side component?

**Comment by i386** [comment]
@michaelneale it will when we put the new header design in

**Comment by vivek** [comment]
LGTM 🐝

**Comment by michaelneale** [comment]
@i386 but I want it now

**Comment by i386** [comment]
@michaelneale you'll have to wait for santa.

**Pull request merged**
