### PR TITLE
JENKINS-48278 Send daily job stats to Keen.io

### PR DESCRIPTION
**Pull request by i386**
# Description

Sends an event to keen every day that looks like the following:
```
{
  name: 'job_stats',
  properties: {
     singlePipelineScripted: 1,
     singlePipelineDeclarative: 1,
     pipelineDeclarative: 1,
     pipelineScripted: 1,
     freestyle: 1,
     matrix: 1,
     other: 1
  }
}
```

See [JENKINS-48278](https://issues.jenkins-ci.org/browse/JENKINS-48278)

### CODE REVIEW

**Comment by i386** [comment]
@abayer I need to know how to start the `JobAnalytics` executor on Jenkins startup

**Comment by abayer** [comment]
@i386 So you want something like [this](https://github.com/jenkinsci/jenkins/blob/0fc375e9e4abc238aad67fb29f8fdd29f7084968/core/src/main/java/jenkins/model/DownloadSettings.java#L89) - inherit from `AsyncPeriodicWork` and tada, you get everything you need for free.

**Comment by i386** [comment]
Thanks @abayer! I’ve made that a thing. Need to figure out how to order the “other” category and then tests should pass.

**Comment by i386** [comment]
@abayer do you know how to fix this?
```
[INFO] ------------------------------------------------------------------------
[INFO] Building Pipeline implementation for Blue Ocean 1.4.0-beta-1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ blueocean-pipeline-api-impl ---
[INFO] 
[INFO] --- maven-hpi-plugin:2.0:validate (default-validate) @ blueocean-pipeline-api-impl ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:display-info (display-info) @ blueocean-pipeline-api-impl ---
[INFO] Maven Version: 3.3.3
[INFO] JDK Version: 1.8.0_131 normalized as: 1.8.0-131
[INFO] OS Info: Arch: amd64 Family: unix Name: linux Version: 4.4.0-1035-aws
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (display-info) @ blueocean-pipeline-api-impl ---
[INFO] Ignoring requireUpperBoundDeps in com.google.code.findbugs:jsr305
[INFO] Ignoring requireUpperBoundDeps in com.google.guava:guava
[WARNING] Rule 5: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 paths to dependency are:
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins.workflow:workflow-job:2.14.1
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.10
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins.workflow:workflow-cps:2.42
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.9
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins.workflow:workflow-api:2.22
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.10
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins.workflow:workflow-support:2.14
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.9
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins.workflow:workflow-multibranch:2.16
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.10
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins.workflow:workflow-durable-task-step:2.13
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.10
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins:pipeline-graph-analysis:1.5
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.10
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins:htmlpublisher:1.14
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:1.14.2
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins:pipeline-input-step:2.8
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.5
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins.workflow:workflow-support:2.14
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.9
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins:pipeline-stage-step:2.2
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.1
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins.workflow:workflow-basic-steps:2.6
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.12
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkins-ci.plugins.workflow:workflow-scm-step:2.6
    +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.9
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-io.jenkins.blueocean:blueocean-rest-impl:1.4.0-beta-1-SNAPSHOT
    +-org.jenkins-ci.plugins:junit:1.23
      +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.12
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkinsci.plugins:pipeline-model-definition:1.2.5
    +-org.jenkinsci.plugins:pipeline-model-api:1.2.5
      +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.14
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkinsci.plugins:pipeline-model-definition:1.2.5
    +-org.jenkins-ci.plugins:docker-workflow:1.9
      +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.2
and
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.4.0-beta-1-SNAPSHOT
  +-org.jenkinsci.plugins:pipeline-model-definition:1.2.5
    +-org.jenkins-ci.plugins:credentials-binding:1.11
      +-org.jenkins-ci.plugins.workflow:workflow-step-api:2.13 (managed) <-- org.jenkins-ci.plugins.workflow:workflow-step-api:2.9
```

**Pull request merged**
