### PR TITLE
[JENKINS-39857_Display_steps_durations_in_Blue_Ocean] Add duration in…

### PR DESCRIPTION
**Pull request by scherler**
…formation to the result item

# Description

See [JENKINS-39857](https://issues.jenkins-ci.org/browse/JENKINS-39857) and [JENKINS-41282](https://issues.jenkins-ci.org/browse/JENKINS-41282).

# Depends on

https://github.com/jenkinsci/jenkins-design-language/pull/135

# showview

https://youtu.be/nao7UX0v8r0

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
Unfortunately I think this one needs to be done the same time as: https://issues.jenkins-ci.org/browse/JENKINS-41282 so that the humanize function is the same in both places.

**Comment by scherler** [comment]
@michaelneale we use the humanize function from jdl so when we change it we change it over there. Speaking of which https://github.com/moment/moment/issues/348 seems that the "normal" one is not given more precised output and it is recommended to use either https://github.com/EvanHahn/HumanizeDuration.js or write our own http://stackoverflow.com/questions/14157341/how-can-i-humanize-this-complete-duration-in-moment-js-javascript

**Comment by michaelneale** [comment]
IMO makes sense to have our own one as it will likely change.

**Comment by scherler** [comment]
@michaelneale agree, further it could be done with `format` which we already use in the rest.

**Comment by scherler** [comment]
@michaelneale  fixes now as well https://issues.jenkins-ci.org/browse/JENKINS-41282

**Pull request merged**
