### PR TITLE
Fix problems scrolling large pipelines

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

See [JENKINS-43201](https://issues.jenkins-ci.org/browse/JENKINS-43201).

# Submitter checklist
- [X] Link to JIRA ticket in description, if appropriate.
- [X] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by sophistifunk** [comment]
screen shot 2017-07-31 at 6 19 33 pm

**Comment by sophistifunk** [comment]
Double scrollbars make baby Jesus cry, but without some serious refactoring of this page I'm not sure what we can do about it.

**Comment by sophistifunk** [comment]
As this also has some small changes to JDL, I'll wait until this and #1277 are in master before publishing new prod releases of JDL and core-js.

**Comment by sophistifunk** [comment]
Silly pipeline for testing: https://gist.github.com/sophistifunk/68ab14929f58b5d2150bcc65674b5e19

**Comment by michaelneale** [comment]
ok :bee: from me - if you can do the update dance and it gets a green tick - get it in!

**Comment by kzantow** [comment]
*sigh* this rewrite I'm sitting on might have fixed this...

**Comment by michaelneale** [comment]
@kzantow oh?

**Comment by sophistifunk** [comment]
I'm thinking the release dance, rather than the scrolling, right?

**Comment by michaelneale** [comment]
ah yes good point @sophistifunk... carry on.

**Comment by sophistifunk** [comment]
Le sigh

**Pull request merged**
