### PR TITLE
JENKINS-41242: footer adjustments

### PR DESCRIPTION
**Pull request by imeredith**
# Description

Build it and look at the footer.

NOTE: SNAPSHOT's have a longish version, release versions will be as expected.

See [JENKINS-41242](https://issues.jenkins-ci.org/browse/JENKINS-41242).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
@imeredith got a screenshot?

**Comment by imeredith** [comment]
image

**Comment by imeredith** [comment]
That is what jenkins reports as its version number

**Comment by i386** [comment]
LGTM

**Comment by michaelneale** [comment]
:bee:

**Pull request merged**
