### PR TITLE
Bug/jenkins 44571 show more log broken

### PR DESCRIPTION
**Pull request by cliffmeyers**
# Description
- See [JENKINS-44571](https://issues.jenkins-ci.org/browse/JENKINS-44571).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by cliffmeyers** [comment]
This implements the workaround suggested by @i386 to just open the full raw log in a new tab.

Freestyle:
show-more-fix-1-freestyle

Pipeline:
show-more-fix-2-pipeline

I'm running ATH against this change now, not sure whether this part is actually tested currently.

**Comment by cliffmeyers** [comment]
cc @michaelneale @imeredith @kzantow

**Comment by cliffmeyers** [comment]
ATH passed. I'm going to merge this now and if for some reason we want to do a fancier fix we can easily revert this one.  cc @kzantow have at it :)

**Comment by michaelneale** [comment]
fantastic @cliffmeyers !

**Comment by i386** [comment]
@cliffmeyers thanks so much 👍

**Pull request merged**
