### PR TITLE
Feature/steplabel

### PR DESCRIPTION
**Pull request by nidve01**

### CODE REVIEW

**Comment by i386** [comment]
@nidve01 interesting - is this to add better descriptions to steps?

**Comment by nidve01** [comment]
@i386 Yep, since displayName for step is static had to add new label for better description

**Comment by i386** [comment]
@nidve01 got an example of how this would change? We've been discussing this for a while on https://issues.jenkins-ci.org/browse/JENKINS-37324

**Comment by nidve01** [comment]
@i386 Is this resolved? I found a way, but this need multiple workflow plugin changes.

**Comment by i386** [comment]
@nidve01 I know Sam Van Oort is looking into something that can help here. If you are interested, post to the mailing list and ask where its at :)

**Comment by nidve01** [comment]
@i386
Do we have formal fix for adding a name/label for the sh step? Is this marked as resolved 
https://issues.jenkins-ci.org/browse/JENKINS-36933 by providing a workaround with nested stage. Is there a better solution available besides the nested stage?

**Comment by i386** [comment]
@nidve01 we are going to implement https://issues.jenkins-ci.org/browse/JENKINS-37324

**Pull request closed without merging**
