### PR TITLE
[JENKINS-38496] Make steps show as aborted if they are aborted

### PR DESCRIPTION
**Pull request by imeredith**
# Description

Changes to backend to make steps show as aborted if they are aborted.

JDL PR: https://github.com/jenkinsci/jenkins-design-language/pull/137

See [JENKINS-38496](https://issues.jenkins-ci.org/browse/JENKINS-38496).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
Err I mean aborted

**Comment by kzantow** [comment]
@i386 seems like it should make them show as aborted, since it's operating on the `FlowNode`, but I've not dealt with that in the slightest... what say you, @imeredith ?

**Comment by blueoceandeploy** [comment]
It should, testing probably needed

**Comment by imeredith** [comment]
It should be, but exhaustive testing probably shold be done :).

**Comment by i386** [comment]
@imeredith I assume you've tested it?

**Comment by imeredith** [comment]
@i386 yes but i was hoping @michaelneale  could take a look today

**Comment by michaelneale** [comment]
Not sure how to test it - but couldn't make it work. 

The pipeline I used: 

```
node {
    stage("first") {
      sh 'ping -c 4 www.apple.com'
    }
    stage("second") {
        sh 'ping -c 40 www.apple.com'
    }
    stage("third") {
        sh 'ping -c 4 www.apple.com'
    }
    
}

```

I then aborted it in the middle stage. This had a few problems: 

* Result screen never showed it as failure (I had to do a refresh)
* When refreshing, I showed it as following: 

screen shot 2017-01-30 at 12 07 02 pm

Which doesn't seem right.

**Comment by imeredith** [comment]
@michaelneale i was testing with sleeps. I wonder if it shows as failure becuase it aborts a shell script that will return a non zero. Will look into it tomorrow

**Comment by michaelneale** [comment]
yes could well be that - the sleeps are probably not representative of real scenarios so wouldn't surprise me at all if they behave differently .

**Comment by imeredith** [comment]
Working as intended.. Step as returned with script error, not aborted. If we want it to be aborted we need to file issue upstream

**Comment by michaelneale** [comment]
I am unable to build just this branch locally (master is ok) - any ideas? 

```
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ blueocean-web ---
[INFO] Running 'npm install' in /Users/michaelneale/projects/paas/blueocean-plugin/blueocean-web
[INFO] 
[INFO] > @jenkins-cd/blueocean-core-js@0.0.54 prepublish /Users/michaelneale/projects/paas/blueocean-plugin/blueocean-core-js
[INFO] > gulp
[INFO] 
[ERROR] [12:59:01] Local gulp not found in ~/projects/paas/blueocean-plugin/blueocean-core-js
[ERROR] [12:59:01] Try running: npm install gulp
[ERROR] npm ERR! addLocal Could not install /Users/michaelneale/projects/paas/blueocean-plugin/blueocean-core-js
[WARNING] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[ERROR] npm ERR! Darwin 16.3.0
[ERROR] npm ERR! argv "/Users/michaelneale/projects/paas/blueocean-plugin/blueocean-web/node/node" "/Users/michaelneale/projects/paas/blueocean-plugin/blueocean-web/node/node_modules/npm/bin/npm-cli.js" "install"
[ERROR] npm ERR! node v6.4.0
[ERROR] npm ERR! npm  v3.10.3
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] 
[ERROR] npm ERR! @jenkins-cd/blueocean-core-js@0.0.54 prepublish: `gulp`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the @jenkins-cd/blueocean-core-js@0.0.54 prepublish script 'gulp'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the @jenkins-cd/blueocean-core-js package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     gulp
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs @jenkins-cd/blueocean-core-js
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls @jenkins-cd/blueocean-core-js
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /Users/michaelneale/projects/paas/blueocean-plugin/blueocean-web/npm-debug.log
```

**Comment by michaelneale** [comment]
Looks better now. ATH passes. 

The favourite card still shows as red - but probably another PR for that? Given taht - :bee: from me.

**Comment by i386** [comment]
Favorite card should be updated before this ticket gets closed out.

Nice job!

**Comment by michaelneale** [comment]
@imeredith @scherler an ATH test for this? A backend test could help too

**Comment by imeredith** [comment]
yes im doing a backend test

**Comment by michaelneale** [comment]
This includes the favourite change now too with JDL version?

**Comment by michaelneale** [comment]
:bee: usual ATH disclaimers yadayada

**Comment by scherler** [comment]
@michaelneale I was thinking unit test as @imeredith provided buth ATH never hurts

**Comment by imeredith** [comment]
Test I added looks flaky. Seeing if I can improve it.

**Pull request merged**
