### PR TITLE
Simplify the dashboard API client a little

### PR DESCRIPTION
**Pull request by benlangfeld**
# Description

In the process of preparing https://github.com/jenkinsci/blueocean-plugin/pull/1517, I identified some duplication in the processing of API responses that can be removed.

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by benlangfeld** [comment]
@cliffmeyers @scherler Are you happy with this?

**Comment by michaelneale** [comment]
rerunning tests. 

ping @cliffmeyers @kzantow look ok? I like the smell of deleted code ;)

**Comment by michaelneale** [comment]
thanks @benlangfeld

**Comment by michaelneale** [comment]
@benlangfeld BTW if you want to be given repo access, that would be fine (then you could work on branches etc)

**Pull request merged**
