### PR TITLE
JENKINS-44391# Parallel stage support

### PR DESCRIPTION
**Pull request by vivek**
# Description

See [JENKINS-44391](https://issues.jenkins-ci.org/browse/JENKINS-44391).

Parallel stage visualization seems to work fine. There is one side effect upgrading to `pipeline-model-definition:1.2-beta-2`, there is extra synthetic step appears during initialization: `Set job properties`. @abayer is this intentional.

This extra step resulted in to changing couple tests which was asserting on number of expected steps.

Tested it by converting a pipeline script with parallel to stage parallels: https://github.com/vivek/app-store-demo/blob/parallel-stage/Jenkinsfile#L15-L41. 

Visualization and karaoke seems to work ok.

image

## Pipeline Editor
Shows blank screen. It probably needs to be changed to be aware of parallel stages. Looks like presence of parallel stages is tripping it. Here is the output of 

`http://localhost:8080/jenkins/pipeline-model-converter/toJson`

```json
{
   "status" : "ok",
   "data" : {
      "result" : "success",
      "json" : {
         "pipeline" : {
            "agent" : {
               "type" : "docker",
               "arguments" : [
                  {
                     "value" : {
                        "value" : "maven",
                        "isLiteral" : true
                     },
                     "key" : "image"
                  }
               ]
            },
            "post" : {
               "conditions" : [
                  {
                     "branch" : {
                        "steps" : [
                           {
                              "name" : "junit",
                              "arguments" : [
                                 {
                                    "value" : {
                                       "isLiteral" : true,
                                       "value" : "**/target/surefire-reports/TEST-*.xml"
                                    },
                                    "key" : "testResults"
                                 }
                              ]
                           },
                           {
                              "name" : "archive",
                              "arguments" : [
                                 {
                                    "value" : {
                                       "value" : "**/target/*.jar",
                                       "isLiteral" : true
                                    },
                                    "key" : "includes"
                                 }
                              ]
                           }
                        ],
                        "name" : "default"
                     },
                     "condition" : "always"
                  }
               ]
            },
            "stages" : [
               {
                  "name" : "Build",
                  "branches" : [
                     {
                        "name" : "default",
                        "steps" : [
                           {
                              "arguments" : [
                                 {
                                    "value" : {
                                       "isLiteral" : true,
                                       "value" : "mvn clean source:jar package"
                                    },
                                    "key" : "script"
                                 }
                              ],
                              "name" : "sh"
                           }
                        ]
                     }
                  ]
               },
               {
                  "name" : "Browser Tests",
                  "parallel" : [
                     {
                        "branches" : [
                           {
                              "name" : "default",
                              "steps" : [
                                 {
                                    "name" : "sh",
                                    "arguments" : [
                                       {
                                          "value" : {
                                             "isLiteral" : true,
                                             "value" : "echo setting up selenium environment"
                                          },
                                          "key" : "script"
                                       }
                                    ]
                                 },
                                 {
                                    "arguments" : [
                                       {
                                          "value" : {
                                             "isLiteral" : true,
                                             "value" : "ping -c 5 localhost"
                                          },
                                          "key" : "script"
                                       }
                                    ],
                                    "name" : "sh"
                                 }
                              ]
                           }
                        ],
                        "name" : "Firefox"
                     },
                     {
                        "name" : "Safari",
                        "branches" : [
                           {
                              "name" : "default",
                              "steps" : [
                                 {
                                    "arguments" : [
                                       {
                                          "key" : "script",
                                          "value" : {
                                             "value" : "echo setting up selenium environment",
                                             "isLiteral" : true
                                          }
                                       }
                                    ],
                                    "name" : "sh"
                                 },
                                 {
                                    "name" : "sh",
                                    "arguments" : [
                                       {
                                          "value" : {
                                             "isLiteral" : true,
                                             "value" : "ping -c 8 localhost"
                                          },
                                          "key" : "script"
                                       }
                                    ]
                                 }
                              ]
                           }
                        ]
                     },
                     {
                        "name" : "Chrome",
                        "branches" : [
                           {
                              "name" : "default",
                              "steps" : [
                                 {
                                    "name" : "sh",
                                    "arguments" : [
                                       {
                                          "value" : {
                                             "isLiteral" : true,
                                             "value" : "echo setting up selenium environment"
                                          },
                                          "key" : "script"
                                       }
                                    ]
                                 },
                                 {
                                    "name" : "sh",
                                    "arguments" : [
                                       {
                                          "key" : "script",
                                          "value" : {
                                             "value" : "ping -c 3 localhost",
                                             "isLiteral" : true
                                          }
                                       }
                                    ]
                                 }
                              ]
                           }
                        ]
                     },
                     {
                        "name" : "Internet Explorer",
                        "branches" : [
                           {
                              "name" : "default",
                              "steps" : [
                                 {
                                    "arguments" : [
                                       {
                                          "value" : {
                                             "isLiteral" : true,
                                             "value" : "echo setting up selenium environment"
                                          },
                                          "key" : "script"
                                       }
                                    ],
                                    "name" : "sh"
                                 },
                                 {
                                    "arguments" : [
                                       {
                                          "key" : "script",
                                          "value" : {
                                             "value" : "ping -c 4 localhost",
                                             "isLiteral" : true
                                          }
                                       }
                                    ],
                                    "name" : "sh"
                                 }
                              ]
                           }
                        ]
                     }
                  ]
               },
               {
                  "branches" : [
                     {
                        "name" : "default",
                        "steps" : [
                           {
                              "arguments" : [
                                 {
                                    "key" : "script",
                                    "value" : {
                                       "isLiteral" : true,
                                       "value" : "mvn findbugs:findbugs"
                                    }
                                 }
                              ],
                              "name" : "sh"
                           }
                        ]
                     }
                  ],
                  "name" : "Static Analysis"
               },
               {
                  "name" : "Deploy",
                  "branches" : [
                     {
                        "name" : "default",
                        "steps" : [
                           {
                              "arguments" : [
                                 {
                                    "key" : "script",
                                    "value" : {
                                       "isLiteral" : true,
                                       "value" : "mvn source:jar package -Dmaven.test.skip"
                                    }
                                 }
                              ],
                              "name" : "sh"
                           }
                        ]
                     }
                  ]
               }
            ]
         }
      }
   }
}

```

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by michaelneale** [comment]
good to know - seems good. Just marked this as "DO NOT MERGE" as a beta.

**Comment by i386** [comment]
> there is extra synthetic step appears during initializations

@vivek is that an extra pipeline node or step that appears and then disappears? We don't want that.

**Comment by vivek** [comment]
@i386 Its Step, an extra step, doesn't disappear though. always there.  See 'Set job properties' step in the attached image above.

**Comment by i386** [comment]
@vivek gotcha. Are those useful to anyone at all or are they noise? if they are more noisy then I'd rather not show the step.

**Comment by abayer** [comment]
@vivek @i386, that `properties` step...I need to wedge it inside a synthetic stage. Will deal with that.

**Comment by kzantow** [comment]
@abayer @vivek @i386 ... i think this is for things before the first stage starts executing... like allocating a docker image and such, yes? It's important to be able to see that info somewhere, but it disappears; is the idea to put it in some 'init' stage permanently for the run?

**Comment by vivek** [comment]
@abayer thanks. 

> that properties step...I need to wedge it inside a synthetic stage. Will deal with that.

Right, a inside a PRE synthetic stage. But this won't help if we decide not to show it. We need some action or marker to give us a hint that this step was result of declarative doing stuff than anything meaningful for the user.

>  i think this is for things before the first stage starts executing... like allocating a docker image and such, yes? It's important to be able to see that info somewhere, but it disappears; is the idea to put it in some 'init' stage permanently for the run?

Right, we had this discussion in past.  All such steps (declarative generated) are made available inside synthetic stage, we intentionally don't show it and fold them inside the very first stage. This way we show one to one mapping of what user describes in their pipeline script and nodes in visualization. I guess we are talking more about whether this 'Set job properties' needs to be shown at all or how to hide it.

**Comment by abayer** [comment]
Actually, I think I'm refactoring `properties` management in Declarative entirely to address https://issues.jenkins-ci.org/browse/JENKINS-44621. Assuming that pans out, we won't ever actually call the `properties(...)` step directly but will do all property management behind the scenes. So, yay? =)

**Comment by abayer** [comment]
fyi, https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/160 has the `properties` behavior change.

**Comment by vivek** [comment]
@abayer Let me know if it's ready for test, not sure if its settled, based on your conversation with Jesse?

**Comment by i386** [comment]
Work to be be completed:

1. Release of declarative 1.2-beta-3 of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/160 by @abayer 
2. Validate that the job properties step is not shown and all tests pass
3. Complete [JENKINS-44390](https://issues.jenkins-ci.org/browse/JENKINS-44390) so that the Editor roundtrips the new format (ping @kzantow are you able to take a look at this when the jsmodules-as-plugins lands?)
4. Release Editor and Blue Ocean

**Comment by vivek** [comment]
@i386  Added support for skipped parallel stages. They appear now as skipped.

image

I used script at https://github.com/vivek/app-store-demo/blob/parrallel-skipped-stages/Jenkinsfile

**Comment by i386** [comment]
Thanks @vivek 🙌

**Comment by i386** [comment]
@vivek I updated this branch with latest master to keep it healthy

**Comment by vivek** [comment]
@i386 two pipeline node tests failing after this merge. Maybe some pipeline library upgrade caused it, I will look in to them later today.

**Comment by i386** [comment]
@vivek I think @abayer ended up removing the extra flow nodes that were originally introduced into beta1

**Comment by vivek** [comment]
@i386 they are old tests, looks like there is side effect of some change.

**Comment by i386** [comment]
Subsumed by https://github.com/jenkinsci/blueocean-plugin/pull/1308

**Pull request closed without merging**
