### PR TITLE
Remove the pipeline-editor dependency

### PR DESCRIPTION
**Pull request by rtyler**
I heard this lives in the repo now

### CODE REVIEW

**Comment by rtyler** [comment]
522b6c04e691b209f948b81f_736

**Comment by i386** [comment]
Nah still needed in the POM root

**Comment by rtyler** [comment]
ORLY, I thought because it was a module  that wasn't necessary.

3qfzt0

**Comment by i386** [comment]
Nope :( you would have to repeat the version everywhere if you were to use it. Mavens :(

**Pull request closed without merging**
